export const hsk1 = [
{ "simplified" : "的", "traditional" : "的", "pinyin" : "de5", "pinyinAccent" : "de", "definition" : "indicates possession, like adding 's to a noun" },
{ "simplified" : "我", "traditional" : "我", "pinyin" : "wo3", "pinyinAccent" : "wǒ", "definition" : "I; me" },
{ "simplified" : "你", "traditional" : "你", "pinyin" : "ni3", "pinyinAccent" : "nǐ", "definition" : "you (singular)" },
{ "simplified" : "是", "traditional" : "是", "pinyin" : "shi4", "pinyinAccent" : "shì", "definition" : "be; is; are; am" },
{ "simplified" : "了", "traditional" : "了", "pinyin" : "le5", "pinyinAccent" : "le", "definition" : "indicates a completed or finished action" },
{ "simplified" : "不", "traditional" : "不", "pinyin" : "bu4", "pinyinAccent" : "bù", "definition" : "no; not" },
{ "simplified" : "在", "traditional" : "在", "pinyin" : "zai4", "pinyinAccent" : "zài", "definition" : "at; on; in; indicates an action in progress" },
{ "simplified" : "他", "traditional" : "他", "pinyin" : "ta1", "pinyinAccent" : "tā", "definition" : "he; him" },
{ "simplified" : "我们", "traditional" : "我們", "pinyin" : "wo3men5", "pinyinAccent" : "wǒmen", "definition" : "we; us" },
{ "simplified" : "好", "traditional" : "好", "pinyin" : "hao3", "pinyinAccent" : "hǎo", "definition" : "good" },
{ "simplified" : "有", "traditional" : "有", "pinyin" : "you3", "pinyinAccent" : "yǒu", "definition" : "have" },
{ "simplified" : "这", "traditional" : "這", "pinyin" : "zhe4", "pinyinAccent" : "zhè", "definition" : "this" },
{ "simplified" : "会", "traditional" : "會", "pinyin" : "hui4", "pinyinAccent" : "huì", "definition" : "know how to" },
{ "simplified" : "吗", "traditional" : "嗎", "pinyin" : "ma5", "pinyinAccent" : "ma", "definition" : "indicates a yes/no question (added to a statement)" },
{ "simplified" : "什么", "traditional" : "什麼", "pinyin" : "shen2me5", "pinyinAccent" : "shénme", "definition" : "what? (replaces the noun to turn a statement into a question)" },
{ "simplified" : "说", "traditional" : "說", "pinyin" : "shuo1", "pinyinAccent" : "shuō", "definition" : "speak" },
{ "simplified" : "她", "traditional" : "她", "pinyin" : "ta1", "pinyinAccent" : "tā", "definition" : "she" },
{ "simplified" : "想", "traditional" : "想", "pinyin" : "xiang3", "pinyinAccent" : "xiǎng", "definition" : "think; believe; suppose; would like to" },
{ "simplified" : "一", "traditional" : "一", "pinyin" : "yi1", "pinyinAccent" : "yī", "definition" : "one; once; a" },
{ "simplified" : "很", "traditional" : "很", "pinyin" : "hen3", "pinyinAccent" : "hěn", "definition" : "very; quite" },
{ "simplified" : "人", "traditional" : "人", "pinyin" : "ren2", "pinyinAccent" : "rén", "definition" : "person; man; people" },
{ "simplified" : "那", "traditional" : "那", "pinyin" : "na4", "pinyinAccent" : "nà", "definition" : "that; then" },
{ "simplified" : "来", "traditional" : "來", "pinyin" : "lai2", "pinyinAccent" : "lái", "definition" : "come; arrive; ever since; next" },
{ "simplified" : "都", "traditional" : "都", "pinyin" : "dou1", "pinyinAccent" : "dōu", "definition" : "all; both" },
{ "simplified" : "个", "traditional" : "個", "pinyin" : "ge5", "pinyinAccent" : "ge", "definition" : "general measure word" },
{ "simplified" : "能", "traditional" : "能", "pinyin" : "neng2", "pinyinAccent" : "néng", "definition" : "can; be able" },
{ "simplified" : "去", "traditional" : "去", "pinyin" : "qu4", "pinyinAccent" : "qù", "definition" : "go; to leave" },
{ "simplified" : "和", "traditional" : "和", "pinyin" : "he2", "pinyinAccent" : "hé", "definition" : "and; with" },
{ "simplified" : "做", "traditional" : "做", "pinyin" : "zuo4", "pinyinAccent" : "zuò", "definition" : "do; make" },
{ "simplified" : "上", "traditional" : "上", "pinyin" : "shang4", "pinyinAccent" : "shàng", "definition" : "above; up" },
{ "simplified" : "没有", "traditional" : "沒有", "pinyin" : "mei2you3", "pinyinAccent" : "méiyǒu", "definition" : "not have; there is not" },
{ "simplified" : "看", "traditional" : "看", "pinyin" : "kan4", "pinyinAccent" : "kàn", "definition" : "see; look at; to watch" },
{ "simplified" : "怎么", "traditional" : "怎麼", "pinyin" : "zen3me5", "pinyinAccent" : "zěnme", "definition" : "how?" },
{ "simplified" : "现在", "traditional" : "現在", "pinyin" : "xian4zai4", "pinyinAccent" : "xiànzài", "definition" : "now" },
{ "simplified" : "点", "traditional" : "點", "pinyin" : "dian3", "pinyinAccent" : "diǎn", "definition" : "a dot; a little; o'clock" },
{ "simplified" : "呢", "traditional" : "呢", "pinyin" : "ne5", "pinyinAccent" : "ne", "definition" : "indicates a question; how about...?;" },
{ "simplified" : "太", "traditional" : "太", "pinyin" : "tai4", "pinyinAccent" : "tài", "definition" : "too (much)" },
{ "simplified" : "里", "traditional" : "裡", "pinyin" : "li3", "pinyinAccent" : "lǐ", "definition" : "inside; Chinese mile (~.5 km)" },
{ "simplified" : "听", "traditional" : "聽", "pinyin" : "ting1", "pinyinAccent" : "tīng", "definition" : "listen; hear" },
{ "simplified" : "谁", "traditional" : "誰", "pinyin" : "shei2", "pinyinAccent" : "shéi", "definition" : "who" },
{ "simplified" : "多", "traditional" : "多", "pinyin" : "duo1", "pinyinAccent" : "duō", "definition" : "many" },
{ "simplified" : "时候", "traditional" : "時候", "pinyin" : "shi2hou5", "pinyinAccent" : "shíhou", "definition" : "time" },
{ "simplified" : "下", "traditional" : "下", "pinyin" : "xia4", "pinyinAccent" : "xià", "definition" : "fall; below" },
{ "simplified" : "谢谢", "traditional" : "謝謝", "pinyin" : "xie4xie5", "pinyinAccent" : "xièxie", "definition" : "thank you" },
{ "simplified" : "先生", "traditional" : "先生", "pinyin" : "xian1sheng5", "pinyinAccent" : "xiānsheng", "definition" : "Mr.; Sir" },
{ "simplified" : "喜欢", "traditional" : "喜歡", "pinyin" : "xi3huan5", "pinyinAccent" : "xǐhuan", "definition" : "to like" },
{ "simplified" : "大", "traditional" : "大", "pinyin" : "da4", "pinyinAccent" : "dà, dài", "definition" : "big; large" },
{ "simplified" : "东西", "traditional" : "東西", "pinyin" : "dong1xi5", "pinyinAccent" : "dōngxi", "definition" : "things; stuff" },
{ "simplified" : "小", "traditional" : "小", "pinyin" : "xiao3", "pinyinAccent" : "xiǎo", "definition" : "small; young" },
{ "simplified" : "叫", "traditional" : "叫", "pinyin" : "jiao4", "pinyinAccent" : "jiào", "definition" : "to be called" },
{ "simplified" : "爱", "traditional" : "愛", "pinyin" : "ai4", "pinyinAccent" : "ài", "definition" : "love" },
{ "simplified" : "年", "traditional" : "年", "pinyin" : "nian2", "pinyinAccent" : "nián", "definition" : "year" },
{ "simplified" : "请", "traditional" : "請", "pinyin" : "qing3", "pinyinAccent" : "qǐng", "definition" : "please; invite; to treat someone to something" },
{ "simplified" : "回", "traditional" : "回", "pinyin" : "hui2", "pinyinAccent" : "huí", "definition" : "to return; to reply; to go back" },
{ "simplified" : "工作", "traditional" : "工作", "pinyin" : "gong1zuo4", "pinyinAccent" : "gōngzuò", "definition" : "work; a job" },
{ "simplified" : "钱", "traditional" : "錢", "pinyin" : "qian2", "pinyinAccent" : "qián", "definition" : "money; coin" },
{ "simplified" : "吃", "traditional" : "吃", "pinyin" : "chi1", "pinyinAccent" : "chī", "definition" : "eat" },
{ "simplified" : "开", "traditional" : "開", "pinyin" : "kai1", "pinyinAccent" : "kāi", "definition" : "to open; to start; to operate (a vehicle)" },
{ "simplified" : "家", "traditional" : "家", "pinyin" : "jia1", "pinyinAccent" : "jiā", "definition" : "family; home" },
{ "simplified" : "哪", "traditional" : "哪", "pinyin" : "na3", "pinyinAccent" : "nǎa", "definition" : "which; how" },
{ "simplified" : "朋友", "traditional" : "朋友", "pinyin" : "peng2you5", "pinyinAccent" : "péngyou", "definition" : "friend" },
{ "simplified" : "妈妈", "traditional" : "媽媽", "pinyin" : "ma1ma5", "pinyinAccent" : "māma", "definition" : "mom; mum" },
{ "simplified" : "今天", "traditional" : "今天", "pinyin" : "jin1tian1", "pinyinAccent" : "jīntiān", "definition" : "today" },
{ "simplified" : "几", "traditional" : "幾", "pinyin" : "ji3", "pinyinAccent" : "jǐ", "definition" : "how many; several; a few" },
{ "simplified" : "爸爸", "traditional" : "爸爸", "pinyin" : "ba4ba5", "pinyinAccent" : "bàba", "definition" : "Dad" },
{ "simplified" : "些", "traditional" : "些", "pinyin" : "xie1", "pinyinAccent" : "xiē", "definition" : "some; few; several" },
{ "simplified" : "怎么样", "traditional" : "怎麼樣", "pinyin" : "zen3me5yang4", "pinyinAccent" : "zěnmeyàng", "definition" : "how about?; how is/was it?" },
{ "simplified" : "对不起", "traditional" : "對不起", "pinyin" : "dui4bu5qi3", "pinyinAccent" : "duìbuqǐ", "definition" : "sorry" },
{ "simplified" : "住", "traditional" : "住", "pinyin" : "zhu4", "pinyinAccent" : "zhù", "definition" : "to live; reside; to stop" },
{ "simplified" : "三", "traditional" : "三", "pinyin" : "san1", "pinyinAccent" : "sān", "definition" : "three" },
{ "simplified" : "高兴", "traditional" : "高興", "pinyin" : "gao1xing4", "pinyinAccent" : "gāoxìng", "definition" : "happy; glad" },
{ "simplified" : "买", "traditional" : "買", "pinyin" : "mai3", "pinyinAccent" : "mǎi", "definition" : "to buy" },
{ "simplified" : "医生", "traditional" : "醫生", "pinyin" : "yi1sheng1", "pinyinAccent" : "yīshēng", "definition" : "doctor" },
{ "simplified" : "哪儿", "traditional" : "哪兒", "pinyin" : "na3r5", "pinyinAccent" : "nǎr", "definition" : "where? (Beijing accent)" },
{ "simplified" : "字", "traditional" : "字", "pinyin" : "zi4", "pinyinAccent" : "zì", "definition" : "letter; character" },
{ "simplified" : "名字", "traditional" : "名字", "pinyin" : "ming2zi5", "pinyinAccent" : "míngzi", "definition" : "name" },
{ "simplified" : "认识", "traditional" : "認識", "pinyin" : "ren4shi5", "pinyinAccent" : "rènshi", "definition" : "recognize; know (a person)" },
{ "simplified" : "坐", "traditional" : "坐", "pinyin" : "zuo4", "pinyinAccent" : "zuò", "definition" : "sit" },
{ "simplified" : "喝", "traditional" : "喝", "pinyin" : "he1", "pinyinAccent" : "hē", "definition" : "to drink" },
{ "simplified" : "写", "traditional" : "寫", "pinyin" : "xie3", "pinyinAccent" : "xiě", "definition" : "to write; to compose" },
{ "simplified" : "月", "traditional" : "月", "pinyin" : "yue4", "pinyinAccent" : "yuè", "definition" : "moon; month; flesh (radical)" },
{ "simplified" : "号", "traditional" : "號", "pinyin" : "hao4", "pinyinAccent" : "hào", "definition" : "number; day of a month" },
{ "simplified" : "狗", "traditional" : "狗", "pinyin" : "gou3", "pinyinAccent" : "gǒu", "definition" : "dog" },
{ "simplified" : "岁", "traditional" : "歲", "pinyin" : "sui4", "pinyinAccent" : "suì", "definition" : "years old; age" },
{ "simplified" : "看见", "traditional" : "看見", "pinyin" : "kan4jian4", "pinyinAccent" : "kànjiàn", "definition" : "see; catch sight of" },
{ "simplified" : "打电话", "traditional" : "打電話", "pinyin" : "da3 dian4hua4", "pinyinAccent" : "dǎ diànhuà", "definition" : "make a phone call" },
{ "simplified" : "喂", "traditional" : "喂", "pinyin" : "wei4", "pinyinAccent" : "wèi", "definition" : "hello (on the phone)" },
{ "simplified" : "儿子", "traditional" : "兒子", "pinyin" : "er2zi5", "pinyinAccent" : "érzi", "definition" : "son" },
{ "simplified" : "漂亮", "traditional" : "漂亮", "pinyin" : "piao4liang5", "pinyinAccent" : "piàoliang", "definition" : "pretty; beautiful" },
{ "simplified" : "分钟", "traditional" : "分鐘", "pinyin" : "fen1zhong1", "pinyinAccent" : "fēnzhōng", "definition" : "minute; (measure word for time)" },
{ "simplified" : "再见", "traditional" : "再見", "pinyin" : "zai4jian4", "pinyinAccent" : "zàijiàn", "definition" : "goodbye; see you later" },
{ "simplified" : "本", "traditional" : "本", "pinyin" : "ben3", "pinyinAccent" : "běn", "definition" : "measure word for books" },
{ "simplified" : "明天", "traditional" : "明天", "pinyin" : "ming2tian1", "pinyinAccent" : "míngtiān", "definition" : "tomorrow" },
{ "simplified" : "少", "traditional" : "少", "pinyin" : "shao3", "pinyinAccent" : "shǎo", "definition" : "few; little" },
{ "simplified" : "多少", "traditional" : "多少", "pinyin" : "duo1shao5", "pinyinAccent" : "duōshao", "definition" : "how much?; how many?" },
{ "simplified" : "块", "traditional" : "塊", "pinyin" : "kuai4", "pinyinAccent" : "kuài", "definition" : "lump; piece; sum of money" },
{ "simplified" : "女儿", "traditional" : "女兒", "pinyin" : "nv3'er2", "pinyinAccent" : "nǚ'ér", "definition" : "daughter" },
{ "simplified" : "小姐", "traditional" : "小姐", "pinyin" : "xiao3jie5", "pinyinAccent" : "xiǎojie", "definition" : "young lady; miss; Ms." },
{ "simplified" : "衣服", "traditional" : "衣服", "pinyin" : "yi1fu5", "pinyinAccent" : "yīfu", "definition" : "clothes" },
{ "simplified" : "水", "traditional" : "水", "pinyin" : "shui3", "pinyinAccent" : "shuǐ", "definition" : "water" },
{ "simplified" : "学校", "traditional" : "學校", "pinyin" : "xue2xiao4", "pinyinAccent" : "xuéxiào", "definition" : "school" },
{ "simplified" : "电影", "traditional" : "電影", "pinyin" : "dian4ying3", "pinyinAccent" : "diànyǐng", "definition" : "movie; film" },
{ "simplified" : "书", "traditional" : "書", "pinyin" : "shu1", "pinyinAccent" : "shū", "definition" : "book; letter" },
{ "simplified" : "四", "traditional" : "四", "pinyin" : "si4", "pinyinAccent" : "sì", "definition" : "four" },
{ "simplified" : "五", "traditional" : "五", "pinyin" : "wu3", "pinyinAccent" : "wǔ", "definition" : "five" },
{ "simplified" : "医院", "traditional" : "醫院", "pinyin" : "yi1yuan4", "pinyinAccent" : "yīyuàn", "definition" : "hospital" },
{ "simplified" : "没关系", "traditional" : "沒關系", "pinyin" : "mei2 guan1xi5", "pinyinAccent" : "méi guānxi", "definition" : "it doesn't matter; never mind" },
{ "simplified" : "飞机", "traditional" : "飛機", "pinyin" : "fei1ji1", "pinyinAccent" : "fēijī", "definition" : "airplane" },
{ "simplified" : "二", "traditional" : "二", "pinyin" : "er4", "pinyinAccent" : "èr", "definition" : "two" },
{ "simplified" : "电视", "traditional" : "電視", "pinyin" : "dian4shi4", "pinyinAccent" : "diànshì", "definition" : "television; TV" },
{ "simplified" : "读", "traditional" : "讀", "pinyin" : "du2", "pinyinAccent" : "dú", "definition" : "to read; to study" },
{ "simplified" : "后面", "traditional" : "后面", "pinyin" : "hou4mian5", "pinyinAccent" : "hòumian", "definition" : "back; behind" },
{ "simplified" : "昨天", "traditional" : "昨天", "pinyin" : "zuo2tian1", "pinyinAccent" : "zuótiān", "definition" : "yesterday" },
{ "simplified" : "睡觉", "traditional" : "睡覺", "pinyin" : "shui4 jiao4", "pinyinAccent" : "shuì jiào", "definition" : "to sleep; go to bed" },
{ "simplified" : "六", "traditional" : "六", "pinyin" : "liu4", "pinyinAccent" : "liù", "definition" : "six" },
{ "simplified" : "老师", "traditional" : "老師", "pinyin" : "lao3shi1", "pinyinAccent" : "lǎoshī", "definition" : "teacher" },
{ "simplified" : "星期", "traditional" : "星期", "pinyin" : "xing1qi1", "pinyinAccent" : "xīngqī", "definition" : "week" },
{ "simplified" : "十", "traditional" : "十", "pinyin" : "shi2", "pinyinAccent" : "shí", "definition" : "ten" },
{ "simplified" : "猫", "traditional" : "貓", "pinyin" : "mao1", "pinyinAccent" : "māo", "definition" : "cat" },
{ "simplified" : "电脑", "traditional" : "電腦", "pinyin" : "dian4nao3", "pinyinAccent" : "diànnǎo", "definition" : "computer" },
{ "simplified" : "热", "traditional" : "熱", "pinyin" : "re4", "pinyinAccent" : "rè", "definition" : "heat; hot" },
{ "simplified" : "学生", "traditional" : "學生", "pinyin" : "xue2sheng5", "pinyinAccent" : "xuésheng", "definition" : "student" },
{ "simplified" : "下午", "traditional" : "下午", "pinyin" : "xia4wu3", "pinyinAccent" : "xiàwǔ", "definition" : "afternoon" },
{ "simplified" : "学习", "traditional" : "學習", "pinyin" : "xue2xi2", "pinyinAccent" : "xuéxí", "definition" : "learn; to study" },
{ "simplified" : "冷", "traditional" : "冷", "pinyin" : "leng3", "pinyinAccent" : "lěng", "definition" : "cold" },
{ "simplified" : "不客气", "traditional" : "不客氣", "pinyin" : "bu2 ke4qi5", "pinyinAccent" : "bú kèqi", "definition" : "you're welcome; don't be polite" },
{ "simplified" : "前面", "traditional" : "前面", "pinyin" : "qian2mian4", "pinyinAccent" : "qiánmiàn", "definition" : "in front" },
{ "simplified" : "八", "traditional" : "八", "pinyin" : "ba1", "pinyinAccent" : "bā", "definition" : "eight" },
{ "simplified" : "中国", "traditional" : "中國", "pinyin" : "Zhong1guo2", "pinyinAccent" : "Zhōngguó", "definition" : "China" },
{ "simplified" : "七", "traditional" : "七", "pinyin" : "qi1", "pinyinAccent" : "qī", "definition" : "seven" },
{ "simplified" : "菜", "traditional" : "菜", "pinyin" : "cai4", "pinyinAccent" : "cài", "definition" : "dish (type of food); vegetables" },
{ "simplified" : "桌子", "traditional" : "桌子", "pinyin" : "zhuo1zi5", "pinyinAccent" : "zhuōzi", "definition" : "table; desk" },
{ "simplified" : "出租车", "traditional" : "出租車", "pinyin" : "chu1zu1che1", "pinyinAccent" : "chūzūchē", "definition" : "taxi; cab" },
{ "simplified" : "天气", "traditional" : "天氣", "pinyin" : "tian1qi4", "pinyinAccent" : "tiānqì", "definition" : "weather" },
{ "simplified" : "茶", "traditional" : "茶", "pinyin" : "cha2", "pinyinAccent" : "chá", "definition" : "tea" },
{ "simplified" : "九", "traditional" : "九", "pinyin" : "jiu3", "pinyinAccent" : "jiǔ", "definition" : "nine" },
{ "simplified" : "商店", "traditional" : "商店", "pinyin" : "shang1dian4", "pinyinAccent" : "shāngdiàn", "definition" : "shop; store" },
{ "simplified" : "椅子", "traditional" : "椅子", "pinyin" : "yi3zi5", "pinyinAccent" : "yǐzi", "definition" : "chair" },
{ "simplified" : "同学", "traditional" : "同學", "pinyin" : "tong2xue2", "pinyinAccent" : "tóngxué", "definition" : "fellow student; schoolmate" },
{ "simplified" : "一点儿", "traditional" : "一點兒", "pinyin" : "yi4dian3r5", "pinyinAccent" : "yìdiǎnr", "definition" : "a bit; a few" },
{ "simplified" : "苹果", "traditional" : "蘋果", "pinyin" : "ping2guo3", "pinyinAccent" : "píngguǒ", "definition" : "apple" },
{ "simplified" : "饭店", "traditional" : "飯店", "pinyin" : "fan4dian4", "pinyinAccent" : "fàndiàn", "definition" : "restaurant; hotel" },
{ "simplified" : "中午", "traditional" : "中午", "pinyin" : "zhong1wu3", "pinyinAccent" : "zhōngwǔ", "definition" : "noon; midday" },
{ "simplified" : "上午", "traditional" : "上午", "pinyin" : "shang4wu3", "pinyinAccent" : "shàngwǔ", "definition" : "late morning (before noon)" },
{ "simplified" : "水果", "traditional" : "水果", "pinyin" : "shui3guo3", "pinyinAccent" : "shuǐguǒ", "definition" : "fruit" },
{ "simplified" : "杯子", "traditional" : "杯子", "pinyin" : "bei1zi5", "pinyinAccent" : "bēizi", "definition" : "cup; glass" },
{ "simplified" : "下雨", "traditional" : "下雨", "pinyin" : "xia4yu3", "pinyinAccent" : "xiàyǔ", "definition" : "to rain" },
{ "simplified" : "米饭", "traditional" : "米飯", "pinyin" : "mi3fan4", "pinyinAccent" : "mǐfàn", "definition" : "(cooked) rice" },
{ "simplified" : "北京", "traditional" : "北京", "pinyin" : "Bei3jing1", "pinyinAccent" : "Běijīng", "definition" : "Beijing" },
{ "simplified" : "汉语", "traditional" : "漢語", "pinyin" : "Han4yu3", "pinyinAccent" : "Hànyǔ", "definition" : "Chinese language" }
]
