export const hsk2 = [
{ "simplified" : "就", "traditional" : "就", "pinyin" : "jiu4", "pinyinAccent" : "jiù", "definition" : "then; at once; just; only; with regard to" },
{ "simplified" : "要", "traditional" : "要", "pinyin" : "yao4, yao1", "pinyinAccent" : "yào, yāo", "definition" : "to want; to need; will/shall; important | demand; request" },
{ "simplified" : "知道", "traditional" : "知道", "pinyin" : "zhi1dao5", "pinyinAccent" : "zhīdao", "definition" : "know; be aware of" },
{ "simplified" : "吧", "traditional" : "吧", "pinyin" : "ba5, ba1", "pinyinAccent" : "ba, bā", "definition" : "particle indicating polite suggestion; | onomatopoeia | bar (serving drinks, providing internet access, etc.)" },
{ "simplified" : "到", "traditional" : "到", "pinyin" : "dao4", "pinyinAccent" : "dào", "definition" : "arrive (at a place); until (a time)" },
{ "simplified" : "对", "traditional" : "對", "pinyin" : "dui4", "pinyinAccent" : "duì", "definition" : "correct; a pair; to face; be opposite; to; towards" },
{ "simplified" : "也", "traditional" : "也", "pinyin" : "ye3", "pinyinAccent" : "yě", "definition" : "also; too" },
{ "simplified" : "还", "traditional" : "還", "pinyin" : "hai2, huan2", "pinyinAccent" : "hái, huán", "definition" : "still; yet; in addition; even | repay; to return" },
{ "simplified" : "让", "traditional" : "讓", "pinyin" : "rang4", "pinyinAccent" : "ràng", "definition" : "ask; let; yield" },
{ "simplified" : "给", "traditional" : "給", "pinyin" : "gei3, ji3", "pinyinAccent" : "gěi, jǐ", "definition" : "to give; to grant; (passive particle) | provide" },
{ "simplified" : "过", "traditional" : "過", "pinyin" : "guo4", "pinyinAccent" : "guò", "definition" : "to pass; to cross; go over; (indicates a past experience)" },
{ "simplified" : "得", "traditional" : "得", "pinyin" : "de2, dei3, de5", "pinyinAccent" : "dé, děi, de", "definition" : "obtain | must | (complement particle)" },
{ "simplified" : "真", "traditional" : "真", "pinyin" : "zhen1", "pinyinAccent" : "zhēn", "definition" : "real; true; genuine" },
{ "simplified" : "着", "traditional" : "著", "pinyin" : "zhe5, zhao2, zhuo2", "pinyinAccent" : "zhe, zháo, zhuó", "definition" : "-ing (indicating action in progress) | to touch; to feel | to wear; apply" },
{ "simplified" : "可以", "traditional" : "可以", "pinyin" : "ke3yi3", "pinyinAccent" : "kěyǐ", "definition" : "can; may; possible; okay" },
{ "simplified" : "别", "traditional" : "別", "pinyin" : "bie2, bie4", "pinyinAccent" : "bié, biè", "definition" : "don't do something; don't | depart; | other; difference; distinguish" },
{ "simplified" : "走", "traditional" : "走", "pinyin" : "zou3", "pinyinAccent" : "zǒu", "definition" : "to walk; to go; to move (Kangxi radical 156)" },
{ "simplified" : "告诉", "traditional" : "告訴", "pinyin" : "gao4su5", "pinyinAccent" : "gàosu", "definition" : "to tell; inform" },
{ "simplified" : "因为", "traditional" : "因為", "pinyin" : "yin1wei4", "pinyinAccent" : "yīnwèi", "definition" : "because" },
{ "simplified" : "再", "traditional" : "再", "pinyin" : "zai4", "pinyinAccent" : "zài", "definition" : "again; once more" },
{ "simplified" : "快", "traditional" : "快", "pinyin" : "kuai4", "pinyinAccent" : "kuài", "definition" : "fast; quick; swift" },
{ "simplified" : "但是", "traditional" : "但是", "pinyin" : "dan4shi4", "pinyinAccent" : "dànshì", "definition" : "but; however" },
{ "simplified" : "已经", "traditional" : "已經", "pinyin" : "yi3jing5", "pinyinAccent" : "yǐjing", "definition" : "already" },
{ "simplified" : "为什么", "traditional" : "為什麼", "pinyin" : "wei4shen2me5", "pinyinAccent" : "wèishénme", "definition" : "why?; for what reason?" },
{ "simplified" : "觉得", "traditional" : "覺得", "pinyin" : "jue2de5", "pinyinAccent" : "juéde", "definition" : "feel; think" },
{ "simplified" : "它", "traditional" : "它", "pinyin" : "ta1", "pinyinAccent" : "tā", "definition" : "it" },
{ "simplified" : "从", "traditional" : "從", "pinyin" : "cong2", "pinyinAccent" : "cóng", "definition" : "from; obey; observe" },
{ "simplified" : "找", "traditional" : "找", "pinyin" : "zhao3", "pinyinAccent" : "zhǎo", "definition" : "try to find; look for; seek; to give change" },
{ "simplified" : "最", "traditional" : "最", "pinyin" : "zui4", "pinyinAccent" : "zuì", "definition" : "the most; -est; (indicator for superlative)" },
{ "simplified" : "可能", "traditional" : "可能", "pinyin" : "ke3neng2", "pinyinAccent" : "kěnéng", "definition" : "possible; maybe" },
{ "simplified" : "次", "traditional" : "次", "pinyin" : "ci4", "pinyinAccent" : "cì", "definition" : "(mw for number of times of occurrence); nth; order" },
{ "simplified" : "出", "traditional" : "出", "pinyin" : "chu1", "pinyinAccent" : "chū", "definition" : "go out; occur" },
{ "simplified" : "孩子", "traditional" : "孩子", "pinyin" : "hai2zi5", "pinyinAccent" : "háizi", "definition" : "child; children; son or daughter" },
{ "simplified" : "所以", "traditional" : "所以", "pinyin" : "suo3yi3", "pinyinAccent" : "suǒyǐ", "definition" : "so; therefore; as a result" },
{ "simplified" : "两", "traditional" : "兩", "pinyin" : "liang3", "pinyinAccent" : "liǎng", "definition" : "two; 2; both; (unit of weight equal to 50 grams)" },
{ "simplified" : "错", "traditional" : "錯", "pinyin" : "cuo4", "pinyinAccent" : "cuò", "definition" : "mistake; error; blunder; miss an opportunity" },
{ "simplified" : "等", "traditional" : "等", "pinyin" : "deng3", "pinyinAccent" : "děng", "definition" : "to wait; rank; equal; etc." },
{ "simplified" : "题", "traditional" : "題", "pinyin" : "ti2", "pinyinAccent" : "tí", "definition" : "topic; subject; question on a test or assignment" },
{ "simplified" : "问", "traditional" : "問", "pinyin" : "wen4", "pinyinAccent" : "wèn", "definition" : "ask; inquire" },
{ "simplified" : "问题", "traditional" : "問題", "pinyin" : "wen4ti2", "pinyinAccent" : "wèntí", "definition" : "question; problem" },
{ "simplified" : "一起", "traditional" : "一起", "pinyin" : "yi4qi3", "pinyinAccent" : "yìqǐ", "definition" : "together; in the same place" },
{ "simplified" : "开始", "traditional" : "開始", "pinyin" : "kai1shi3", "pinyinAccent" : "kāishǐ", "definition" : "begin; to start; beginning" },
{ "simplified" : "时间", "traditional" : "時間", "pinyin" : "shi2jian1", "pinyinAccent" : "shíjiān", "definition" : "time; period" },
{ "simplified" : "事情", "traditional" : "事情", "pinyin" : "shi4qing5", "pinyinAccent" : "shìqing", "definition" : "matter; affair; thing; business" },
{ "simplified" : "一下", "traditional" : "一下", "pinyin" : "yi2xia4", "pinyinAccent" : "yíxià", "definition" : "a little bit/while; one time; once" },
{ "simplified" : "非常", "traditional" : "非常", "pinyin" : "fei1chang2", "pinyinAccent" : "fēicháng", "definition" : "extremely; extraordinary; very" },
{ "simplified" : "希望", "traditional" : "希望", "pinyin" : "xi1wang4", "pinyinAccent" : "xīwàng", "definition" : "to hope; wish for; to desire" },
{ "simplified" : "准备", "traditional" : "准備", "pinyin" : "zhun3bei4", "pinyinAccent" : "zhǔnbèi", "definition" : "prepare; get ready" },
{ "simplified" : "比", "traditional" : "比", "pinyin" : "bi3", "pinyinAccent" : "bǐ", "definition" : "compare; (indicates comparison) (Kangxi radical 81); to gesticulate as one talks" },
{ "simplified" : "件", "traditional" : "件", "pinyin" : "jian4", "pinyinAccent" : "jiàn", "definition" : "(mw for things, clothes, and items)" },
{ "simplified" : "意思", "traditional" : "意思", "pinyin" : "yi4si5", "pinyinAccent" : "yìsi", "definition" : "meaning; idea; opinion" },
{ "simplified" : "第一", "traditional" : "第一", "pinyin" : "di4yi1", "pinyinAccent" : "dìyī", "definition" : "first; number 1" },
{ "simplified" : "进", "traditional" : "進", "pinyin" : "jin4", "pinyinAccent" : "jìn", "definition" : "enter; come in" },
{ "simplified" : "大家", "traditional" : "大家", "pinyin" : "da4jia1", "pinyinAccent" : "dàjiā", "definition" : "everyone" },
{ "simplified" : "新", "traditional" : "新", "pinyin" : "xin1", "pinyinAccent" : "xīn", "definition" : "new; Xinjiang autonomous region (abbreviation)" },
{ "simplified" : "您", "traditional" : "您", "pinyin" : "nin2", "pinyinAccent" : "nín", "definition" : "you (polite)" },
{ "simplified" : "穿", "traditional" : "穿", "pinyin" : "chuan1", "pinyinAccent" : "chuān", "definition" : "to wear; put on; penetrate" },
{ "simplified" : "送", "traditional" : "送", "pinyin" : "song4", "pinyinAccent" : "sòng", "definition" : "deliver; to carry; to give; send" },
{ "simplified" : "玩", "traditional" : "玩", "pinyin" : "wan2", "pinyinAccent" : "wán", "definition" : "to play; have a good time; visit; enjoy" },
{ "simplified" : "长", "traditional" : "長", "pinyin" : "chang2, zhang3", "pinyinAccent" : "cháng, zhǎng", "definition" : "long; length | grow; chief (Kangxi radical 168)" },
{ "simplified" : "小时", "traditional" : "小時", "pinyin" : "xiao3shi2", "pinyinAccent" : "xiǎoshí", "definition" : "hour" },
{ "simplified" : "完", "traditional" : "完", "pinyin" : "wan2", "pinyinAccent" : "wán", "definition" : "to finish; be over; complete" },
{ "simplified" : "每", "traditional" : "每", "pinyin" : "mei3", "pinyinAccent" : "měi", "definition" : "each; every" },
{ "simplified" : "公司", "traditional" : "公司", "pinyin" : "gong1si1", "pinyinAccent" : "gōngsī", "definition" : "company; corporation" },
{ "simplified" : "帮助", "traditional" : "幫助", "pinyin" : "bang1zhu4", "pinyinAccent" : "bāngzhù", "definition" : "help; assist; aid" },
{ "simplified" : "晚上", "traditional" : "晚上", "pinyin" : "wan3shang5", "pinyinAccent" : "wǎnshang", "definition" : "evening; night" },
{ "simplified" : "说话", "traditional" : "說話", "pinyin" : "shuo1hua4", "pinyinAccent" : "shuōhuà", "definition" : "to talk; speak" },
{ "simplified" : "门", "traditional" : "門", "pinyin" : "men2", "pinyinAccent" : "mén", "definition" : "door; opening; gate (Kangxi radical 169)" },
{ "simplified" : "女", "traditional" : "女", "pinyin" : "nv3", "pinyinAccent" : "nǚ", "definition" : "woman; female (Kangxi radical 38)" },
{ "simplified" : "忙", "traditional" : "忙", "pinyin" : "mang2", "pinyinAccent" : "máng", "definition" : "busy" },
{ "simplified" : "卖", "traditional" : "賣", "pinyin" : "mai4", "pinyinAccent" : "mài", "definition" : "to sell" },
{ "simplified" : "高", "traditional" : "高", "pinyin" : "gao1", "pinyinAccent" : "gāo", "definition" : "high; tall (Kangxi radical 189)" },
{ "simplified" : "房间", "traditional" : "房間", "pinyin" : "fang2jian1", "pinyinAccent" : "fángjiān", "definition" : "room" },
{ "simplified" : "路", "traditional" : "路", "pinyin" : "lu4", "pinyinAccent" : "lù", "definition" : "road; path; journey; route" },
{ "simplified" : "懂", "traditional" : "懂", "pinyin" : "dong3", "pinyinAccent" : "dǒng", "definition" : "understand; know" },
{ "simplified" : "正在", "traditional" : "正在", "pinyin" : "zheng4zai4", "pinyinAccent" : "zhèngzài", "definition" : "in the process of (doing something); currently" },
{ "simplified" : "笑", "traditional" : "笑", "pinyin" : "xiao4", "pinyinAccent" : "xiào", "definition" : "to laugh; to smile" },
{ "simplified" : "远", "traditional" : "遠", "pinyin" : "yuan3", "pinyinAccent" : "yuǎn", "definition" : "far; distant; remote" },
{ "simplified" : "妻子", "traditional" : "妻子", "pinyin" : "qi1zi5", "pinyinAccent" : "qīzi", "definition" : "wife" },
{ "simplified" : "丈夫", "traditional" : "丈夫", "pinyin" : "zhang4fu5", "pinyinAccent" : "zhàngfu", "definition" : "husband; man" },
{ "simplified" : "离", "traditional" : "離", "pinyin" : "li2", "pinyinAccent" : "lí", "definition" : "leave; depart; go away; apart from" },
{ "simplified" : "往", "traditional" : "往", "pinyin" : "wang3", "pinyinAccent" : "wǎng", "definition" : "to go (in a direction); towards; in the past" },
{ "simplified" : "男", "traditional" : "男", "pinyin" : "nan2", "pinyinAccent" : "nán", "definition" : "male" },
{ "simplified" : "眼睛", "traditional" : "眼睛", "pinyin" : "yan3jing5", "pinyinAccent" : "yǎnjing", "definition" : "eye" },
{ "simplified" : "快乐", "traditional" : "快樂", "pinyin" : "kuai4le4", "pinyinAccent" : "kuàilè", "definition" : "happy" },
{ "simplified" : "虽然", "traditional" : "雖然", "pinyin" : "sui1ran2", "pinyinAccent" : "suīrán", "definition" : "although; even though" },
{ "simplified" : "早上", "traditional" : "早上", "pinyin" : "zao3shang5", "pinyinAccent" : "zǎoshang", "definition" : "(early) morning" },
{ "simplified" : "药", "traditional" : "藥", "pinyin" : "yao4", "pinyinAccent" : "yào", "definition" : "medicine; drug; cure; chemical" },
{ "simplified" : "身体", "traditional" : "身體", "pinyin" : "shen1ti3", "pinyinAccent" : "shēntǐ", "definition" : "health; (human) body" },
{ "simplified" : "黑", "traditional" : "黑", "pinyin" : "hei1", "pinyinAccent" : "hēi", "definition" : "black; dark (Kangxi radical 203); Heilongjiang province (abbreviation)" },
{ "simplified" : "咖啡", "traditional" : "咖啡", "pinyin" : "ka1fei1", "pinyinAccent" : "kāfēi", "definition" : "coffee" },
{ "simplified" : "日", "traditional" : "日", "pinyin" : "ri4", "pinyinAccent" : "rì", "definition" : "sun; day; date; time (Kangxi radical 72)" },
{ "simplified" : "休息", "traditional" : "休息", "pinyin" : "xiu1xi5", "pinyinAccent" : "xiūxi", "definition" : "to rest; take a break" },
{ "simplified" : "外", "traditional" : "外", "pinyin" : "wai4", "pinyinAccent" : "wài", "definition" : "outer; outside; in addition; foreign" },
{ "simplified" : "生日", "traditional" : "生日", "pinyin" : "sheng1ri4", "pinyinAccent" : "shēngrì", "definition" : "birthday" },
{ "simplified" : "哥哥", "traditional" : "哥哥", "pinyin" : "ge1ge5", "pinyinAccent" : "gēge", "definition" : "older brother" },
{ "simplified" : "票", "traditional" : "票", "pinyin" : "piao4", "pinyinAccent" : "piào", "definition" : "ticket; bank note; a vote" },
{ "simplified" : "手机", "traditional" : "手機", "pinyin" : "shou3ji1", "pinyinAccent" : "shǒujī", "definition" : "mobile (cell) phone" },
{ "simplified" : "洗", "traditional" : "洗", "pinyin" : "xi3", "pinyinAccent" : "xǐ", "definition" : "to wash; bathe" },
{ "simplified" : "跳舞", "traditional" : "跳舞", "pinyin" : "tiao4 wu3", "pinyinAccent" : "tiào wǔ", "definition" : "to dance" },
{ "simplified" : "弟弟", "traditional" : "弟弟", "pinyin" : "di4di5", "pinyinAccent" : "dìdi", "definition" : "younger brother" },
{ "simplified" : "妹妹", "traditional" : "妹妹", "pinyin" : "mei4mei5", "pinyinAccent" : "mèimei", "definition" : "younger sister" },
{ "simplified" : "红", "traditional" : "紅", "pinyin" : "hong2", "pinyinAccent" : "hóng", "definition" : "red; symbol of success; bonus; popular" },
{ "simplified" : "慢", "traditional" : "慢", "pinyin" : "man4", "pinyinAccent" : "màn", "definition" : "slow" },
{ "simplified" : "近", "traditional" : "近", "pinyin" : "jin4", "pinyinAccent" : "jìn", "definition" : "near; close (to)" },
{ "simplified" : "白", "traditional" : "白", "pinyin" : "bai2, bo2", "pinyinAccent" : "bái, bó", "definition" : "white; snowy; pure; bright; empty (Kangxi radical 106)" },
{ "simplified" : "姐姐", "traditional" : "姐姐", "pinyin" : "jie3jie5", "pinyinAccent" : "jiějie", "definition" : "older sister" },
{ "simplified" : "介绍", "traditional" : "介紹", "pinyin" : "jie4shao4", "pinyinAccent" : "jièshào", "definition" : "to introduce; recommend; introduction" },
{ "simplified" : "鱼", "traditional" : "魚", "pinyin" : "yu2", "pinyinAccent" : "yú", "definition" : "fish (Kangxi radical 195)" },
{ "simplified" : "累", "traditional" : "累", "pinyin" : "lei4, lei3, lei2", "pinyinAccent" : "lèi, lěi, léi", "definition" : "tired | accumulate; implicate | rope; bind together" },
{ "simplified" : "课", "traditional" : "課", "pinyin" : "ke4", "pinyinAccent" : "kè", "definition" : "class; subject; lesson; course" },
{ "simplified" : "上班", "traditional" : "上班", "pinyin" : "shang4 ban1", "pinyinAccent" : "shàng bān", "definition" : "go to work; be on duty" },
{ "simplified" : "旁边", "traditional" : "旁邊", "pinyin" : "pang2bian1", "pinyinAccent" : "pángbiān", "definition" : "side, beside" },
{ "simplified" : "运动", "traditional" : "運動", "pinyin" : "yun4dong4", "pinyinAccent" : "yùndòng", "definition" : "(physical) exercise; movement; sports; campaign" },
{ "simplified" : "去年", "traditional" : "去年", "pinyin" : "qu4nian2", "pinyinAccent" : "qùnián", "definition" : "last year" },
{ "simplified" : "报纸", "traditional" : "報紙", "pinyin" : "bao4zhi3", "pinyinAccent" : "bàozhǐ", "definition" : "newspaper" },
{ "simplified" : "颜色", "traditional" : "顏色", "pinyin" : "yan2se4", "pinyinAccent" : "yánsè", "definition" : "color" },
{ "simplified" : "机场", "traditional" : "機場", "pinyin" : "ji1chang3", "pinyinAccent" : "jīchǎng", "definition" : "airport; airfield" },
{ "simplified" : "唱歌", "traditional" : "唱歌", "pinyin" : "chang4ge1", "pinyinAccent" : "chànggē", "definition" : "sing (a song)" },
{ "simplified" : "千", "traditional" : "千", "pinyin" : "qian1", "pinyinAccent" : "qiān", "definition" : "one thousand" },
{ "simplified" : "好吃", "traditional" : "好吃", "pinyin" : "hao3chi1", "pinyinAccent" : "hǎochī", "definition" : "tasty" },
{ "simplified" : "考试", "traditional" : "考試", "pinyin" : "kao3shi4", "pinyinAccent" : "kǎoshì", "definition" : "test; exam; to give or take a test" },
{ "simplified" : "左边", "traditional" : "左邊", "pinyin" : "zuo3bian5", "pinyinAccent" : "zuǒbian", "definition" : "the left side; the left" },
{ "simplified" : "姓", "traditional" : "姓", "pinyin" : "xing4", "pinyinAccent" : "xìng", "definition" : "surname; family name" },
{ "simplified" : "百", "traditional" : "百", "pinyin" : "bai3", "pinyinAccent" : "bǎi", "definition" : "hundred" },
{ "simplified" : "雪", "traditional" : "雪", "pinyin" : "xue3", "pinyinAccent" : "xuě", "definition" : "snow" },
{ "simplified" : "贵", "traditional" : "貴", "pinyin" : "gui4", "pinyinAccent" : "guì", "definition" : "expensive; noble; honorable; Guizhou province (abbreviation)" },
{ "simplified" : "生病", "traditional" : "生病", "pinyin" : "sheng1 bing4", "pinyinAccent" : "shēng bìng", "definition" : "get sick; fall ill" },
{ "simplified" : "游泳", "traditional" : "游泳", "pinyin" : "you2yong3", "pinyinAccent" : "yóuyǒng", "definition" : "to swim" },
{ "simplified" : "牛奶", "traditional" : "牛奶", "pinyin" : "niu2nai3", "pinyinAccent" : "niúnǎi", "definition" : "cow's milk" },
{ "simplified" : "右边", "traditional" : "右邊", "pinyin" : "you4bian5", "pinyinAccent" : "yòubian", "definition" : "the right (as opposed to left) side" },
{ "simplified" : "便宜", "traditional" : "便宜", "pinyin" : "pian2yi5", "pinyinAccent" : "piányi", "definition" : "cheap" },
{ "simplified" : "公共汽车", "traditional" : "公共汽車", "pinyin" : "gong1gong4 qi4che1", "pinyinAccent" : "gōnggòng qìchē", "definition" : "(public) bus" },
{ "simplified" : "起床", "traditional" : "起床", "pinyin" : "qi3 chuang2", "pinyinAccent" : "qǐ chuáng", "definition" : "get out of bed" },
{ "simplified" : "打篮球", "traditional" : "打籃球", "pinyin" : "da3 lan2qiu2", "pinyinAccent" : "dǎ lánqiú", "definition" : "play basketball" },
{ "simplified" : "鸡蛋", "traditional" : "雞蛋", "pinyin" : "ji1dan4", "pinyinAccent" : "jīdàn", "definition" : "(chicken) egg" },
{ "simplified" : "踢足球", "traditional" : "踢足球", "pinyin" : "ti1zu2qiu2", "pinyinAccent" : "tīzúqiú", "definition" : "to play football/soccer" },
{ "simplified" : "零", "traditional" : "零", "pinyin" : "ling2", "pinyinAccent" : "líng", "definition" : "zero; remnant" },
{ "simplified" : "手表", "traditional" : "手表", "pinyin" : "shou3biao3", "pinyinAccent" : "shǒubiǎo", "definition" : "wristwatch" },
{ "simplified" : "旅游", "traditional" : "旅游", "pinyin" : "lv3you2", "pinyinAccent" : "lǚyóu", "definition" : "trip; journey; tour" },
{ "simplified" : "服务员", "traditional" : "服務員", "pinyin" : "fu2wu4yuan2", "pinyinAccent" : "fúwùyuán", "definition" : "waiter/waitress; server; attendant" },
{ "simplified" : "宾馆", "traditional" : "賓館", "pinyin" : "bin1guan3", "pinyinAccent" : "bīnguǎn", "definition" : "guesthouse; hotel" },
{ "simplified" : "教室", "traditional" : "教室", "pinyin" : "jiao4shi4", "pinyinAccent" : "jiàoshì", "definition" : "classroom" },
{ "simplified" : "跑步", "traditional" : "跑步", "pinyin" : "pao3 bu4", "pinyinAccent" : "pǎo bù", "definition" : "to run; to jog" },
{ "simplified" : "阴", "traditional" : "陰", "pinyin" : "yin1", "pinyinAccent" : "yīn", "definition" : "cloudy (weather); yin (the negative principle of Yin and Yang); secret; the moon; negative; shade" },
{ "simplified" : "面条", "traditional" : "面條", "pinyin" : "mian4tiao2", "pinyinAccent" : "miàntiáo", "definition" : "noodles" },
{ "simplified" : "铅笔", "traditional" : "鉛筆", "pinyin" : "qian1bi3", "pinyinAccent" : "qiānbǐ", "definition" : "pencil" },
{ "simplified" : "火车站", "traditional" : "火車站", "pinyin" : "huo3che1zhan4", "pinyinAccent" : "huǒchēzhàn", "definition" : "train station" },
{ "simplified" : "西瓜", "traditional" : "西瓜", "pinyin" : "xi1gua1", "pinyinAccent" : "xīguā", "definition" : "watermelon" },
{ "simplified" : "羊肉", "traditional" : "羊肉", "pinyin" : "yang2rou4", "pinyinAccent" : "yángròu", "definition" : "mutton; lamb" },
{ "simplified" : "晴", "traditional" : "晴", "pinyin" : "qing2", "pinyinAccent" : "qíng", "definition" : "clear; fine (as of weather)" }
]
