export const hsk3 = [
{ "simplified" : "啊", "traditional" : "啊", "pinyin" : "a1, a2, a3, a4, a5", "pinyinAccent" : "ā, á, ǎ, à, a", "definition" : "ah; (particle showing elation, doubt, puzzled surprise, or approval)" },
{ "simplified" : "还", "traditional" : "還", "pinyin" : "hai2, huan2", "pinyinAccent" : "hái, huán", "definition" : "still; yet; in addition; even | repay; to return" },
{ "simplified" : "把", "traditional" : "把", "pinyin" : "ba3, ba4", "pinyinAccent" : "bǎ, bà", "definition" : "(mw for things with handles); (pretransitive particle); to hold | a grip; a handle; stem (of plants)" },
{ "simplified" : "过", "traditional" : "過", "pinyin" : "guo4", "pinyinAccent" : "guò", "definition" : "to pass; to cross; go over; (indicates a past experience)" },
{ "simplified" : "如果", "traditional" : "如果", "pinyin" : "ru2guo3", "pinyinAccent" : "rúguǒ", "definition" : "if; in the event that" },
{ "simplified" : "只", "traditional" : "隻", "pinyin" : "zhi3, zhi1", "pinyinAccent" : "zhǐ, zhī", "definition" : "only; merely; just; but | (mw for birds and certain animals)" },
{ "simplified" : "被", "traditional" : "被", "pinyin" : "bei4", "pinyinAccent" : "bèi", "definition" : "by (indicates passive voice sentences); a quilt/blanket" },
{ "simplified" : "跟", "traditional" : "跟", "pinyin" : "gen1", "pinyinAccent" : "gēn", "definition" : "to follow; go with; heel" },
{ "simplified" : "自己", "traditional" : "自己", "pinyin" : "zi4ji3", "pinyinAccent" : "zìjǐ", "definition" : "oneself; self" },
{ "simplified" : "用", "traditional" : "用", "pinyin" : "yong4", "pinyinAccent" : "yòng", "definition" : "to use (Kangxi radical 101)" },
{ "simplified" : "像", "traditional" : "像", "pinyin" : "xiang4", "pinyinAccent" : "xiàng", "definition" : "be like; resemble; appearance; appear" },
{ "simplified" : "为", "traditional" : "為", "pinyin" : "wei2, wei4", "pinyinAccent" : "wéi, wèi", "definition" : "to act (as); become; to mean | for; because of; to; for the sake of" },
{ "simplified" : "需要", "traditional" : "需要", "pinyin" : "xu1yao4", "pinyinAccent" : "xūyào", "definition" : "to need; to want; to demand" },
{ "simplified" : "应该", "traditional" : "應該", "pinyin" : "ying1gai1", "pinyinAccent" : "yīnggāi", "definition" : "should; ought to; must" },
{ "simplified" : "起来", "traditional" : "起來", "pinyin" : "qi3 lai5", "pinyinAccent" : "qǐ lai", "definition" : "(beginning or continuing an action); to rise; get up (from bed)" },
{ "simplified" : "才", "traditional" : "才", "pinyin" : "cai2", "pinyinAccent" : "cái", "definition" : "ability; talent; just now; not until" },
{ "simplified" : "又", "traditional" : "又", "pinyin" : "you4", "pinyinAccent" : "yòu", "definition" : "(once) again; also; both (Kangxi radical 29)" },
{ "simplified" : "拿", "traditional" : "拿", "pinyin" : "na2", "pinyinAccent" : "ná", "definition" : "carry in your hand; seize; to catch" },
{ "simplified" : "更", "traditional" : "更", "pinyin" : "geng4, geng1", "pinyinAccent" : "gèng, gēng", "definition" : "more; even more | change; watch (e.g. of a sentry or guard)" },
{ "simplified" : "带", "traditional" : "帶", "pinyin" : "dai4", "pinyinAccent" : "dài", "definition" : "band; belt; ribbon; carry; bring; take along; bring up (kids)" },
{ "simplified" : "然后", "traditional" : "然后", "pinyin" : "ran2hou4", "pinyinAccent" : "ránhòu", "definition" : "then; afterwards" },
{ "simplified" : "一样", "traditional" : "一樣", "pinyin" : "yi2yang4", "pinyinAccent" : "yíyàng", "definition" : "the same; alike; equal to" },
{ "simplified" : "当然", "traditional" : "當然", "pinyin" : "dang1ran2", "pinyinAccent" : "dāngrán", "definition" : "of course; naturally" },
{ "simplified" : "相信", "traditional" : "相信", "pinyin" : "xiang1xin4", "pinyinAccent" : "xiāngxìn", "definition" : "believe (sb.); be convinced of" },
{ "simplified" : "认为", "traditional" : "認為", "pinyin" : "ren4wei2", "pinyinAccent" : "rènwéi", "definition" : "believe; think that" },
{ "simplified" : "明白", "traditional" : "明白", "pinyin" : "ming2bai5", "pinyinAccent" : "míngbai", "definition" : "clear; obvious; understand; explicit" },
{ "simplified" : "一直", "traditional" : "一直", "pinyin" : "yi4zhi2", "pinyinAccent" : "yìzhí", "definition" : "always; all along; straight (in a straight line)" },
{ "simplified" : "地", "traditional" : "地", "pinyin" : "di4, de5", "pinyinAccent" : "dì, de", "definition" : "earth; ground | (adverbial particle)" },
{ "simplified" : "地方", "traditional" : "地方", "pinyin" : "di4fang5", "pinyinAccent" : "dìfang", "definition" : "place; space; room; part, (fāng: local; regional)" },
{ "simplified" : "离开", "traditional" : "離開", "pinyin" : "li2kai1", "pinyinAccent" : "líkāi", "definition" : "leave; depart" },
{ "simplified" : "一定", "traditional" : "一定", "pinyin" : "yi2ding4", "pinyinAccent" : "yídìng", "definition" : "surely; certainly; necessarily; definite" },
{ "simplified" : "还是", "traditional" : "還是", "pinyin" : "hai2shi5", "pinyinAccent" : "háishi", "definition" : "or; still; nevertheless; had better" },
{ "simplified" : "发", "traditional" : "發", "pinyin" : "fa1, fa4", "pinyinAccent" : "fā, fà", "definition" : "send out; to issue; to show (one's feelings) | hair" },
{ "simplified" : "发现", "traditional" : "發現", "pinyin" : "fa1xian4", "pinyinAccent" : "fāxiàn", "definition" : "discover; to find" },
{ "simplified" : "而且", "traditional" : "而且", "pinyin" : "er2qie3", "pinyinAccent" : "érqiě", "definition" : "moreover; in addition; as well as" },
{ "simplified" : "必须", "traditional" : "必須", "pinyin" : "bi4xu1", "pinyinAccent" : "bìxū", "definition" : "must; have to" },
{ "simplified" : "放", "traditional" : "放", "pinyin" : "fang4", "pinyinAccent" : "fàng", "definition" : "put; to place; to release; to free" },
{ "simplified" : "为了", "traditional" : "為了", "pinyin" : "wei4le5", "pinyinAccent" : "wèile", "definition" : "in order to; for the sake of; for the purpose of" },
{ "simplified" : "向", "traditional" : "向", "pinyin" : "xiang4", "pinyinAccent" : "xiàng", "definition" : "direction; towards; to turn; to face" },
{ "simplified" : "老", "traditional" : "老", "pinyin" : "lao3", "pinyinAccent" : "lǎo", "definition" : "old; aged; tough; often (Kangxi radical 125)" },
{ "simplified" : "位", "traditional" : "位", "pinyin" : "wei4", "pinyinAccent" : "wèi", "definition" : "position; location; (polite mw for people)" },
{ "simplified" : "先", "traditional" : "先", "pinyin" : "xian1", "pinyinAccent" : "xiān", "definition" : "first; early; before" },
{ "simplified" : "种", "traditional" : "種", "pinyin" : "zhong3, zhong4", "pinyinAccent" : "zhǒng, zhòng", "definition" : "type; breed; race; seed | to plant" },
{ "simplified" : "最后", "traditional" : "最后", "pinyin" : "zui4hou4", "pinyinAccent" : "zuìhòu", "definition" : "last; final; ultimately" },
{ "simplified" : "其他", "traditional" : "其他", "pinyin" : "qi2ta1", "pinyinAccent" : "qítā", "definition" : "other; else" },
{ "simplified" : "记得", "traditional" : "記得", "pinyin" : "ji4de5", "pinyinAccent" : "jìde", "definition" : "remember" },
{ "simplified" : "或者", "traditional" : "或者", "pinyin" : "huo4zhe3", "pinyinAccent" : "huòzhě", "definition" : "or; possible; maybe; perhaps" },
{ "simplified" : "过去", "traditional" : "過去", "pinyin" : "guo4qu4", "pinyinAccent" : "guòqù", "definition" : "in the past; formerly" },
{ "simplified" : "担心", "traditional" : "擔心", "pinyin" : "dan1xin1", "pinyinAccent" : "dānxīn", "definition" : "to worry; feel anxious" },
{ "simplified" : "条", "traditional" : "條", "pinyin" : "tiao2", "pinyinAccent" : "tiáo", "definition" : "strip; (mw for long thin objects); item" },
{ "simplified" : "以前", "traditional" : "以前", "pinyin" : "yi3qian2", "pinyinAccent" : "yǐqián", "definition" : "before; formerly; previous" },
{ "simplified" : "长", "traditional" : "長", "pinyin" : "chang2, zhang3", "pinyinAccent" : "cháng, zhǎng", "definition" : "long; length | grow; chief (Kangxi radical 168)" },
{ "simplified" : "世界", "traditional" : "世界", "pinyin" : "shi4jie4", "pinyinAccent" : "shìjiè", "definition" : "world" },
{ "simplified" : "重要", "traditional" : "重要", "pinyin" : "zhong4yao4", "pinyinAccent" : "zhòngyào", "definition" : "important; significant; major" },
{ "simplified" : "别人", "traditional" : "別人", "pinyin" : "bie2ren5", "pinyinAccent" : "biéren", "definition" : "other people; others" },
{ "simplified" : "机会", "traditional" : "機會", "pinyin" : "ji1hui4", "pinyinAccent" : "jīhuì", "definition" : "opportunity; chance; occasion" },
{ "simplified" : "张", "traditional" : "張", "pinyin" : "zhang1", "pinyinAccent" : "zhāng", "definition" : "(mw for flat objects); to spread out; (common surname)" },
{ "simplified" : "接", "traditional" : "接", "pinyin" : "jie1", "pinyinAccent" : "jiē", "definition" : "connect; to meet; to pick up (somebody); to receive" },
{ "simplified" : "比赛", "traditional" : "比賽", "pinyin" : "bi3sai4", "pinyinAccent" : "bǐsài", "definition" : "(sports) match; competition" },
{ "simplified" : "关", "traditional" : "關", "pinyin" : "guan1", "pinyinAccent" : "guān", "definition" : "to close; shut; concern; relationship; turn off; mountain pass" },
{ "simplified" : "关系", "traditional" : "關系", "pinyin" : "guan1xi5", "pinyinAccent" : "guānxi", "definition" : "relation; to concern" },
{ "simplified" : "马", "traditional" : "馬", "pinyin" : "ma3", "pinyinAccent" : "mǎ", "definition" : "horse (Kangxi radical 187)" },
{ "simplified" : "马上", "traditional" : "馬上", "pinyin" : "ma3shang4", "pinyinAccent" : "mǎshàng", "definition" : "at once; immediately; right away" },
{ "simplified" : "决定", "traditional" : "決定", "pinyin" : "jue2ding4", "pinyinAccent" : "juédìng", "definition" : "decide; resolve" },
{ "simplified" : "关于", "traditional" : "關於", "pinyin" : "guan1yu2", "pinyinAccent" : "guānyú", "definition" : "about; regarding; concerning" },
{ "simplified" : "难", "traditional" : "難", "pinyin" : "nan2, nan4", "pinyinAccent" : "nán, nàn", "definition" : "difficult | trouble; to blame" },
{ "simplified" : "了解", "traditional" : "了解", "pinyin" : "liao3jie3", "pinyinAccent" : "liǎojiě", "definition" : "comprehend; understand; know; find out" },
{ "simplified" : "站", "traditional" : "站", "pinyin" : "zhan4", "pinyinAccent" : "zhàn", "definition" : "stand; a station; be on one's feet; service center" },
{ "simplified" : "结束", "traditional" : "結束", "pinyin" : "jie2shu4", "pinyinAccent" : "jiéshù", "definition" : "to end; to finish; conclude" },
{ "simplified" : "清楚", "traditional" : "清楚", "pinyin" : "qing1chu5", "pinyinAccent" : "qīngchu", "definition" : "clear; distinct; be clear about" },
{ "simplified" : "愿意", "traditional" : "願意", "pinyin" : "yuan4yi4", "pinyinAccent" : "yuànyì", "definition" : "be willing; want to; be ready" },
{ "simplified" : "花", "traditional" : "花", "pinyin" : "hua1", "pinyinAccent" : "huā", "definition" : "flower; blossom; spend money; cost" },
{ "simplified" : "照片", "traditional" : "照片", "pinyin" : "zhao4pian4", "pinyinAccent" : "zhàopiàn", "definition" : "picture; photograph" },
{ "simplified" : "欢迎", "traditional" : "歡迎", "pinyin" : "huan1ying2", "pinyinAccent" : "huānyíng", "definition" : "to welcome; greet" },
{ "simplified" : "总是", "traditional" : "總是", "pinyin" : "zong3shi4", "pinyinAccent" : "zǒngshì", "definition" : "always; eventually" },
{ "simplified" : "嘴", "traditional" : "嘴", "pinyin" : "zui3", "pinyinAccent" : "zuǐ", "definition" : "mouth" },
{ "simplified" : "参加", "traditional" : "參加", "pinyin" : "can1jia1", "pinyinAccent" : "cānjiā", "definition" : "participate; join; take part in" },
{ "simplified" : "办法", "traditional" : "辦法", "pinyin" : "ban4fa3", "pinyinAccent" : "bànfǎ", "definition" : "method; way (of doing something)" },
{ "simplified" : "选择", "traditional" : "選擇", "pinyin" : "xuan3ze2", "pinyinAccent" : "xuǎnzé", "definition" : "select; to pick; choose" },
{ "simplified" : "坏", "traditional" : "壞", "pinyin" : "huai4", "pinyinAccent" : "huài", "definition" : "bad; broken" },
{ "simplified" : "打算", "traditional" : "打算", "pinyin" : "da3suan4", "pinyinAccent" : "dǎsuàn", "definition" : "to plan; intend" },
{ "simplified" : "试", "traditional" : "試", "pinyin" : "shi4", "pinyinAccent" : "shì", "definition" : "to try; to test; examination" },
{ "simplified" : "特别", "traditional" : "特別", "pinyin" : "te4bie2", "pinyinAccent" : "tèbié", "definition" : "special; especially; particular" },
{ "simplified" : "注意", "traditional" : "注意", "pinyin" : "zhu4yi4", "pinyinAccent" : "zhùyì", "definition" : "pay attention to; take notice of; be careful" },
{ "simplified" : "其实", "traditional" : "其實", "pinyin" : "qi2shi2", "pinyinAccent" : "qíshí", "definition" : "actually; in fact" },
{ "simplified" : "小心", "traditional" : "小心", "pinyin" : "xiao3xin1", "pinyinAccent" : "xiǎoxīn", "definition" : "be careful" },
{ "simplified" : "久", "traditional" : "久", "pinyin" : "jiu3", "pinyinAccent" : "jiǔ", "definition" : "long (time)" },
{ "simplified" : "只有", "traditional" : "隻有", "pinyin" : "zhi3you3", "pinyinAccent" : "zhǐyǒu", "definition" : "only" },
{ "simplified" : "讲", "traditional" : "講", "pinyin" : "jiang3", "pinyinAccent" : "jiǎng", "definition" : "to talk; to lecture; to explain; a speech" },
{ "simplified" : "故事", "traditional" : "故事", "pinyin" : "gu4shi5", "pinyinAccent" : "gùshi", "definition" : "story; tale" },
{ "simplified" : "换", "traditional" : "換", "pinyin" : "huan4", "pinyinAccent" : "huàn", "definition" : "change; to exchange; to barter; to trade" },
{ "simplified" : "结婚", "traditional" : "結婚", "pinyin" : "jie2hun1", "pinyinAccent" : "jiéhūn", "definition" : "get married" },
{ "simplified" : "段", "traditional" : "段", "pinyin" : "duan4", "pinyinAccent" : "duàn", "definition" : "paragraph; segment; section" },
{ "simplified" : "努力", "traditional" : "努力", "pinyin" : "nu3li4", "pinyinAccent" : "nǔlì", "definition" : "to work hard; to strive" },
{ "simplified" : "害怕", "traditional" : "害怕", "pinyin" : "hai4pa4", "pinyinAccent" : "hàipà", "definition" : "afraid of; to fear" },
{ "simplified" : "刚才", "traditional" : "剛才", "pinyin" : "gang1cai2", "pinyinAccent" : "gāngcái", "definition" : "just now; a moment ago" },
{ "simplified" : "节目", "traditional" : "節目", "pinyin" : "jie2mu4", "pinyinAccent" : "jiémù", "definition" : "program; item (on a program)" },
{ "simplified" : "辆", "traditional" : "輛", "pinyin" : "liang4", "pinyinAccent" : "liàng", "definition" : "(mw for vehicles)" },
{ "simplified" : "万", "traditional" : "萬", "pinyin" : "wan4", "pinyinAccent" : "wàn", "definition" : "ten thousand" },
{ "simplified" : "解决", "traditional" : "解決", "pinyin" : "jie3jue2", "pinyinAccent" : "jiějué", "definition" : "settle (a dispute); resolve; solve" },
{ "simplified" : "办公室", "traditional" : "辦公室", "pinyin" : "ban4gong1shi4", "pinyinAccent" : "bàngōngshì", "definition" : "office" },
{ "simplified" : "奇怪", "traditional" : "奇怪", "pinyin" : "qi2guai4", "pinyinAccent" : "qíguài", "definition" : "strange; odd" },
{ "simplified" : "同意", "traditional" : "同意", "pinyin" : "tong2yi4", "pinyinAccent" : "tóngyì", "definition" : "agree; to consent; approve" },
{ "simplified" : "游戏", "traditional" : "游戲", "pinyin" : "you2xi4", "pinyinAccent" : "yóuxì", "definition" : "game; play; recreation" },
{ "simplified" : "帮忙", "traditional" : "幫忙", "pinyin" : "bang1mang2", "pinyinAccent" : "bāngmáng", "definition" : "to help" },
{ "simplified" : "国家", "traditional" : "國家", "pinyin" : "guo2jia1", "pinyinAccent" : "guójiā", "definition" : "country; state; nation" },
{ "simplified" : "最近", "traditional" : "最近", "pinyin" : "zui4jin4", "pinyinAccent" : "zuìjìn", "definition" : "recently; lately; these days" },
{ "simplified" : "声音", "traditional" : "聲音", "pinyin" : "sheng1yin1", "pinyinAccent" : "shēngyīn", "definition" : "sound; voice" },
{ "simplified" : "可爱", "traditional" : "可愛", "pinyin" : "ke3'ai4", "pinyinAccent" : "kě'ài", "definition" : "cute; lovely" },
{ "simplified" : "分", "traditional" : "分", "pinyin" : "fen1, fen4", "pinyinAccent" : "fēn, fèn", "definition" : "divide; part; minute; cent | component; share; ingredient" },
{ "simplified" : "完成", "traditional" : "完成", "pinyin" : "wan2cheng2", "pinyinAccent" : "wánchéng", "definition" : "to complete; accomplish; to fulfill" },
{ "simplified" : "半", "traditional" : "半", "pinyin" : "ban4", "pinyinAccent" : "bàn", "definition" : "half; semi-; incomplete" },
{ "simplified" : "要求", "traditional" : "要求", "pinyin" : "yao1qiu2", "pinyinAccent" : "yāoqiú", "definition" : "to request; to demand; requirement" },
{ "simplified" : "除了", "traditional" : "除了", "pinyin" : "chu2le5", "pinyinAccent" : "chúle", "definition" : "besides; except for; aside from; in addition to" },
{ "simplified" : "容易", "traditional" : "容易", "pinyin" : "rong2yi4", "pinyinAccent" : "róngyì", "definition" : "easy; likely; liable (to)" },
{ "simplified" : "教", "traditional" : "教", "pinyin" : "jiao1, jiao4", "pinyinAccent" : "jiāo, jiào", "definition" : "teach; instruct | religion; teaching" },
{ "simplified" : "脸", "traditional" : "臉", "pinyin" : "lian3", "pinyinAccent" : "liǎn", "definition" : "face" },
{ "simplified" : "简单", "traditional" : "簡單", "pinyin" : "jian3dan1", "pinyinAccent" : "jiǎndān", "definition" : "simple; not complicated" },
{ "simplified" : "检查", "traditional" : "檢查", "pinyin" : "jian3cha2", "pinyinAccent" : "jiǎnchá", "definition" : "to check; examine; inspect" },
{ "simplified" : "音乐", "traditional" : "音樂", "pinyin" : "yin1yue4", "pinyinAccent" : "yīnyuè", "definition" : "music" },
{ "simplified" : "越", "traditional" : "越", "pinyin" : "yue4", "pinyinAccent" : "yuè", "definition" : "even more; the more; exceed" },
{ "simplified" : "照顾", "traditional" : "照顧", "pinyin" : "zhao4gu5", "pinyinAccent" : "zhàogu", "definition" : "take care of; look after; give consideration" },
{ "simplified" : "聪明", "traditional" : "聰明", "pinyin" : "cong1ming5", "pinyinAccent" : "cōngming", "definition" : "intelligent; clever; bright; smart" },
{ "simplified" : "甜", "traditional" : "甜", "pinyin" : "tian2", "pinyinAccent" : "tián", "definition" : "sweet" },
{ "simplified" : "突然", "traditional" : "突然", "pinyin" : "tu1ran2", "pinyinAccent" : "tūrán", "definition" : "sudden; abrupt" },
{ "simplified" : "终于", "traditional" : "終於", "pinyin" : "zhong1yu2", "pinyinAccent" : "zhōngyú", "definition" : "at last; in the end; finally" },
{ "simplified" : "船", "traditional" : "船", "pinyin" : "chuan2", "pinyinAccent" : "chuán", "definition" : "a boat; vessel; ship" },
{ "simplified" : "口", "traditional" : "口", "pinyin" : "kou3", "pinyinAccent" : "kǒu", "definition" : "mouth (Kangxi radical 30)" },
{ "simplified" : "回答", "traditional" : "回答", "pinyin" : "hui2da2", "pinyinAccent" : "huídá", "definition" : "to reply; to answer" },
{ "simplified" : "礼物", "traditional" : "禮物", "pinyin" : "li3wu4", "pinyinAccent" : "lǐwù", "definition" : "gift; present" },
{ "simplified" : "头发", "traditional" : "頭發", "pinyin" : "tou2fa5", "pinyinAccent" : "tóufa", "definition" : "hair (on the head)" },
{ "simplified" : "关心", "traditional" : "關心", "pinyin" : "guan1xin1", "pinyinAccent" : "guānxīn", "definition" : "concerned about/with" },
{ "simplified" : "脚", "traditional" : "腳", "pinyin" : "jiao3", "pinyinAccent" : "jiǎo", "definition" : "foot (body part)" },
{ "simplified" : "生气", "traditional" : "生氣", "pinyin" : "sheng1qi4", "pinyinAccent" : "shēngqì", "definition" : "angry; mad" },
{ "simplified" : "哭", "traditional" : "哭", "pinyin" : "ku1", "pinyinAccent" : "kū", "definition" : "cry; weep" },
{ "simplified" : "画", "traditional" : "畫", "pinyin" : "hua4", "pinyinAccent" : "huà", "definition" : "draw; picture; painting" },
{ "simplified" : "年轻", "traditional" : "年輕", "pinyin" : "nian2qing1", "pinyinAccent" : "niánqīng", "definition" : "young" },
{ "simplified" : "包", "traditional" : "包", "pinyin" : "bao1", "pinyinAccent" : "bāo", "definition" : "to cover; to wrap; to hold; include; (mw for containers, packages, etc.)" },
{ "simplified" : "腿", "traditional" : "腿", "pinyin" : "tui3", "pinyinAccent" : "tuǐ", "definition" : "leg" },
{ "simplified" : "忘记", "traditional" : "忘記", "pinyin" : "wang4ji4", "pinyinAccent" : "wàngjì", "definition" : "forget" },
{ "simplified" : "搬", "traditional" : "搬", "pinyin" : "ban1", "pinyinAccent" : "bān", "definition" : "to move; to transport" },
{ "simplified" : "楼", "traditional" : "樓", "pinyin" : "lou2", "pinyinAccent" : "lóu", "definition" : "story; floor; (multi-story) building" },
{ "simplified" : "遇到", "traditional" : "遇到", "pinyin" : "yu4dao4", "pinyinAccent" : "yùdào", "definition" : "to meet; run into; come across" },
{ "simplified" : "新闻", "traditional" : "新聞", "pinyin" : "xin1wen2", "pinyinAccent" : "xīnwén", "definition" : "news" },
{ "simplified" : "比较", "traditional" : "比較", "pinyin" : "bi3jiao4", "pinyinAccent" : "bǐjiào", "definition" : "compare; contrast; relatively" },
{ "simplified" : "双", "traditional" : "雙", "pinyin" : "shuang1", "pinyinAccent" : "shuāng", "definition" : "two; double; (mw for pairs)" },
{ "simplified" : "见面", "traditional" : "見面", "pinyin" : "jian4mian4", "pinyinAccent" : "jiànmiàn", "definition" : "meet/see somebody (face to face); meeting" },
{ "simplified" : "经常", "traditional" : "經常", "pinyin" : "jing1chang2", "pinyinAccent" : "jīngcháng", "definition" : "often; frequently; daily" },
{ "simplified" : "城市", "traditional" : "城市", "pinyin" : "cheng2shi4", "pinyinAccent" : "chéngshì", "definition" : "city or town" },
{ "simplified" : "一会儿", "traditional" : "一會兒", "pinyin" : "yi2hui4r5", "pinyinAccent" : "yíhuìr", "definition" : "a while; a moment" },
{ "simplified" : "附近", "traditional" : "附近", "pinyin" : "fu4jin4", "pinyinAccent" : "fùjìn", "definition" : "(in the) vicinity; nearby; neighboring" },
{ "simplified" : "借", "traditional" : "借", "pinyin" : "jie4", "pinyinAccent" : "jiè", "definition" : "lend; borrow; excuse" },
{ "simplified" : "影响", "traditional" : "影響", "pinyin" : "ying3xiang3", "pinyinAccent" : "yǐngxiǎng", "definition" : "influence; affect; effect" },
{ "simplified" : "认真", "traditional" : "認真", "pinyin" : "ren4zhen1", "pinyinAccent" : "rènzhēn", "definition" : "serious; earnest; take seriously" },
{ "simplified" : "米", "traditional" : "米", "pinyin" : "mi3", "pinyinAccent" : "mǐ", "definition" : "rice; meter (Kangxi radical 119)" },
{ "simplified" : "差", "traditional" : "差", "pinyin" : "cha4, cha1, chai1, ci1", "pinyinAccent" : "chà, chā, chāi, cī", "definition" : "differ from; fall short of; poor; inferior | difference | to dispatch" },
{ "simplified" : "银行", "traditional" : "銀行", "pinyin" : "yin2hang2", "pinyinAccent" : "yínháng", "definition" : "bank" },
{ "simplified" : "安静", "traditional" : "安靜", "pinyin" : "an1jing4", "pinyinAccent" : "ānjìng", "definition" : "quiet; peaceful; calm" },
{ "simplified" : "多么", "traditional" : "多麼", "pinyin" : "duo1me5", "pinyinAccent" : "duōme", "definition" : "how (wonderful, etc.); what (a great idea)" },
{ "simplified" : "饿", "traditional" : "餓", "pinyin" : "e4", "pinyinAccent" : "è", "definition" : "hungry" },
{ "simplified" : "根据", "traditional" : "根據", "pinyin" : "gen1ju4", "pinyinAccent" : "gēnjù", "definition" : "according to; based on; basis" },
{ "simplified" : "几乎", "traditional" : "幾乎", "pinyin" : "ji1hu1", "pinyinAccent" : "jīhū", "definition" : "almost" },
{ "simplified" : "后来", "traditional" : "后來", "pinyin" : "hou4lai2", "pinyinAccent" : "hòulái", "definition" : "afterwards; after; later" },
{ "simplified" : "动物", "traditional" : "動物", "pinyin" : "dong4wu4", "pinyinAccent" : "dòngwù", "definition" : "animal" },
{ "simplified" : "西", "traditional" : "西", "pinyin" : "xi1", "pinyinAccent" : "xī", "definition" : "West (Kangxi radical 146)" },
{ "simplified" : "一边", "traditional" : "一邊", "pinyin" : "yi4bian1", "pinyinAccent" : "yìbiān", "definition" : "one side; on the one hand; at the same time" },
{ "simplified" : "舒服", "traditional" : "舒服", "pinyin" : "shu1fu5", "pinyinAccent" : "shūfu", "definition" : "comfortable; feeling well" },
{ "simplified" : "一般", "traditional" : "一般", "pinyin" : "yi4ban1", "pinyinAccent" : "yìbān", "definition" : "general; ordinary; common; same" },
{ "simplified" : "叔叔", "traditional" : "叔叔", "pinyin" : "shu1shu5", "pinyinAccent" : "shūshu", "definition" : "(informal) father's younger brother; uncle" },
{ "simplified" : "疼", "traditional" : "疼", "pinyin" : "teng2", "pinyinAccent" : "téng", "definition" : "ache; sore; (it) hurts; love fondly" },
{ "simplified" : "迟到", "traditional" : "遲到", "pinyin" : "chi2dao4", "pinyinAccent" : "chídào", "definition" : "arrive late" },
{ "simplified" : "历史", "traditional" : "歷史", "pinyin" : "li4shi3", "pinyinAccent" : "lìshǐ", "definition" : "history" },
{ "simplified" : "啤酒", "traditional" : "啤酒", "pinyin" : "pi2jiu3", "pinyinAccent" : "píjiǔ", "definition" : "beer" },
{ "simplified" : "短", "traditional" : "短", "pinyin" : "duan3", "pinyinAccent" : "duǎn", "definition" : "short (in length, duration, or height); lack" },
{ "simplified" : "经过", "traditional" : "經過", "pinyin" : "jing1guo4", "pinyinAccent" : "jīngguò", "definition" : "to pass; go through; as a result of" },
{ "simplified" : "周末", "traditional" : "周末", "pinyin" : "zhou1mo4", "pinyinAccent" : "zhōumò", "definition" : "weekend" },
{ "simplified" : "班", "traditional" : "班", "pinyin" : "ban1", "pinyinAccent" : "bān", "definition" : "team; class; squad" },
{ "simplified" : "习惯", "traditional" : "習慣", "pinyin" : "xi2guan4", "pinyinAccent" : "xíguàn", "definition" : "habit; be accustomed to; usual practice" },
{ "simplified" : "公园", "traditional" : "公園", "pinyin" : "gong1yuan2", "pinyinAccent" : "gōngyuán", "definition" : "public park" },
{ "simplified" : "干净", "traditional" : "干淨", "pinyin" : "gan1jing4", "pinyinAccent" : "gānjìng", "definition" : "clean; neat and tidy" },
{ "simplified" : "鸟", "traditional" : "鳥", "pinyin" : "niao3", "pinyinAccent" : "niǎo", "definition" : "bird (Kangxi radical 196)" },
{ "simplified" : "健康", "traditional" : "健康", "pinyin" : "jian4kang1", "pinyinAccent" : "jiànkāng", "definition" : "health; healthy" },
{ "simplified" : "树", "traditional" : "樹", "pinyin" : "shu4", "pinyinAccent" : "shù", "definition" : "tree" },
{ "simplified" : "蛋糕", "traditional" : "蛋糕", "pinyin" : "dan4gao1", "pinyinAccent" : "dàngāo", "definition" : "cake" },
{ "simplified" : "元", "traditional" : "元", "pinyin" : "yuan2", "pinyinAccent" : "yuán", "definition" : "Chinese monetary unit; dollar; first; principal" },
{ "simplified" : "客人", "traditional" : "客人", "pinyin" : "ke4ren2", "pinyinAccent" : "kèrén", "definition" : "guest; customer" },
{ "simplified" : "会议", "traditional" : "會議", "pinyin" : "hui4yi4", "pinyinAccent" : "huìyì", "definition" : "meeting; conference" },
{ "simplified" : "奶奶", "traditional" : "奶奶", "pinyin" : "nai3nai5", "pinyinAccent" : "nǎinai", "definition" : "grandma; (informal) paternal grandmother" },
{ "simplified" : "裤子", "traditional" : "褲子", "pinyin" : "ku4zi5", "pinyinAccent" : "kùzi", "definition" : "pants; trousers" },
{ "simplified" : "邻居", "traditional" : "鄰居", "pinyin" : "lin2ju1", "pinyinAccent" : "línjū", "definition" : "neighbor" },
{ "simplified" : "经理", "traditional" : "經理", "pinyin" : "jing1li3", "pinyinAccent" : "jīnglǐ", "definition" : "manager; director" },
{ "simplified" : "层", "traditional" : "層", "pinyin" : "ceng2", "pinyinAccent" : "céng", "definition" : "(mw for layers, floors of buildings)" },
{ "simplified" : "灯", "traditional" : "燈", "pinyin" : "deng1", "pinyinAccent" : "dēng", "definition" : "lamp; light" },
{ "simplified" : "练习", "traditional" : "練習", "pinyin" : "lian4xi2", "pinyinAccent" : "liànxí", "definition" : "practice; exercise" },
{ "simplified" : "爷爷", "traditional" : "爺爺", "pinyin" : "ye2ye5", "pinyinAccent" : "yéye", "definition" : "(informal) father's father; paternal grandfather" },
{ "simplified" : "蓝", "traditional" : "藍", "pinyin" : "lan2", "pinyinAccent" : "lán", "definition" : "blue" },
{ "simplified" : "难过", "traditional" : "難過", "pinyin" : "nan2guo4", "pinyinAccent" : "nánguò", "definition" : "be grieved; be sad; have a hard time" },
{ "simplified" : "中间", "traditional" : "中間", "pinyin" : "zhong1jian1", "pinyinAccent" : "zhōngjiān", "definition" : "center; middle; between; among" },
{ "simplified" : "帽子", "traditional" : "帽子", "pinyin" : "mao4zi5", "pinyinAccent" : "màozi", "definition" : "hat; cap" },
{ "simplified" : "司机", "traditional" : "司機", "pinyin" : "si1ji1", "pinyinAccent" : "sījī", "definition" : "driver; chauffeur" },
{ "simplified" : "旧", "traditional" : "舊", "pinyin" : "jiu4", "pinyinAccent" : "jiù", "definition" : "old; past; used" },
{ "simplified" : "满意", "traditional" : "滿意", "pinyin" : "man3yi4", "pinyinAccent" : "mǎnyì", "definition" : "satisfied; pleased" },
{ "simplified" : "骑", "traditional" : "騎", "pinyin" : "qi2", "pinyinAccent" : "qí", "definition" : "to ride (an animal or bike); to sit astride" },
{ "simplified" : "太阳", "traditional" : "太陽", "pinyin" : "tai4yang2", "pinyinAccent" : "tàiyáng", "definition" : "the sun" },
{ "simplified" : "极", "traditional" : "極", "pinyin" : "ji2", "pinyinAccent" : "jí", "definition" : "an extreme; pole; very" },
{ "simplified" : "主要", "traditional" : "主要", "pinyin" : "zhu3yao4", "pinyinAccent" : "zhǔyào", "definition" : "main; principal; major" },
{ "simplified" : "同事", "traditional" : "同事", "pinyin" : "tong2shi4", "pinyinAccent" : "tóngshì", "definition" : "colleague; co-worker" },
{ "simplified" : "鼻子", "traditional" : "鼻子", "pinyin" : "bi2zi5", "pinyinAccent" : "bízi", "definition" : "nose" },
{ "simplified" : "角", "traditional" : "角", "pinyin" : "jiao3, jue2", "pinyinAccent" : "jiǎo, jué", "definition" : "horn; angle; unit of money (1/10 yuan); corner (Kangxi radical 148) | role (theater)" },
{ "simplified" : "变化", "traditional" : "變化", "pinyin" : "bian4hua4", "pinyinAccent" : "biànhuà", "definition" : "change" },
{ "simplified" : "东", "traditional" : "東", "pinyin" : "dong1", "pinyinAccent" : "dōng", "definition" : "East" },
{ "simplified" : "年级", "traditional" : "年級", "pinyin" : "nian2ji2", "pinyinAccent" : "niánjí", "definition" : "grade; year (in school)" },
{ "simplified" : "环境", "traditional" : "環境", "pinyin" : "huan2jing4", "pinyinAccent" : "huánjìng", "definition" : "environment; surroundings" },
{ "simplified" : "胖", "traditional" : "胖", "pinyin" : "pang4", "pinyinAccent" : "pàng", "definition" : "fat; plump" },
{ "simplified" : "地图", "traditional" : "地圖", "pinyin" : "di4tu2", "pinyinAccent" : "dìtú", "definition" : "map" },
{ "simplified" : "面包", "traditional" : "面包", "pinyin" : "mian4bao1", "pinyinAccent" : "miànbāo", "definition" : "bread" },
{ "simplified" : "电子邮件", "traditional" : "電子郵件", "pinyin" : "dian4zi3 you2jian4", "pinyinAccent" : "diànzǐ yóujiàn", "definition" : "email" },
{ "simplified" : "耳朵", "traditional" : "耳朵", "pinyin" : "er3duo5", "pinyinAccent" : "ěrduo", "definition" : "ear" },
{ "simplified" : "裙子", "traditional" : "裙子", "pinyin" : "qun2zi5", "pinyinAccent" : "qúnzi", "definition" : "skirt" },
{ "simplified" : "新鲜", "traditional" : "新鮮", "pinyin" : "xin1xian1", "pinyinAccent" : "xīnxiān", "definition" : "fresh (experience, food, etc.); new; novel" },
{ "simplified" : "放心", "traditional" : "放心", "pinyin" : "fang4 xin1", "pinyinAccent" : "fàng xīn", "definition" : "relax; feel relieved; rest assured" },
{ "simplified" : "聊天", "traditional" : "聊天", "pinyin" : "liao2tian1", "pinyinAccent" : "liáotiān", "definition" : "to chat" },
{ "simplified" : "南", "traditional" : "南", "pinyin" : "nan2", "pinyinAccent" : "nán", "definition" : "South" },
{ "simplified" : "热情", "traditional" : "熱情", "pinyin" : "re4qing2", "pinyinAccent" : "rèqíng", "definition" : "cordial; warm; enthusiastic" },
{ "simplified" : "信用卡", "traditional" : "信用卡", "pinyin" : "xin4yong4ka3", "pinyinAccent" : "xìnyòngkǎ", "definition" : "credit card" },
{ "simplified" : "电梯", "traditional" : "電梯", "pinyin" : "dian4ti1", "pinyinAccent" : "diàntī", "definition" : "elevator" },
{ "simplified" : "方便", "traditional" : "方便", "pinyin" : "fang1bian4", "pinyinAccent" : "fāngbiàn", "definition" : "convenient" },
{ "simplified" : "洗手间", "traditional" : "洗手間", "pinyin" : "xi3shou3jian1", "pinyinAccent" : "xǐshǒujiān", "definition" : "toilet; lavatory; washroom" },
{ "simplified" : "洗澡", "traditional" : "洗澡", "pinyin" : "xi3zao3", "pinyinAccent" : "xǐzǎo", "definition" : "bathe; take a bath or shower; bath or shower" },
{ "simplified" : "饮料", "traditional" : "飲料", "pinyin" : "yin3liao4", "pinyinAccent" : "yǐnliào", "definition" : "beverage; drink" },
{ "simplified" : "校长", "traditional" : "校長", "pinyin" : "xiao4zhang3", "pinyinAccent" : "xiàozhǎng", "definition" : "principal (of school, college or university); president; headmaster" },
{ "simplified" : "水平", "traditional" : "水平", "pinyin" : "shui3ping2", "pinyinAccent" : "shuǐpíng", "definition" : "level; standard; horizontal" },
{ "simplified" : "作业", "traditional" : "作業", "pinyin" : "zuo4ye4", "pinyinAccent" : "zuòyè", "definition" : "school assignment; homework; task" },
{ "simplified" : "衬衫", "traditional" : "襯衫", "pinyin" : "chen4shan1", "pinyinAccent" : "chènshān", "definition" : "shirt; blouse" },
{ "simplified" : "成绩", "traditional" : "成績", "pinyin" : "cheng2ji4", "pinyinAccent" : "chéngjì", "definition" : "achievement; success; results (of work or study)" },
{ "simplified" : "碗", "traditional" : "碗", "pinyin" : "wan3", "pinyinAccent" : "wǎn", "definition" : "bowl; cup" },
{ "simplified" : "阿姨", "traditional" : "阿姨", "pinyin" : "a1yi2", "pinyinAccent" : "āyí", "definition" : "auntie; step-mother; mother's younger sister" },
{ "simplified" : "图书馆", "traditional" : "圖書館", "pinyin" : "tu2shu1guan3", "pinyinAccent" : "túshūguǎn", "definition" : "library" },
{ "simplified" : "文化", "traditional" : "文化", "pinyin" : "wen2hua4", "pinyinAccent" : "wénhuà", "definition" : "culture; civilization" },
{ "simplified" : "绿", "traditional" : "綠", "pinyin" : "lv4", "pinyinAccent" : "lǜ", "definition" : "green" },
{ "simplified" : "打扫", "traditional" : "打掃", "pinyin" : "da3sao3", "pinyinAccent" : "dǎsǎo", "definition" : "to clean; to sweep" },
{ "simplified" : "草", "traditional" : "草", "pinyin" : "cao3", "pinyinAccent" : "cǎo", "definition" : "grass; straw; draft (of a document)" },
{ "simplified" : "冰箱", "traditional" : "冰箱", "pinyin" : "bing1xiang1", "pinyinAccent" : "bīngxiāng", "definition" : "refrigerator" },
{ "simplified" : "数学", "traditional" : "數學", "pinyin" : "shu4xue2", "pinyinAccent" : "shùxué", "definition" : "mathematics" },
{ "simplified" : "自行车", "traditional" : "自行車", "pinyin" : "zi4xing2che1", "pinyinAccent" : "zìxíngchē", "definition" : "bike; bicycle" },
{ "simplified" : "着急", "traditional" : "著急", "pinyin" : "zhao2ji2", "pinyinAccent" : "zháojí", "definition" : "to worry; feel anxious" },
{ "simplified" : "瘦", "traditional" : "瘦", "pinyin" : "shou4", "pinyinAccent" : "shòu", "definition" : "thin; tight; lean" },
{ "simplified" : "提高", "traditional" : "提高", "pinyin" : "ti2gao1", "pinyinAccent" : "tígāo", "definition" : "to raise; heighten; improve" },
{ "simplified" : "起飞", "traditional" : "起飛", "pinyin" : "qi3fei1", "pinyinAccent" : "qǐfēi", "definition" : "take off (in an airplane); liftoff" },
{ "simplified" : "矮", "traditional" : "矮", "pinyin" : "ai3", "pinyinAccent" : "ǎi", "definition" : "short; low" },
{ "simplified" : "地铁", "traditional" : "地鐵", "pinyin" : "di4tie3", "pinyinAccent" : "dìtiě", "definition" : "subway" },
{ "simplified" : "体育", "traditional" : "體育", "pinyin" : "ti3yu4", "pinyinAccent" : "tǐyù", "definition" : "physical training; sports" },
{ "simplified" : "刻", "traditional" : "刻", "pinyin" : "ke4", "pinyinAccent" : "kè", "definition" : "quarter (hour); (mw for short time intervals); carve; to cut" },
{ "simplified" : "护照", "traditional" : "護照", "pinyin" : "hu4zhao4", "pinyinAccent" : "hùzhào", "definition" : "passport" },
{ "simplified" : "节日", "traditional" : "節日", "pinyin" : "jie2ri4", "pinyinAccent" : "jiérì", "definition" : "holiday; festival" },
{ "simplified" : "盘子", "traditional" : "盤子", "pinyin" : "pan2zi5", "pinyinAccent" : "pánzi", "definition" : "plate; dish; tray" },
{ "simplified" : "一共", "traditional" : "一共", "pinyin" : "yi2gong4", "pinyinAccent" : "yígòng", "definition" : "altogether; in total" },
{ "simplified" : "瓶子", "traditional" : "瓶子", "pinyin" : "ping2zi5", "pinyinAccent" : "píngzi", "definition" : "bottle" },
{ "simplified" : "街道", "traditional" : "街道", "pinyin" : "jie1dao4", "pinyinAccent" : "jiēdào", "definition" : "street" },
{ "simplified" : "锻炼", "traditional" : "鍛煉", "pinyin" : "duan4lian4", "pinyinAccent" : "duànliàn", "definition" : "to exercise; work out; toughen; to temper" },
{ "simplified" : "感冒", "traditional" : "感冒", "pinyin" : "gan3mao4", "pinyinAccent" : "gǎnmào", "definition" : "catch cold; (common) cold" },
{ "simplified" : "爱好", "traditional" : "愛好", "pinyin" : "ai4hao4", "pinyinAccent" : "àihào", "definition" : "hobby; fond of; to like; interest" },
{ "simplified" : "超市", "traditional" : "超市", "pinyin" : "chao1shi4", "pinyinAccent" : "chāoshì", "definition" : "supermarket" },
{ "simplified" : "月亮", "traditional" : "月亮", "pinyin" : "yue4liang5", "pinyinAccent" : "yuèliang", "definition" : "the moon" },
{ "simplified" : "饱", "traditional" : "飽", "pinyin" : "bao3", "pinyinAccent" : "bǎo", "definition" : "eat until full; satisfied" },
{ "simplified" : "有名", "traditional" : "有名", "pinyin" : "you3ming2", "pinyinAccent" : "yǒumíng", "definition" : "famous; well-known" },
{ "simplified" : "香蕉", "traditional" : "香蕉", "pinyin" : "xiang1jiao1", "pinyinAccent" : "xiāngjiāo", "definition" : "banana" },
{ "simplified" : "笔记本", "traditional" : "筆記本", "pinyin" : "bi3ji4ben3", "pinyinAccent" : "bǐjìběn", "definition" : "notebook" },
{ "simplified" : "夏", "traditional" : "夏", "pinyin" : "xia4", "pinyinAccent" : "xià", "definition" : "summer" },
{ "simplified" : "菜单", "traditional" : "菜單", "pinyin" : "cai4dan1", "pinyinAccent" : "càidān", "definition" : "menu" },
{ "simplified" : "北方", "traditional" : "北方", "pinyin" : "bei3fang1", "pinyinAccent" : "běifāng", "definition" : "north; the northern part of the country" },
{ "simplified" : "上网", "traditional" : "上網", "pinyin" : "shang4wang3", "pinyinAccent" : "shàngwǎng", "definition" : "to surf the web; to go online" },
{ "simplified" : "季节", "traditional" : "季節", "pinyin" : "ji4jie2", "pinyinAccent" : "jìjié", "definition" : "season; time; period" },
{ "simplified" : "渴", "traditional" : "渴", "pinyin" : "ke3", "pinyinAccent" : "kě", "definition" : "thirsty" },
{ "simplified" : "发烧", "traditional" : "發燒", "pinyin" : "fa1shao1", "pinyinAccent" : "fāshāo", "definition" : "have a fever" },
{ "simplified" : "不但", "traditional" : "不但", "pinyin" : "bu2dan4", "pinyinAccent" : "búdàn", "definition" : "not only" },
{ "simplified" : "空调", "traditional" : "空調", "pinyin" : "kong1tiao2", "pinyinAccent" : "kōngtiáo", "definition" : "air conditioning" },
{ "simplified" : "照相机", "traditional" : "照相機", "pinyin" : "zhao4xiang4ji1", "pinyinAccent" : "zhàoxiàngjī", "definition" : "camera" },
{ "simplified" : "春", "traditional" : "春", "pinyin" : "chun1", "pinyinAccent" : "chūn", "definition" : "spring (season); joyful" },
{ "simplified" : "伞", "traditional" : "傘", "pinyin" : "san3", "pinyinAccent" : "sǎn", "definition" : "umbrella; parasol" },
{ "simplified" : "公斤", "traditional" : "公斤", "pinyin" : "gong1jin1", "pinyinAccent" : "gōngjīn", "definition" : "kilogram" },
{ "simplified" : "个子", "traditional" : "個子", "pinyin" : "ge4zi5", "pinyinAccent" : "gèzi", "definition" : "height; stature; build" },
{ "simplified" : "熊猫", "traditional" : "熊貓", "pinyin" : "xiong2mao1", "pinyinAccent" : "xióngmāo", "definition" : "panda" },
{ "simplified" : "刷牙", "traditional" : "刷牙", "pinyin" : "shua1ya2", "pinyinAccent" : "shuāyá", "definition" : "brush one's teeth" },
{ "simplified" : "复习", "traditional" : "復習", "pinyin" : "fu4xi2", "pinyinAccent" : "fùxí", "definition" : "revise; to review" },
{ "simplified" : "冬", "traditional" : "冬", "pinyin" : "dong1", "pinyinAccent" : "dōng", "definition" : "winter" },
{ "simplified" : "请假", "traditional" : "請假", "pinyin" : "qing3 jia4", "pinyinAccent" : "qǐng jià", "definition" : "to ask for time off" },
{ "simplified" : "中文", "traditional" : "中文", "pinyin" : "Zhong1wen2", "pinyinAccent" : "Zhōngwén", "definition" : "Chinese (language)" },
{ "simplified" : "秋", "traditional" : "秋", "pinyin" : "qiu1", "pinyinAccent" : "qiū", "definition" : "autumn; fall; harvest time" },
{ "simplified" : "句子", "traditional" : "句子", "pinyin" : "ju4zi5", "pinyinAccent" : "jùzi", "definition" : "sentence" },
{ "simplified" : "行李箱", "traditional" : "行李箱", "pinyin" : "xing2li3xiang1", "pinyinAccent" : "xínglǐxiāng", "definition" : "trunk; suitcase" },
{ "simplified" : "筷子", "traditional" : "筷子", "pinyin" : "kuai4zi5", "pinyinAccent" : "kuàizi", "definition" : "chopsticks" },
{ "simplified" : "皮鞋", "traditional" : "皮鞋", "pinyin" : "pi2xie2", "pinyinAccent" : "píxié", "definition" : "leather shoes" },
{ "simplified" : "爬山", "traditional" : "爬山", "pinyin" : "pa2shan1", "pinyinAccent" : "páshān", "definition" : "mountain climbing" },
{ "simplified" : "黑板", "traditional" : "黑板", "pinyin" : "hei1ban3", "pinyinAccent" : "hēibǎn", "definition" : "blackboard" },
{ "simplified" : "感兴趣", "traditional" : "感興趣", "pinyin" : "gan3 xing4qu4", "pinyinAccent" : "gǎn xìngqù", "definition" : "be interested in" },
{ "simplified" : "词典", "traditional" : "詞典", "pinyin" : "ci2dian3", "pinyinAccent" : "cídiǎn", "definition" : "dictionary" },
{ "simplified" : "留学", "traditional" : "留學", "pinyin" : "liu2 xue2", "pinyinAccent" : "liú xué", "definition" : "study abroad" },
{ "simplified" : "刮风", "traditional" : "刮風", "pinyin" : "gua1feng1", "pinyinAccent" : "guāfēng", "definition" : "windy; to blow (wind)" },
{ "simplified" : "黄河", "traditional" : "黃河", "pinyin" : "huang2he2", "pinyinAccent" : "huánghé", "definition" : "Yellow River" }
]
