export const hsk4 = [
{ "simplified" : "得", "traditional" : "得", "pinyin" : "de2, dei3, de5", "pinyinAccent" : "dé, děi, de", "definition" : "obtain | must | (complement particle)" },
{ "simplified" : "死", "traditional" : "死", "pinyin" : "si3", "pinyinAccent" : "sǐ", "definition" : "to die; dead; fixed; impassible; extremely" },
{ "simplified" : "干", "traditional" : "干", "pinyin" : "gan4, gan1", "pinyinAccent" : "gàn, gān", "definition" : "to work; do; manage; tree trunk | to concern; shield; dry; clean (Kangxi radical 51)" },
{ "simplified" : "而", "traditional" : "而", "pinyin" : "er2", "pinyinAccent" : "ér", "definition" : "and; but; yet; while (Kangxi radical 126)" },
{ "simplified" : "等", "traditional" : "等", "pinyin" : "deng3", "pinyinAccent" : "děng", "definition" : "to wait; rank; equal; etc." },
{ "simplified" : "当", "traditional" : "當", "pinyin" : "dang1, dang4", "pinyinAccent" : "dāng, dàng", "definition" : "should; act as; work as; manage; match; (sound of bells) | appropriate; assume; pawn" },
{ "simplified" : "所有", "traditional" : "所有", "pinyin" : "suo3you3", "pinyinAccent" : "suǒyǒu", "definition" : "all; to have; to possess" },
{ "simplified" : "也许", "traditional" : "也許", "pinyin" : "ye3xu3", "pinyinAccent" : "yěxǔ", "definition" : "perhaps; probably; maybe" },
{ "simplified" : "行", "traditional" : "行", "pinyin" : "xing2, hang2", "pinyinAccent" : "xíng, háng", "definition" : "walk; be current; do; will do; okay | row; place; a firm (Kangxi radical 144)" },
{ "simplified" : "不过", "traditional" : "不過", "pinyin" : "bu2guo4", "pinyinAccent" : "búguò", "definition" : "only; merely; but; however" },
{ "simplified" : "发生", "traditional" : "發生", "pinyin" : "fa1sheng1", "pinyinAccent" : "fāshēng", "definition" : "happen; occur; take place" },
{ "simplified" : "一切", "traditional" : "一切", "pinyin" : "yi2qie4", "pinyinAccent" : "yíqiè", "definition" : "all; every; everything" },
{ "simplified" : "抱", "traditional" : "抱", "pinyin" : "bao4", "pinyinAccent" : "bào", "definition" : "to hold; to hug; carry in one's arms; to cradle" },
{ "simplified" : "抱歉", "traditional" : "抱歉", "pinyin" : "bao4qian4", "pinyinAccent" : "bàoqiàn", "definition" : "be sorry; feel apologetic; to regret" },
{ "simplified" : "感觉", "traditional" : "感覺", "pinyin" : "gan3jue2", "pinyinAccent" : "gǎnjué", "definition" : "to feel; become aware of; feeling" },
{ "simplified" : "肯定", "traditional" : "肯定", "pinyin" : "ken3ding4", "pinyinAccent" : "kěndìng", "definition" : "sure; definite; affirm; approve" },
{ "simplified" : "棒", "traditional" : "棒", "pinyin" : "bang4", "pinyinAccent" : "bàng", "definition" : "stick; club; good; excellent" },
{ "simplified" : "以", "traditional" : "以", "pinyin" : "yi3", "pinyinAccent" : "yǐ", "definition" : "to use; according to; so as to; for; by" },
{ "simplified" : "以为", "traditional" : "以為", "pinyin" : "yi3wei2", "pinyinAccent" : "yǐwéi", "definition" : "think (mistakenly); consider (that); believe" },
{ "simplified" : "掉", "traditional" : "掉", "pinyin" : "diao4", "pinyinAccent" : "diào", "definition" : "to drop; to fall" },
{ "simplified" : "生活", "traditional" : "生活", "pinyin" : "sheng1huo2", "pinyinAccent" : "shēnghuó", "definition" : "life; livelihood; to live" },
{ "simplified" : "之", "traditional" : "之", "pinyin" : "zhi1", "pinyinAccent" : "zhī", "definition" : "(literary equivalent to 的); (pronoun); of" },
{ "simplified" : "任何", "traditional" : "任何", "pinyin" : "ren4he2", "pinyinAccent" : "rènhé", "definition" : "any; whatever; whichever" },
{ "simplified" : "与", "traditional" : "與", "pinyin" : "yu3, yu4, yu2", "pinyinAccent" : "yǔ, yù, yú", "definition" : "(formal) and; to give; together with; participate; final particle expressing doubt or surprise" },
{ "simplified" : "弄", "traditional" : "弄", "pinyin" : "nong4, long4", "pinyinAccent" : "nòng, lòng", "definition" : "do; manage; to handle; make | lane; alley" },
{ "simplified" : "却", "traditional" : "卻", "pinyin" : "que4", "pinyinAccent" : "què", "definition" : "but; yet; however" },
{ "simplified" : "继续", "traditional" : "繼續", "pinyin" : "ji4xu4", "pinyinAccent" : "jìxù", "definition" : "to continue; to go on; to proceed" },
{ "simplified" : "够", "traditional" : "夠", "pinyin" : "gou4", "pinyinAccent" : "gòu", "definition" : "enough; to reach" },
{ "simplified" : "父亲", "traditional" : "父親", "pinyin" : "fu4qin5", "pinyinAccent" : "fùqin", "definition" : "father" },
{ "simplified" : "完全", "traditional" : "完全", "pinyin" : "wan2quan2", "pinyinAccent" : "wánquán", "definition" : "complete; whole; totally" },
{ "simplified" : "可是", "traditional" : "可是", "pinyin" : "ke3shi4", "pinyinAccent" : "kěshì", "definition" : "but; however" },
{ "simplified" : "谈", "traditional" : "談", "pinyin" : "tan2", "pinyinAccent" : "tán", "definition" : "to talk; to chat; discuss" },
{ "simplified" : "好像", "traditional" : "好像", "pinyin" : "hao3xiang4", "pinyinAccent" : "hǎoxiàng", "definition" : "as if; seem to be" },
{ "simplified" : "警察", "traditional" : "警察", "pinyin" : "jing3cha2", "pinyinAccent" : "jǐngchá", "definition" : "police" },
{ "simplified" : "场", "traditional" : "場", "pinyin" : "chang3, chang2", "pinyinAccent" : "chǎng, cháng", "definition" : "courtyard; place; field; (mw for games, performances, etc.) | threshing floor" },
{ "simplified" : "刚", "traditional" : "剛", "pinyin" : "gang1", "pinyinAccent" : "gāng", "definition" : "just (indicating the immediate past); recently; firm" },
{ "simplified" : "呀", "traditional" : "呀", "pinyin" : "ya5, ya1", "pinyinAccent" : "ya, yā", "definition" : "ah; oh; (used for 啊 after words ending with a, e, i, o, or ü)" },
{ "simplified" : "情况", "traditional" : "情況", "pinyin" : "qing2kuang4", "pinyinAccent" : "qíngkuàng", "definition" : "circumstance; state of affairs; situation" },
{ "simplified" : "只要", "traditional" : "隻要", "pinyin" : "zhi3yao4", "pinyinAccent" : "zhǐyào", "definition" : "so long as; if only; provided that" },
{ "simplified" : "份", "traditional" : "份", "pinyin" : "fen4", "pinyinAccent" : "fèn", "definition" : "part; portion; (mw for documents, papers, jobs, etc.)" },
{ "simplified" : "底", "traditional" : "底", "pinyin" : "di3", "pinyinAccent" : "dǐ", "definition" : "bottom; background; base" },
{ "simplified" : "到底", "traditional" : "到底", "pinyin" : "dao4 di3", "pinyinAccent" : "dào dǐ", "definition" : "after all; in the end (used in a question)" },
{ "simplified" : "成为", "traditional" : "成為", "pinyin" : "cheng2wei2", "pinyinAccent" : "chéngwéi", "definition" : "become; turn into" },
{ "simplified" : "永远", "traditional" : "永遠", "pinyin" : "yong3yuan3", "pinyinAccent" : "yǒngyuǎn", "definition" : "forever; eternal; always" },
{ "simplified" : "安全", "traditional" : "安全", "pinyin" : "an1quan2", "pinyinAccent" : "ānquán", "definition" : "safe; safety; secure; security" },
{ "simplified" : "留", "traditional" : "留", "pinyin" : "liu2", "pinyinAccent" : "liú", "definition" : "to leave (behind, a message); to retain; to stay" },
{ "simplified" : "计划", "traditional" : "計劃", "pinyin" : "ji4hua4", "pinyinAccent" : "jìhuà", "definition" : "plan; project" },
{ "simplified" : "俩", "traditional" : "倆", "pinyin" : "lia3, liang3", "pinyinAccent" : "liǎ, liǎng", "definition" : "(colloquial) two (people)" },
{ "simplified" : "停", "traditional" : "停", "pinyin" : "ting2", "pinyinAccent" : "tíng", "definition" : "to stop; to halt; to park (a car)" },
{ "simplified" : "感谢", "traditional" : "感謝", "pinyin" : "gan3xie4", "pinyinAccent" : "gǎnxiè", "definition" : "thank; be grateful" },
{ "simplified" : "敢", "traditional" : "敢", "pinyin" : "gan3", "pinyinAccent" : "gǎn", "definition" : "to dare" },
{ "simplified" : "从来", "traditional" : "從來", "pinyin" : "cong2lai2", "pinyinAccent" : "cónglái", "definition" : "have always (from the beginning); never (with negative)" },
{ "simplified" : "赢", "traditional" : "贏", "pinyin" : "ying2", "pinyinAccent" : "yíng", "definition" : "to win; to beat; to profit" },
{ "simplified" : "消息", "traditional" : "消息", "pinyin" : "xiao1xi5", "pinyinAccent" : "xiāoxi", "definition" : "news; information" },
{ "simplified" : "拉", "traditional" : "拉", "pinyin" : "la1, la2", "pinyinAccent" : "lā, lá", "definition" : "to pull; to play (string instruments); to drag | to slash; to chat" },
{ "simplified" : "原因", "traditional" : "原因", "pinyin" : "yuan2yin1", "pinyinAccent" : "yuányīn", "definition" : "cause; reason" },
{ "simplified" : "连", "traditional" : "連", "pinyin" : "lian2", "pinyinAccent" : "lián", "definition" : "even; including; join" },
{ "simplified" : "确实", "traditional" : "確實", "pinyin" : "que4shi2", "pinyinAccent" : "quèshí", "definition" : "indeed; in truth; reliable" },
{ "simplified" : "挺", "traditional" : "挺", "pinyin" : "ting3", "pinyinAccent" : "tǐng", "definition" : "straighten up; stick out; rather (good); very" },
{ "simplified" : "保证", "traditional" : "保証", "pinyin" : "bao3zheng4", "pinyinAccent" : "bǎozhèng", "definition" : "to guarantee; ensure" },
{ "simplified" : "接受", "traditional" : "接受", "pinyin" : "jie1shou4", "pinyinAccent" : "jiēshòu", "definition" : "accept; receive (honors, etc.)" },
{ "simplified" : "改变", "traditional" : "改變", "pinyin" : "gai3bian4", "pinyinAccent" : "gǎibiàn", "definition" : "to change; alter; to transform" },
{ "simplified" : "麻烦", "traditional" : "麻煩", "pinyin" : "ma2fan5", "pinyinAccent" : "máfan", "definition" : "trouble (someone); troubling; bothersome" },
{ "simplified" : "出现", "traditional" : "出現", "pinyin" : "chu1xian4", "pinyinAccent" : "chūxiàn", "definition" : "appear; arise; emerge" },
{ "simplified" : "不管", "traditional" : "不管", "pinyin" : "bu4guan3", "pinyinAccent" : "bùguǎn", "definition" : "no matter (what, how, etc.); regardless of" },
{ "simplified" : "甚至", "traditional" : "甚至", "pinyin" : "shen4zhi4", "pinyinAccent" : "shènzhì", "definition" : "even (to the point of); so much so that" },
{ "simplified" : "保护", "traditional" : "保護", "pinyin" : "bao3hu4", "pinyinAccent" : "bǎohù", "definition" : "to protect; to defend" },
{ "simplified" : "真正", "traditional" : "真正", "pinyin" : "zhen1zheng4", "pinyinAccent" : "zhēnzhèng", "definition" : "genuine; real; true" },
{ "simplified" : "结果", "traditional" : "結果", "pinyin" : "jie2guo3", "pinyinAccent" : "jiéguǒ", "definition" : "result; outcome; finally" },
{ "simplified" : "当时", "traditional" : "當時", "pinyin" : "dang1shi2", "pinyinAccent" : "dāngshí", "definition" : "then; at that time; while" },
{ "simplified" : "至少", "traditional" : "至少", "pinyin" : "zhi4shao3", "pinyinAccent" : "zhìshǎo", "definition" : "at least; (to say the) least" },
{ "simplified" : "律师", "traditional" : "律師", "pinyin" : "lv4shi1", "pinyinAccent" : "lǜshī", "definition" : "lawyer" },
{ "simplified" : "表演", "traditional" : "表演", "pinyin" : "biao3yan3", "pinyinAccent" : "biǎoyǎn", "definition" : "perform; to play" },
{ "simplified" : "无", "traditional" : "無", "pinyin" : "wu2", "pinyinAccent" : "wú", "definition" : "have not; without; not (Kangxi radical 71)" },
{ "simplified" : "猜", "traditional" : "猜", "pinyin" : "cai1", "pinyinAccent" : "cāi", "definition" : "to guess" },
{ "simplified" : "咱们", "traditional" : "咱們", "pinyin" : "zan2men5", "pinyinAccent" : "zánmen", "definition" : "we (including the listener); us; our" },
{ "simplified" : "进行", "traditional" : "進行", "pinyin" : "jin4xing2", "pinyinAccent" : "jìnxíng", "definition" : "carry on; carry out; undertake" },
{ "simplified" : "内", "traditional" : "內", "pinyin" : "nei4", "pinyinAccent" : "nèi", "definition" : "inside; inner; internal; within" },
{ "simplified" : "是否", "traditional" : "是否", "pinyin" : "shi4fou3", "pinyinAccent" : "shìfǒu", "definition" : "whether (or not); if" },
{ "simplified" : "调查", "traditional" : "調查", "pinyin" : "diao4cha2", "pinyinAccent" : "diàochá", "definition" : "investigate; survey; inquiry" },
{ "simplified" : "成功", "traditional" : "成功", "pinyin" : "cheng2gong1", "pinyinAccent" : "chénggōng", "definition" : "success; to succeed" },
{ "simplified" : "考虑", "traditional" : "考慮", "pinyin" : "kao3lv4", "pinyinAccent" : "kǎolǜ", "definition" : "think over; consider" },
{ "simplified" : "约会", "traditional" : "約會", "pinyin" : "yue1hui4", "pinyinAccent" : "yuēhuì", "definition" : "appointment; engagement; date" },
{ "simplified" : "通过", "traditional" : "通過", "pinyin" : "tong1guo4", "pinyinAccent" : "tōngguò", "definition" : "by means of; through (a method); pass through; via" },
{ "simplified" : "开心", "traditional" : "開心", "pinyin" : "kai1xin1", "pinyinAccent" : "kāixīn", "definition" : "feel happy; have a great time; make fun of somebody" },
{ "simplified" : "母亲", "traditional" : "母親", "pinyin" : "mu3qin5", "pinyinAccent" : "mǔqin", "definition" : "mother" },
{ "simplified" : "主意", "traditional" : "主意", "pinyin" : "zhu3yi5", "pinyinAccent" : "zhǔyi", "definition" : "plan; idea; decision" },
{ "simplified" : "倒", "traditional" : "倒", "pinyin" : "dao3, dao4", "pinyinAccent" : "dǎo, dào", "definition" : "to collapse; to fall; fail; to exchange | to pour; contrary to expectations" },
{ "simplified" : "解释", "traditional" : "解釋", "pinyin" : "jie3shi4", "pinyinAccent" : "jiěshì", "definition" : "to explain" },
{ "simplified" : "联系", "traditional" : "聯系", "pinyin" : "lian2xi4", "pinyinAccent" : "liánxì", "definition" : "integrate; link; connection; contact" },
{ "simplified" : "证明", "traditional" : "証明", "pinyin" : "zheng4ming2", "pinyinAccent" : "zhèngmíng", "definition" : "proof; testify; confirm; certificate" },
{ "simplified" : "生命", "traditional" : "生命", "pinyin" : "sheng1ming4", "pinyinAccent" : "shēngmìng", "definition" : "life" },
{ "simplified" : "难道", "traditional" : "難道", "pinyin" : "nan2dao4", "pinyinAccent" : "nándào", "definition" : "could it be that ...?; don't tell me ..." },
{ "simplified" : "由", "traditional" : "由", "pinyin" : "you2", "pinyinAccent" : "yóu", "definition" : "follow; from; by; through" },
{ "simplified" : "指", "traditional" : "指", "pinyin" : "zhi3", "pinyinAccent" : "zhǐ", "definition" : "finger; to point (at, to, out); refer to" },
{ "simplified" : "危险", "traditional" : "危險", "pinyin" : "wei1xian3", "pinyinAccent" : "wēixiǎn", "definition" : "danger; dangerous; perilous" },
{ "simplified" : "讨厌", "traditional" : "討厭", "pinyin" : "tao3yan4", "pinyinAccent" : "tǎoyàn", "definition" : "to hate; loathe; disgusting; troublesome" },
{ "simplified" : "醒", "traditional" : "醒", "pinyin" : "xing3", "pinyinAccent" : "xǐng", "definition" : "wake up" },
{ "simplified" : "样子", "traditional" : "樣子", "pinyin" : "yang4zi5", "pinyinAccent" : "yàngzi", "definition" : "manner; air; appearance; looks" },
{ "simplified" : "有趣", "traditional" : "有趣", "pinyin" : "you3qu4", "pinyinAccent" : "yǒuqù", "definition" : "interesting; fascinating; amusing" },
{ "simplified" : "提", "traditional" : "提", "pinyin" : "ti2", "pinyinAccent" : "tí", "definition" : "to carry; to lift; to raise (an issue)" },
{ "simplified" : "部分", "traditional" : "部分", "pinyin" : "bu4fen5", "pinyinAccent" : "bùfen", "definition" : "part; share; section" },
{ "simplified" : "理解", "traditional" : "理解", "pinyin" : "li3jie3", "pinyinAccent" : "lǐjiě", "definition" : "comprehend; understand" },
{ "simplified" : "重", "traditional" : "重", "pinyin" : "zhong4, chong2", "pinyinAccent" : "zhòng, chóng", "definition" : "heavy; serious; important | repeat; again; overlap" },
{ "simplified" : "任务", "traditional" : "任務", "pinyin" : "ren4wu5", "pinyinAccent" : "rènwu", "definition" : "a mission; an assignment; a task" },
{ "simplified" : "使", "traditional" : "使", "pinyin" : "shi3", "pinyinAccent" : "shǐ", "definition" : "to use; to make; to cause; enable; envoy; messenger" },
{ "simplified" : "转", "traditional" : "轉", "pinyin" : "zhuan3, zhuan4", "pinyinAccent" : "zhuǎn, zhuàn", "definition" : "to turn; to change; pass on | revolve; rotate" },
{ "simplified" : "博士", "traditional" : "博士", "pinyin" : "bo2shi4", "pinyinAccent" : "bóshì", "definition" : "doctor; PhD" },
{ "simplified" : "紧张", "traditional" : "緊張", "pinyin" : "jin3zhang1", "pinyinAccent" : "jǐnzhāng", "definition" : "nervous; tension; strain" },
{ "simplified" : "放弃", "traditional" : "放棄", "pinyin" : "fang4qi4", "pinyinAccent" : "fàngqì", "definition" : "abandon; renounce; give up" },
{ "simplified" : "大概", "traditional" : "大概", "pinyin" : "da4gai4", "pinyinAccent" : "dàgài", "definition" : "probably; roughly; approximate" },
{ "simplified" : "重新", "traditional" : "重新", "pinyin" : "chong2xin1", "pinyinAccent" : "chóngxīn", "definition" : "again; anew; once more" },
{ "simplified" : "其中", "traditional" : "其中", "pinyin" : "qi2zhong1", "pinyinAccent" : "qízhōng", "definition" : "among; in; included among these" },
{ "simplified" : "来自", "traditional" : "來自", "pinyin" : "lai2zi4", "pinyinAccent" : "láizì", "definition" : "come from (a place)" },
{ "simplified" : "本来", "traditional" : "本來", "pinyin" : "ben3lai2", "pinyinAccent" : "běnlái", "definition" : "originally; at first" },
{ "simplified" : "并且", "traditional" : "並且", "pinyin" : "bing4qie3", "pinyinAccent" : "bìngqiě", "definition" : "and; besides; moreover" },
{ "simplified" : "直接", "traditional" : "直接", "pinyin" : "zhi2jie1", "pinyinAccent" : "zhíjiē", "definition" : "direct; immediate" },
{ "simplified" : "对于", "traditional" : "對於", "pinyin" : "dui4yu2", "pinyinAccent" : "duìyú", "definition" : "regarding; as far as sth. is concerned; with regards to; for" },
{ "simplified" : "正常", "traditional" : "正常", "pinyin" : "zheng4chang2", "pinyinAccent" : "zhèngcháng", "definition" : "normal; regular; ordinary" },
{ "simplified" : "遍", "traditional" : "遍", "pinyin" : "bian4", "pinyinAccent" : "biàn", "definition" : "a time; everywhere; turn; (mw for times or turns)" },
{ "simplified" : "冷静", "traditional" : "冷靜", "pinyin" : "leng3jing4", "pinyinAccent" : "lěngjìng", "definition" : "calm; cool-headed; sober" },
{ "simplified" : "方法", "traditional" : "方法", "pinyin" : "fang1fa3", "pinyinAccent" : "fāngfǎ", "definition" : "method; way; means" },
{ "simplified" : "扔", "traditional" : "扔", "pinyin" : "reng1", "pinyinAccent" : "rēng", "definition" : "to throw; throw away" },
{ "simplified" : "能力", "traditional" : "能力", "pinyin" : "neng2li4", "pinyinAccent" : "nénglì", "definition" : "capability; capable; ability" },
{ "simplified" : "另外", "traditional" : "另外", "pinyin" : "ling4wai4", "pinyinAccent" : "lìngwài", "definition" : "another; in addition; besides" },
{ "simplified" : "放松", "traditional" : "放鬆", "pinyin" : "fang4song1", "pinyinAccent" : "fàngsōng", "definition" : "relax; loosen; slacken" },
{ "simplified" : "丢", "traditional" : "丟", "pinyin" : "diu1", "pinyinAccent" : "diū", "definition" : "lose (something); throw; put aside" },
{ "simplified" : "负责", "traditional" : "負責", "pinyin" : "fu4ze2", "pinyinAccent" : "fùzé", "definition" : "responsible for (something); in charge of" },
{ "simplified" : "梦", "traditional" : "夢", "pinyin" : "meng4", "pinyinAccent" : "mèng", "definition" : "to dream" },
{ "simplified" : "戴", "traditional" : "戴", "pinyin" : "dai4", "pinyinAccent" : "dài", "definition" : "put on; to wear; to respect" },
{ "simplified" : "错误", "traditional" : "錯誤", "pinyin" : "cuo4wu4", "pinyinAccent" : "cuòwù", "definition" : "error; mistake; mistaken" },
{ "simplified" : "随便", "traditional" : "隨便", "pinyin" : "sui2bian4", "pinyinAccent" : "suíbiàn", "definition" : "as one pleases; informal; random; casual" },
{ "simplified" : "经历", "traditional" : "經歷", "pinyin" : "jing1li4", "pinyinAccent" : "jīnglì", "definition" : "undergo; to experience" },
{ "simplified" : "支持", "traditional" : "支持", "pinyin" : "zhi1chi2", "pinyinAccent" : "zhīchí", "definition" : "sustain; hold out; | support; stand by (e.g. international support)" },
{ "simplified" : "建议", "traditional" : "建議", "pinyin" : "jian4yi4", "pinyinAccent" : "jiànyì", "definition" : "to propose; to suggest; recommend" },
{ "simplified" : "否则", "traditional" : "否則", "pinyin" : "fou3ze2", "pinyinAccent" : "fǒuzé", "definition" : "if not; otherwise; or else" },
{ "simplified" : "光", "traditional" : "光", "pinyin" : "guang1", "pinyinAccent" : "guāng", "definition" : "light; ray; bright; only; merely; used up" },
{ "simplified" : "安排", "traditional" : "安排", "pinyin" : "an1pai2", "pinyinAccent" : "ānpái", "definition" : "arrange; to plan" },
{ "simplified" : "钥匙", "traditional" : "鑰匙", "pinyin" : "yao4shi5", "pinyinAccent" : "yàoshi", "definition" : "key" },
{ "simplified" : "信息", "traditional" : "信息", "pinyin" : "xin4xi1", "pinyinAccent" : "xìnxī", "definition" : "information; news; message" },
{ "simplified" : "全部", "traditional" : "全部", "pinyin" : "quan2bu4", "pinyinAccent" : "quánbù", "definition" : "whole; entire; complete" },
{ "simplified" : "首先", "traditional" : "首先", "pinyin" : "shou3xian1", "pinyinAccent" : "shǒuxiān", "definition" : "first (of all); in the first place; firstly" },
{ "simplified" : "照", "traditional" : "照", "pinyin" : "zhao4", "pinyinAccent" : "zhào", "definition" : "to shine; illuminate; according to" },
{ "simplified" : "交", "traditional" : "交", "pinyin" : "jiao1", "pinyinAccent" : "jiāo", "definition" : "deliver; turn over; intersect; to pay (money); friendship" },
{ "simplified" : "台", "traditional" : "台", "pinyin" : "tai2", "pinyinAccent" : "tái", "definition" : "platform; Taiwan (abbr.); desk; stage; typhoon; (mw for machines); (classical) you (in letters)" },
{ "simplified" : "坚持", "traditional" : "堅持", "pinyin" : "jian1chi2", "pinyinAccent" : "jiānchí", "definition" : "persist in; persevere" },
{ "simplified" : "生意", "traditional" : "生意", "pinyin" : "sheng1yi5", "pinyinAccent" : "shēngyi", "definition" : "business; trade" },
{ "simplified" : "火", "traditional" : "火", "pinyin" : "huo3", "pinyinAccent" : "huǒ", "definition" : "fire (Kangxi radical 86)" },
{ "simplified" : "即使", "traditional" : "即使", "pinyin" : "ji2shi3", "pinyinAccent" : "jíshǐ", "definition" : "even if; even though" },
{ "simplified" : "到处", "traditional" : "到處", "pinyin" : "dao4chu4", "pinyinAccent" : "dàochù", "definition" : "everywhere; in all places; all over" },
{ "simplified" : "挂", "traditional" : "挂", "pinyin" : "gua4", "pinyinAccent" : "guà", "definition" : "hang; put up; suspend" },
{ "simplified" : "道歉", "traditional" : "道歉", "pinyin" : "dao4qian4", "pinyinAccent" : "dàoqiàn", "definition" : "apologize; make an apology" },
{ "simplified" : "可怜", "traditional" : "可憐", "pinyin" : "ke3lian2", "pinyinAccent" : "kělián", "definition" : "pitiful; poor; pathetic" },
{ "simplified" : "实在", "traditional" : "實在", "pinyin" : "shi2zai4", "pinyinAccent" : "shízài", "definition" : "honest; in reality; honestly; indeed; certainly" },
{ "simplified" : "骗", "traditional" : "騙", "pinyin" : "pian4", "pinyinAccent" : "piàn", "definition" : "to cheat; to swindle; deceive" },
{ "simplified" : "原谅", "traditional" : "原諒", "pinyin" : "yuan2liang4", "pinyinAccent" : "yuánliàng", "definition" : "to excuse; forgive; to pardon" },
{ "simplified" : "乱", "traditional" : "亂", "pinyin" : "luan4", "pinyinAccent" : "luàn", "definition" : "disorder; confusion; arbitrarily" },
{ "simplified" : "差不多", "traditional" : "差不多", "pinyin" : "cha4bu5duo1", "pinyinAccent" : "chàbuduō", "definition" : "almost; about the same" },
{ "simplified" : "满", "traditional" : "滿", "pinyin" : "man3", "pinyinAccent" : "mǎn", "definition" : "full; abbreviation for Manchurian" },
{ "simplified" : "假", "traditional" : "假", "pinyin" : "jia3, jia4", "pinyinAccent" : "jiǎ, jià", "definition" : "fake; if; borrow | vacation; holiday" },
{ "simplified" : "研究", "traditional" : "研究", "pinyin" : "yan2jiu1", "pinyinAccent" : "yánjiū", "definition" : "to study; to research" },
{ "simplified" : "打扰", "traditional" : "打擾", "pinyin" : "da3rao3", "pinyinAccent" : "dǎrǎo", "definition" : "disturb" },
{ "simplified" : "正确", "traditional" : "正確", "pinyin" : "zheng4que4", "pinyinAccent" : "zhèngquè", "definition" : "correct; proper" },
{ "simplified" : "收", "traditional" : "收", "pinyin" : "shou1", "pinyinAccent" : "shōu", "definition" : "receive; accept; collect; to harvest" },
{ "simplified" : "秒", "traditional" : "秒", "pinyin" : "miao3", "pinyinAccent" : "miǎo", "definition" : "second (unit of time or angle)" },
{ "simplified" : "同时", "traditional" : "同時", "pinyin" : "tong2shi2", "pinyinAccent" : "tóngshí", "definition" : "at the same time; simultaneously" },
{ "simplified" : "提供", "traditional" : "提供", "pinyin" : "ti2gong1", "pinyinAccent" : "tígōng", "definition" : "to supply; provide; furnish" },
{ "simplified" : "输", "traditional" : "輸", "pinyin" : "shu1", "pinyinAccent" : "shū", "definition" : "to transport; to lose (a game, etc.)" },
{ "simplified" : "号码", "traditional" : "號碼", "pinyin" : "hao4ma3", "pinyinAccent" : "hàomǎ", "definition" : "number" },
{ "simplified" : "座", "traditional" : "座", "pinyin" : "zuo4", "pinyinAccent" : "zuò", "definition" : "(mw for mountains, bridges, tall buildings, etc.); | seat; base; stand; constellation" },
{ "simplified" : "比如", "traditional" : "比如", "pinyin" : "bi3ru2", "pinyinAccent" : "bǐrú", "definition" : "for example; for instance; such as" },
{ "simplified" : "严重", "traditional" : "嚴重", "pinyin" : "yan2zhong4", "pinyinAccent" : "yánzhòng", "definition" : "grave; serious; critical" },
{ "simplified" : "脱", "traditional" : "脫", "pinyin" : "tuo1", "pinyinAccent" : "tuō", "definition" : "to shed; take off; to escape" },
{ "simplified" : "陪", "traditional" : "陪", "pinyin" : "pei2", "pinyinAccent" : "péi", "definition" : "accompany; keep company" },
{ "simplified" : "法律", "traditional" : "法律", "pinyin" : "fa3lv4", "pinyinAccent" : "fǎlǜ", "definition" : "law; statute" },
{ "simplified" : "值得", "traditional" : "值得", "pinyin" : "zhi2de5", "pinyinAccent" : "zhíde", "definition" : "be worth; deserve" },
{ "simplified" : "使用", "traditional" : "使用", "pinyin" : "shi3yong4", "pinyinAccent" : "shǐyòng", "definition" : "to use; employ; apply; administer; manipulate" },
{ "simplified" : "方面", "traditional" : "方面", "pinyin" : "fang1mian4", "pinyinAccent" : "fāngmiàn", "definition" : "aspect; field; side" },
{ "simplified" : "原来", "traditional" : "原來", "pinyin" : "yuan2lai2", "pinyinAccent" : "yuánlái", "definition" : "original; former; as it turns out" },
{ "simplified" : "讨论", "traditional" : "討論", "pinyin" : "tao3lun4", "pinyinAccent" : "tǎolùn", "definition" : "to discuss; discussion; to talk over" },
{ "simplified" : "说明", "traditional" : "說明", "pinyin" : "shuo1ming2", "pinyinAccent" : "shuōmíng", "definition" : "explain; explanation; illustrate; to show" },
{ "simplified" : "仍然", "traditional" : "仍然", "pinyin" : "reng2ran2", "pinyinAccent" : "réngrán", "definition" : "still; yet" },
{ "simplified" : "动作", "traditional" : "動作", "pinyin" : "dong4zuo4", "pinyinAccent" : "dòngzuò", "definition" : "movement; motion; action" },
{ "simplified" : "受到", "traditional" : "受到", "pinyin" : "shou4dao4", "pinyinAccent" : "shòudào", "definition" : "receive (influence, restriction, etc.); be subjected to" },
{ "simplified" : "赶", "traditional" : "趕", "pinyin" : "gan3", "pinyinAccent" : "gǎn", "definition" : "catch up; overtake; drive away" },
{ "simplified" : "怀疑", "traditional" : "懷疑", "pinyin" : "huai2yi2", "pinyinAccent" : "huáiyí", "definition" : "doubt; to suspect; be skeptical" },
{ "simplified" : "拒绝", "traditional" : "拒絕", "pinyin" : "ju4jue2", "pinyinAccent" : "jùjué", "definition" : "to refuse; to decline; to reject" },
{ "simplified" : "演员", "traditional" : "演員", "pinyin" : "yan3yuan2", "pinyinAccent" : "yǎnyuán", "definition" : "actor or actress; performer" },
{ "simplified" : "破", "traditional" : "破", "pinyin" : "po4", "pinyinAccent" : "pò", "definition" : "broken; damaged; to split" },
{ "simplified" : "因此", "traditional" : "因此", "pinyin" : "yin1ci3", "pinyinAccent" : "yīncǐ", "definition" : "therefore; thus; that is why; because of this" },
{ "simplified" : "答案", "traditional" : "答案", "pinyin" : "da2'an4", "pinyinAccent" : "dá'àn", "definition" : "answer; solution" },
{ "simplified" : "活动", "traditional" : "活動", "pinyin" : "huo2dong4", "pinyinAccent" : "huódòng", "definition" : "activity; exercise; move about" },
{ "simplified" : "既然", "traditional" : "既然", "pinyin" : "ji4ran2", "pinyinAccent" : "jìrán", "definition" : "since; given that; now that" },
{ "simplified" : "通知", "traditional" : "通知", "pinyin" : "tong1zhi1", "pinyinAccent" : "tōngzhī", "definition" : "notify; to inform; notice" },
{ "simplified" : "不得不", "traditional" : "不得不", "pinyin" : "bu4 de2 bu4", "pinyinAccent" : "bù dé bù", "definition" : "have to; have no choice but to; cannot but" },
{ "simplified" : "无论", "traditional" : "無論", "pinyin" : "wu2lun4", "pinyinAccent" : "wúlùn", "definition" : "no matter what; regardless of whether..." },
{ "simplified" : "刀", "traditional" : "刀", "pinyin" : "dao1", "pinyinAccent" : "dāo", "definition" : "knife; blade (Kangxi radical 18)" },
{ "simplified" : "适合", "traditional" : "適合", "pinyin" : "shi4he2", "pinyinAccent" : "shìhé", "definition" : "to suit; to fit" },
{ "simplified" : "失望", "traditional" : "失望", "pinyin" : "shi1wang4", "pinyinAccent" : "shīwàng", "definition" : "disappointed; lose hope" },
{ "simplified" : "允许", "traditional" : "允許", "pinyin" : "yun3xu3", "pinyinAccent" : "yǔnxǔ", "definition" : "to permit; allow" },
{ "simplified" : "意见", "traditional" : "意見", "pinyin" : "yi4jian4", "pinyinAccent" : "yìjiàn", "definition" : "opinion; view; suggestion; complaint" },
{ "simplified" : "获得", "traditional" : "獲得", "pinyin" : "huo4de2", "pinyinAccent" : "huòdé", "definition" : "obtain; acquire; to gain" },
{ "simplified" : "要是", "traditional" : "要是", "pinyin" : "yao4shi5", "pinyinAccent" : "yàoshi", "definition" : "if; suppose; in case" },
{ "simplified" : "邀请", "traditional" : "邀請", "pinyin" : "yao1qing3", "pinyinAccent" : "yāoqǐng", "definition" : "to invite" },
{ "simplified" : "尽管", "traditional" : "盡管", "pinyin" : "jin3guan3", "pinyinAccent" : "jǐnguǎn", "definition" : "despite; although; even though | freely; without hesitation" },
{ "simplified" : "浪费", "traditional" : "浪費", "pinyin" : "lang4fei4", "pinyinAccent" : "làngfèi", "definition" : "to waste; squander" },
{ "simplified" : "失败", "traditional" : "失敗", "pinyin" : "shi1bai4", "pinyinAccent" : "shībài", "definition" : "be defeated; fail; lose" },
{ "simplified" : "责任", "traditional" : "責任", "pinyin" : "ze2ren4", "pinyinAccent" : "zérèn", "definition" : "responsibility; blame; duty" },
{ "simplified" : "美丽", "traditional" : "美麗", "pinyin" : "mei3li4", "pinyinAccent" : "měilì", "definition" : "beautiful" },
{ "simplified" : "压力", "traditional" : "壓力", "pinyin" : "ya1li4", "pinyinAccent" : "yālì", "definition" : "pressure; stress" },
{ "simplified" : "味道", "traditional" : "味道", "pinyin" : "wei4dao5", "pinyinAccent" : "wèidao", "definition" : "flavor; taste" },
{ "simplified" : "厉害", "traditional" : "厲害", "pinyin" : "li4hai5", "pinyinAccent" : "lìhai", "definition" : "terrible; formidable; fierce; cool; awesome" },
{ "simplified" : "出发", "traditional" : "出發", "pinyin" : "chu1fa1", "pinyinAccent" : "chūfā", "definition" : "start out; set off" },
{ "simplified" : "兴奋", "traditional" : "興奮", "pinyin" : "xing1fen4", "pinyinAccent" : "xīngfèn", "definition" : "excitement; be excited" },
{ "simplified" : "观众", "traditional" : "觀眾", "pinyin" : "guan1zhong4", "pinyinAccent" : "guānzhòng", "definition" : "spectator; audience" },
{ "simplified" : "反对", "traditional" : "反對", "pinyin" : "fan3dui4", "pinyinAccent" : "fǎnduì", "definition" : "oppose; fight against" },
{ "simplified" : "精彩", "traditional" : "精彩", "pinyin" : "jing1cai3", "pinyinAccent" : "jīngcǎi", "definition" : "brilliant; spectacular; wonderful" },
{ "simplified" : "感情", "traditional" : "感情", "pinyin" : "gan3qing2", "pinyinAccent" : "gǎnqíng", "definition" : "feeling; emotion; sensation" },
{ "simplified" : "演出", "traditional" : "演出", "pinyin" : "yan3chu1", "pinyinAccent" : "yǎnchū", "definition" : "to act (in a play); to perform; to put on a show; performance" },
{ "simplified" : "愉快", "traditional" : "愉快", "pinyin" : "yu2kuai4", "pinyinAccent" : "yúkuài", "definition" : "happy; cheerful; delightful" },
{ "simplified" : "开玩笑", "traditional" : "開玩笑", "pinyin" : "kai1 wan2xiao4", "pinyinAccent" : "kāi wánxiào", "definition" : "joke; play a joke; make fun of" },
{ "simplified" : "杂志", "traditional" : "雜志", "pinyin" : "za2zhi4", "pinyinAccent" : "zázhì", "definition" : "magazine" },
{ "simplified" : "合适", "traditional" : "合適", "pinyin" : "he2shi4", "pinyinAccent" : "héshì", "definition" : "suitable; proper; appropriate" },
{ "simplified" : "广告", "traditional" : "廣告", "pinyin" : "guang3gao4", "pinyinAccent" : "guǎnggào", "definition" : "advertisement; a commercial" },
{ "simplified" : "自然", "traditional" : "自然", "pinyin" : "zi4ran2", "pinyinAccent" : "zìrán", "definition" : "nature; natural" },
{ "simplified" : "深", "traditional" : "深", "pinyin" : "shen1", "pinyinAccent" : "shēn", "definition" : "deep; profound; dark (of colors)" },
{ "simplified" : "取", "traditional" : "取", "pinyin" : "qu3", "pinyinAccent" : "qǔ", "definition" : "to take; get; choose" },
{ "simplified" : "短信", "traditional" : "短信", "pinyin" : "duan3xin4", "pinyinAccent" : "duǎnxìn", "definition" : "text message; SMS" },
{ "simplified" : "地球", "traditional" : "地球", "pinyin" : "di4qiu2", "pinyinAccent" : "dìqiú", "definition" : "the Earth; planet" },
{ "simplified" : "帅", "traditional" : "帥", "pinyin" : "shuai4", "pinyinAccent" : "shuài", "definition" : "handsome; graceful; commander-in-chief" },
{ "simplified" : "推", "traditional" : "推", "pinyin" : "tui1", "pinyinAccent" : "tuī", "definition" : "to push; to scrape; to decline; postpone; elect" },
{ "simplified" : "关键", "traditional" : "關鍵", "pinyin" : "guan1jian4", "pinyinAccent" : "guānjiàn", "definition" : "crucial; key; pivotal" },
{ "simplified" : "空", "traditional" : "空", "pinyin" : "kong1, kong4", "pinyinAccent" : "kōng, kòng", "definition" : "empty; sky | leave blank; leisure" },
{ "simplified" : "究竟", "traditional" : "究竟", "pinyin" : "jiu1jing4", "pinyinAccent" : "jiūjìng", "definition" : "after all; when all is said and done; actually" },
{ "simplified" : "恐怕", "traditional" : "恐怕", "pinyin" : "kong3pa4", "pinyinAccent" : "kǒngpà", "definition" : "be afraid; to fear; I'm afraid that..." },
{ "simplified" : "躺", "traditional" : "躺", "pinyin" : "tang3", "pinyinAccent" : "tǎng", "definition" : "recline; lie down (on back or side)" },
{ "simplified" : "聚会", "traditional" : "聚會", "pinyin" : "ju4hui4", "pinyinAccent" : "jùhuì", "definition" : "hold a meeting; get together; a party" },
{ "simplified" : "方向", "traditional" : "方向", "pinyin" : "fang1xiang4", "pinyinAccent" : "fāngxiàng", "definition" : "direction; orientation" },
{ "simplified" : "幸福", "traditional" : "幸福", "pinyin" : "xing4fu2", "pinyinAccent" : "xìngfú", "definition" : "happy; blessed; fortunate" },
{ "simplified" : "接着", "traditional" : "接著", "pinyin" : "jie1zhe5", "pinyinAccent" : "jiēzhe", "definition" : "continue; carry on; to catch; follow" },
{ "simplified" : "技术", "traditional" : "技術", "pinyin" : "ji4shu4", "pinyinAccent" : "jìshù", "definition" : "technology; technique; skill" },
{ "simplified" : "困", "traditional" : "困", "pinyin" : "kun4", "pinyinAccent" : "kùn", "definition" : "sleepy; surround; hard-pressed" },
{ "simplified" : "困难", "traditional" : "困難", "pinyin" : "kun4nan5", "pinyinAccent" : "kùnnan", "definition" : "difficulty; difficult; problem" },
{ "simplified" : "正好", "traditional" : "正好", "pinyin" : "zheng4hao3", "pinyinAccent" : "zhènghǎo", "definition" : "just (in time); just right; just enough; happen to; by chance" },
{ "simplified" : "提醒", "traditional" : "提醒", "pinyin" : "ti2xing3", "pinyinAccent" : "tíxǐng", "definition" : "remind; call attention to; warn of" },
{ "simplified" : "旅行", "traditional" : "旅行", "pinyin" : "lv3xing2", "pinyinAccent" : "lǚxíng", "definition" : "travel" },
{ "simplified" : "激动", "traditional" : "激動", "pinyin" : "ji1dong4", "pinyinAccent" : "jīdòng", "definition" : "excite; agitate" },
{ "simplified" : "骄傲", "traditional" : "驕傲", "pinyin" : "jiao1'ao4", "pinyinAccent" : "jiāo'ào", "definition" : "proud; arrogant; conceited; take pride in" },
{ "simplified" : "毛", "traditional" : "毛", "pinyin" : "mao2", "pinyinAccent" : "máo", "definition" : "hair; fur; feather; dime (Kangxi radical 82)" },
{ "simplified" : "节", "traditional" : "節", "pinyin" : "jie2", "pinyinAccent" : "jié", "definition" : "section; part; festival; moral integrity; save; (mw for class periods)" },
{ "simplified" : "许多", "traditional" : "許多", "pinyin" : "xu3duo1", "pinyinAccent" : "xǔduō", "definition" : "many; a lot; much" },
{ "simplified" : "顺利", "traditional" : "順利", "pinyin" : "shun4li4", "pinyinAccent" : "shùnlì", "definition" : "go smoothly; without a hitch; successful" },
{ "simplified" : "职业", "traditional" : "職業", "pinyin" : "zhi2ye4", "pinyinAccent" : "zhíyè", "definition" : "profession; occupation" },
{ "simplified" : "赚", "traditional" : "賺", "pinyin" : "zhuan4, zuan4", "pinyinAccent" : "zhuàn, zuàn", "definition" : "earn; make a profit | to cheat; to swindle" },
{ "simplified" : "地址", "traditional" : "地址", "pinyin" : "di4zhi3", "pinyinAccent" : "dìzhǐ", "definition" : "address" },
{ "simplified" : "于是", "traditional" : "於是", "pinyin" : "yu2shi4", "pinyinAccent" : "yúshì", "definition" : "as a result; thus; therefore" },
{ "simplified" : "收拾", "traditional" : "收拾", "pinyin" : "shou1shi5", "pinyinAccent" : "shōushi", "definition" : "to tidy; put in order; to repair; to settle with; punish" },
{ "simplified" : "周围", "traditional" : "周圍", "pinyin" : "zhou1wei2", "pinyinAccent" : "zhōuwéi", "definition" : "surroundings; vicinity; environment" },
{ "simplified" : "爱情", "traditional" : "愛情", "pinyin" : "ai4qing2", "pinyinAccent" : "àiqíng", "definition" : "(romantic) love" },
{ "simplified" : "尊重", "traditional" : "尊重", "pinyin" : "zun1zhong4", "pinyinAccent" : "zūnzhòng", "definition" : "esteem; to respect; to value; to honor" },
{ "simplified" : "十分", "traditional" : "十分", "pinyin" : "shi2fen1", "pinyinAccent" : "shífēn", "definition" : "very; fully; 100%" },
{ "simplified" : "教授", "traditional" : "教授", "pinyin" : "jiao4shou4", "pinyinAccent" : "jiàoshòu", "definition" : "professor; instruct; to lecture" },
{ "simplified" : "超过", "traditional" : "超過", "pinyin" : "chao1guo4", "pinyinAccent" : "chāoguò", "definition" : "surpass; exceed; outstrip" },
{ "simplified" : "寄", "traditional" : "寄", "pinyin" : "ji4", "pinyinAccent" : "jì", "definition" : "send by mail" },
{ "simplified" : "顺便", "traditional" : "順便", "pinyin" : "shun4bian4", "pinyinAccent" : "shùnbiàn", "definition" : "conveniently; in passing; on the way" },
{ "simplified" : "无聊", "traditional" : "無聊", "pinyin" : "wu2liao2", "pinyinAccent" : "wúliáo", "definition" : "nonsense; bored; silly; stupid" },
{ "simplified" : "目的", "traditional" : "目的", "pinyin" : "mu4di4", "pinyinAccent" : "mùdì", "definition" : "purpose; aim; goal" },
{ "simplified" : "低", "traditional" : "低", "pinyin" : "di1", "pinyinAccent" : "dī", "definition" : "low; to lower (one's head); droop" },
{ "simplified" : "剩", "traditional" : "剩", "pinyin" : "sheng4", "pinyinAccent" : "shèng", "definition" : "have as remainder; be left over; surplus" },
{ "simplified" : "复杂", "traditional" : "復雜", "pinyin" : "fu4za2", "pinyinAccent" : "fùzá", "definition" : "complicated; complex" },
{ "simplified" : "社会", "traditional" : "社會", "pinyin" : "she4hui4", "pinyinAccent" : "shèhuì", "definition" : "society" },
{ "simplified" : "故意", "traditional" : "故意", "pinyin" : "gu4yi4", "pinyinAccent" : "gùyì", "definition" : "deliberately; intentional; on purpose" },
{ "simplified" : "好处", "traditional" : "好處", "pinyin" : "hao3chu5", "pinyinAccent" : "hǎochu", "definition" : "benefit; advantage" },
{ "simplified" : "竟然", "traditional" : "竟然", "pinyin" : "jing4ran2", "pinyinAccent" : "jìngrán", "definition" : "unexpectedly; to one's surprise; go so far as to" },
{ "simplified" : "表示", "traditional" : "表示", "pinyin" : "biao3shi4", "pinyinAccent" : "biǎoshì", "definition" : "express; show; indicate" },
{ "simplified" : "印象", "traditional" : "印象", "pinyin" : "yin4xiang4", "pinyinAccent" : "yìnxiàng", "definition" : "impression" },
{ "simplified" : "出生", "traditional" : "出生", "pinyin" : "chu1sheng1", "pinyinAccent" : "chūshēng", "definition" : "be born" },
{ "simplified" : "估计", "traditional" : "估計", "pinyin" : "gu1ji4", "pinyinAccent" : "gūjì", "definition" : "appraise; estimate" },
{ "simplified" : "地点", "traditional" : "地點", "pinyin" : "di4dian3", "pinyinAccent" : "dìdiǎn", "definition" : "place; site; location" },
{ "simplified" : "轻", "traditional" : "輕", "pinyin" : "qing1", "pinyinAccent" : "qīng", "definition" : "light; easy; gentle; soft" },
{ "simplified" : "轻松", "traditional" : "輕鬆", "pinyin" : "qing1song1", "pinyinAccent" : "qīngsōng", "definition" : "relaxed; gentle; easygoing" },
{ "simplified" : "作用", "traditional" : "作用", "pinyin" : "zuo4yong4", "pinyinAccent" : "zuòyòng", "definition" : "action; activity; effect" },
{ "simplified" : "举", "traditional" : "舉", "pinyin" : "ju3", "pinyinAccent" : "jǔ", "definition" : "lift; raise; cite" },
{ "simplified" : "小伙子", "traditional" : "小伙子", "pinyin" : "xiao3huo3zi5", "pinyinAccent" : "xiǎohuǒzi", "definition" : "young man; lad; youngster" },
{ "simplified" : "著名", "traditional" : "著名", "pinyin" : "zhu4ming2", "pinyinAccent" : "zhùmíng", "definition" : "famous; well-known; celebration" },
{ "simplified" : "免费", "traditional" : "免費", "pinyin" : "mian3 fei4", "pinyinAccent" : "miǎn fèi", "definition" : "free (of charge); no cost" },
{ "simplified" : "伤心", "traditional" : "傷心", "pinyin" : "shang1xin1", "pinyinAccent" : "shāngxīn", "definition" : "sad; grieve; brokenhearted" },
{ "simplified" : "记者", "traditional" : "記者", "pinyin" : "ji4zhe3", "pinyinAccent" : "jìzhě", "definition" : "reporter; journalist" },
{ "simplified" : "仔细", "traditional" : "仔細", "pinyin" : "zi3xi4", "pinyinAccent" : "zǐxì", "definition" : "careful; attentive; cautious" },
{ "simplified" : "巧克力", "traditional" : "巧克力", "pinyin" : "qiao3ke4li4", "pinyinAccent" : "qiǎokèlì", "definition" : "chocolate" },
{ "simplified" : "辣", "traditional" : "辣", "pinyin" : "la4", "pinyinAccent" : "là", "definition" : "hot (spicy)" },
{ "simplified" : "互相", "traditional" : "互相", "pinyin" : "hu4xiang1", "pinyinAccent" : "hùxiāng", "definition" : "mutually; with each other" },
{ "simplified" : "厕所", "traditional" : "廁所", "pinyin" : "ce4suo3", "pinyinAccent" : "cèsuǒ", "definition" : "bathroom; toilet; lavatory" },
{ "simplified" : "过程", "traditional" : "過程", "pinyin" : "guo4cheng2", "pinyinAccent" : "guòchéng", "definition" : "course of events; process" },
{ "simplified" : "申请", "traditional" : "申請", "pinyin" : "shen1qing3", "pinyinAccent" : "shēnqǐng", "definition" : "apply for; application" },
{ "simplified" : "引起", "traditional" : "引起", "pinyin" : "yin3qi3", "pinyinAccent" : "yǐnqǐ", "definition" : "give rise to; lead to; to cause; arouse" },
{ "simplified" : "发展", "traditional" : "發展", "pinyin" : "fa1zhan3", "pinyinAccent" : "fāzhǎn", "definition" : "develop; development; growth" },
{ "simplified" : "毕业", "traditional" : "畢業", "pinyin" : "bi4 ye4", "pinyinAccent" : "bì yè", "definition" : "to graduate; to finish school" },
{ "simplified" : "正式", "traditional" : "正式", "pinyin" : "zheng4shi4", "pinyinAccent" : "zhèngshì", "definition" : "formal; official" },
{ "simplified" : "厨房", "traditional" : "廚房", "pinyin" : "chu2fang2", "pinyinAccent" : "chúfáng", "definition" : "kitchen" },
{ "simplified" : "专业", "traditional" : "專業", "pinyin" : "zhuan1ye4", "pinyinAccent" : "zhuānyè", "definition" : "profession; specialized field of study; major" },
{ "simplified" : "吸引", "traditional" : "吸引", "pinyin" : "xi1yin3", "pinyinAccent" : "xīyǐn", "definition" : "attract (interest, investment, etc.)" },
{ "simplified" : "心情", "traditional" : "心情", "pinyin" : "xin1qing2", "pinyinAccent" : "xīnqíng", "definition" : "mood; state of mind" },
{ "simplified" : "祝贺", "traditional" : "祝賀", "pinyin" : "zhu4he4", "pinyinAccent" : "zhùhè", "definition" : "congratulate" },
{ "simplified" : "条件", "traditional" : "條件", "pinyin" : "tiao2jian4", "pinyinAccent" : "tiáojiàn", "definition" : "condition; circumstances; prerequisite" },
{ "simplified" : "千万", "traditional" : "千萬", "pinyin" : "qian1wan4", "pinyinAccent" : "qiānwàn", "definition" : "ten million; be sure to; must" },
{ "simplified" : "糖", "traditional" : "糖", "pinyin" : "tang2", "pinyinAccent" : "táng", "definition" : "sugar; candy; sweets" },
{ "simplified" : "趟", "traditional" : "趟", "pinyin" : "tang4, tang1", "pinyinAccent" : "tàng, tāng", "definition" : "(mw for trips times) | to wade" },
{ "simplified" : "由于", "traditional" : "由於", "pinyin" : "you2yu2", "pinyinAccent" : "yóuyú", "definition" : "due to; owing to; as a result of; thanks to" },
{ "simplified" : "密码", "traditional" : "密碼", "pinyin" : "mi4ma3", "pinyinAccent" : "mìmǎ", "definition" : "password; secret code" },
{ "simplified" : "倍", "traditional" : "倍", "pinyin" : "bei4", "pinyinAccent" : "bèi", "definition" : "(two, three, etc)-fold; times (multiplier)" },
{ "simplified" : "擦", "traditional" : "擦", "pinyin" : "ca1", "pinyinAccent" : "cā", "definition" : "to wipe; to rub; to polish" },
{ "simplified" : "尤其", "traditional" : "尤其", "pinyin" : "you2qi2", "pinyinAccent" : "yóuqí", "definition" : "especially; particularly" },
{ "simplified" : "经验", "traditional" : "經驗", "pinyin" : "jing1yan4", "pinyinAccent" : "jīngyàn", "definition" : "experience" },
{ "simplified" : "盒子", "traditional" : "盒子", "pinyin" : "he2zi5", "pinyinAccent" : "hézi", "definition" : "box" },
{ "simplified" : "干杯", "traditional" : "干杯", "pinyin" : "gan1 bei1", "pinyinAccent" : "gān bēi", "definition" : "to drink a toast; cheers!; bottoms up!" },
{ "simplified" : "看法", "traditional" : "看法", "pinyin" : "kan4fa3", "pinyinAccent" : "kànfǎ", "definition" : "point of view; opinion" },
{ "simplified" : "脏", "traditional" : "臟", "pinyin" : "zang1, zang4", "pinyinAccent" : "zāng, zàng", "definition" : "filthy; dirty | internal organs; viscera" },
{ "simplified" : "艺术", "traditional" : "藝術", "pinyin" : "yi4shu4", "pinyinAccent" : "yìshù", "definition" : "art" },
{ "simplified" : "速度", "traditional" : "速度", "pinyin" : "su4du4", "pinyinAccent" : "sùdù", "definition" : "speed; rate; velocity" },
{ "simplified" : "勇敢", "traditional" : "勇敢", "pinyin" : "yong3gan3", "pinyinAccent" : "yǒnggǎn", "definition" : "brave; courageous" },
{ "simplified" : "数字", "traditional" : "數字", "pinyin" : "shu4zi4", "pinyinAccent" : "shùzì", "definition" : "number; numeral; figure; digit" },
{ "simplified" : "暂时", "traditional" : "暫時", "pinyin" : "zan4shi2", "pinyinAccent" : "zànshí", "definition" : "temporary; transient; for the moment" },
{ "simplified" : "优秀", "traditional" : "優秀", "pinyin" : "you1xiu4", "pinyinAccent" : "yōuxiù", "definition" : "outstanding; excellent" },
{ "simplified" : "笑话", "traditional" : "笑話", "pinyin" : "xiao4hua5", "pinyinAccent" : "xiàohua", "definition" : "joke; laugh at" },
{ "simplified" : "可惜", "traditional" : "可惜", "pinyin" : "ke3xi1", "pinyinAccent" : "kěxī", "definition" : "it's a pity; regrettable; too bad" },
{ "simplified" : "响", "traditional" : "響", "pinyin" : "xiang3", "pinyinAccent" : "xiǎng", "definition" : "make a sound; to ring; echo" },
{ "simplified" : "省", "traditional" : "省", "pinyin" : "sheng3, xing3", "pinyinAccent" : "shěng, xǐng", "definition" : "to save; economize; omit; province | examine oneself; to visit; be aware" },
{ "simplified" : "笨", "traditional" : "笨", "pinyin" : "ben4", "pinyinAccent" : "bèn", "definition" : "stupid; foolish; silly; dumb; clumsy" },
{ "simplified" : "科学", "traditional" : "科學", "pinyin" : "ke1xue2", "pinyinAccent" : "kēxué", "definition" : "science; scientific knowledge" },
{ "simplified" : "餐厅", "traditional" : "餐廳", "pinyin" : "can1ting1", "pinyinAccent" : "cāntīng", "definition" : "dining hall; cafeteria; restaurant" },
{ "simplified" : "各", "traditional" : "各", "pinyin" : "ge4", "pinyinAccent" : "gè", "definition" : "each; every" },
{ "simplified" : "距离", "traditional" : "距離", "pinyin" : "ju4li2", "pinyinAccent" : "jùlí", "definition" : "distance; be apart; away from" },
{ "simplified" : "窗户", "traditional" : "窗戶", "pinyin" : "chuang1hu5", "pinyinAccent" : "chuānghu", "definition" : "window" },
{ "simplified" : "空气", "traditional" : "空氣", "pinyin" : "kong1qi4", "pinyinAccent" : "kōngqì", "definition" : "air" },
{ "simplified" : "护士", "traditional" : "護士", "pinyin" : "hu4shi5", "pinyinAccent" : "hùshi", "definition" : "nurse" },
{ "simplified" : "后悔", "traditional" : "后悔", "pinyin" : "hou4hui3", "pinyinAccent" : "hòuhuǐ", "definition" : "to regret; repent" },
{ "simplified" : "大约", "traditional" : "大約", "pinyin" : "da4yue1", "pinyinAccent" : "dàyuē", "definition" : "approximately; about" },
{ "simplified" : "内容", "traditional" : "內容", "pinyin" : "nei4rong2", "pinyinAccent" : "nèiróng", "definition" : "content; substance; details" },
{ "simplified" : "规定", "traditional" : "規定", "pinyin" : "gui1ding4", "pinyinAccent" : "guīdìng", "definition" : "regulation; stipulate; fix; set" },
{ "simplified" : "效果", "traditional" : "效果", "pinyin" : "xiao4guo3", "pinyinAccent" : "xiàoguǒ", "definition" : "effect; result" },
{ "simplified" : "现金", "traditional" : "現金", "pinyin" : "xian4jin1", "pinyinAccent" : "xiànjīn", "definition" : "cash" },
{ "simplified" : "儿童", "traditional" : "兒童", "pinyin" : "er2tong2", "pinyinAccent" : "értóng", "definition" : "child; children" },
{ "simplified" : "租", "traditional" : "租", "pinyin" : "zu1", "pinyinAccent" : "zū", "definition" : "to rent" },
{ "simplified" : "篇", "traditional" : "篇", "pinyin" : "pian1", "pinyinAccent" : "piān", "definition" : "sheet; (mw for articles); piece of writing" },
{ "simplified" : "浪漫", "traditional" : "浪漫", "pinyin" : "lang4man4", "pinyinAccent" : "làngmàn", "definition" : "romantic" },
{ "simplified" : "态度", "traditional" : "態度", "pinyin" : "tai4du5", "pinyinAccent" : "tàidu", "definition" : "manner; bearing; attitude" },
{ "simplified" : "自信", "traditional" : "自信", "pinyin" : "zi4xin4", "pinyinAccent" : "zìxìn", "definition" : "self-confidence" },
{ "simplified" : "吃惊", "traditional" : "吃驚", "pinyin" : "chi1 jing1", "pinyinAccent" : "chī jīng", "definition" : "be startled; be shocked; be amazed" },
{ "simplified" : "熟悉", "traditional" : "熟悉", "pinyin" : "shu2xi1", "pinyinAccent" : "shúxī", "definition" : "familiar with; know well" },
{ "simplified" : "按照", "traditional" : "按照", "pinyin" : "an4zhao4", "pinyinAccent" : "ànzhào", "definition" : "according to; in accordance with; in light of" },
{ "simplified" : "世纪", "traditional" : "世紀", "pinyin" : "shi4ji4", "pinyinAccent" : "shìjì", "definition" : "century" },
{ "simplified" : "回忆", "traditional" : "回憶", "pinyin" : "hui2yi4", "pinyinAccent" : "huíyì", "definition" : "to recall; recollect" },
{ "simplified" : "相同", "traditional" : "相同", "pinyin" : "xiang1tong2", "pinyinAccent" : "xiāngtóng", "definition" : "identical; same; alike" },
{ "simplified" : "重点", "traditional" : "重點", "pinyin" : "zhong4dian3", "pinyinAccent" : "zhòngdiǎn", "definition" : "emphasis; main point" },
{ "simplified" : "教育", "traditional" : "教育", "pinyin" : "jiao4yu4", "pinyinAccent" : "jiàoyù", "definition" : "education" },
{ "simplified" : "受不了", "traditional" : "受不了", "pinyin" : "shou4 bu5 liao3", "pinyinAccent" : "shòu bu liǎo", "definition" : "cannot endure; unbearable; can't stand" },
{ "simplified" : "皮肤", "traditional" : "皮膚", "pinyin" : "pi2fu1", "pinyinAccent" : "pífū", "definition" : "skin" },
{ "simplified" : "区别", "traditional" : "區別", "pinyin" : "qu1bie2", "pinyinAccent" : "qūbié", "definition" : "difference; distinguish" },
{ "simplified" : "左右", "traditional" : "左右", "pinyin" : "zuo3you4", "pinyinAccent" : "zuǒyòu", "definition" : "about; approximate; around | left and right" },
{ "simplified" : "阳光", "traditional" : "陽光", "pinyin" : "yang2guang1", "pinyinAccent" : "yángguāng", "definition" : "sunshine; sunlight" },
{ "simplified" : "页", "traditional" : "頁", "pinyin" : "ye4", "pinyinAccent" : "yè", "definition" : "page; leaf (Kangxi radical 181)" },
{ "simplified" : "文章", "traditional" : "文章", "pinyin" : "wen2zhang1", "pinyinAccent" : "wénzhāng", "definition" : "article; essay" },
{ "simplified" : "语言", "traditional" : "語言", "pinyin" : "yu3yan2", "pinyinAccent" : "yǔyán", "definition" : "language" },
{ "simplified" : "标准", "traditional" : "標准", "pinyin" : "biao1zhun3", "pinyinAccent" : "biāozhǔn", "definition" : "(an official) standard; norm; criterion" },
{ "simplified" : "管理", "traditional" : "管理", "pinyin" : "guan3li3", "pinyinAccent" : "guǎnlǐ", "definition" : "supervise; manage" },
{ "simplified" : "误会", "traditional" : "誤會", "pinyin" : "wu4hui4", "pinyinAccent" : "wùhuì", "definition" : "to misunderstand; to mistake" },
{ "simplified" : "桥", "traditional" : "橋", "pinyin" : "qiao2", "pinyinAccent" : "qiáo", "definition" : "bridge" },
{ "simplified" : "举行", "traditional" : "舉行", "pinyin" : "ju3xing2", "pinyinAccent" : "jǔxíng", "definition" : "convene; to hold (a meeting, ceremony, etc.)" },
{ "simplified" : "肚子", "traditional" : "肚子", "pinyin" : "du4zi5", "pinyinAccent" : "dùzi", "definition" : "belly; abdomen; stomach" },
{ "simplified" : "不仅", "traditional" : "不僅", "pinyin" : "bu4jin3", "pinyinAccent" : "bùjǐn", "definition" : "not only; not just" },
{ "simplified" : "饼干", "traditional" : "餅干", "pinyin" : "bing3gan1", "pinyinAccent" : "bǐnggān", "definition" : "biscuit; cracker; cookie" },
{ "simplified" : "国际", "traditional" : "國際", "pinyin" : "guo2ji4", "pinyinAccent" : "guójì", "definition" : "international" },
{ "simplified" : "信心", "traditional" : "信心", "pinyin" : "xin4xin1", "pinyinAccent" : "xìnxīn", "definition" : "confidence; faith (in sb. or sth.)" },
{ "simplified" : "抬", "traditional" : "抬", "pinyin" : "tai2", "pinyinAccent" : "tái", "definition" : "to lift; to raise (with both palms up); carry (together)" },
{ "simplified" : "竞争", "traditional" : "競爭", "pinyin" : "jing4zheng1", "pinyinAccent" : "jìngzhēng", "definition" : "compete" },
{ "simplified" : "汤", "traditional" : "湯", "pinyin" : "tang1", "pinyinAccent" : "tāng", "definition" : "soup; broth" },
{ "simplified" : "作家", "traditional" : "作家", "pinyin" : "zuo4jia1", "pinyinAccent" : "zuòjiā", "definition" : "author; writer" },
{ "simplified" : "诚实", "traditional" : "誠實", "pinyin" : "cheng2shi2", "pinyinAccent" : "chéngshí", "definition" : "honest; honorable" },
{ "simplified" : "顾客", "traditional" : "顧客", "pinyin" : "gu4ke4", "pinyinAccent" : "gùkè", "definition" : "customer; client" },
{ "simplified" : "存", "traditional" : "存", "pinyin" : "cun2", "pinyinAccent" : "cún", "definition" : "exist; to deposit; to store" },
{ "simplified" : "香", "traditional" : "香", "pinyin" : "xiang1", "pinyinAccent" : "xiāng", "definition" : "fragrant; savory (Kangxi radical 186)" },
{ "simplified" : "打扮", "traditional" : "打扮", "pinyin" : "da3ban5", "pinyinAccent" : "dǎban", "definition" : "dress up; put on make up" },
{ "simplified" : "交流", "traditional" : "交流", "pinyin" : "jiao1liu2", "pinyinAccent" : "jiāoliú", "definition" : "communicate; exchange; give and take; interaction; to alternate" },
{ "simplified" : "年龄", "traditional" : "年齡", "pinyin" : "nian2ling2", "pinyinAccent" : "niánlíng", "definition" : "(a person's) age" },
{ "simplified" : "小说", "traditional" : "小說", "pinyin" : "xiao3shuo1", "pinyinAccent" : "xiǎoshuō", "definition" : "novel; fiction" },
{ "simplified" : "符合", "traditional" : "符合", "pinyin" : "fu2he2", "pinyinAccent" : "fúhé", "definition" : "in keeping with; in accordance with; conform" },
{ "simplified" : "交通", "traditional" : "交通", "pinyin" : "jiao1tong1", "pinyinAccent" : "jiāotōng", "definition" : "traffic; transportation" },
{ "simplified" : "共同", "traditional" : "共同", "pinyin" : "gong4tong2", "pinyinAccent" : "gòngtóng", "definition" : "together; common; joint" },
{ "simplified" : "稍微", "traditional" : "稍微", "pinyin" : "shao1wei1", "pinyinAccent" : "shāowēi", "definition" : "a little bit; slightly" },
{ "simplified" : "增加", "traditional" : "增加", "pinyin" : "zeng1jia1", "pinyinAccent" : "zēngjiā", "definition" : "to increase; to raise; add" },
{ "simplified" : "敲", "traditional" : "敲", "pinyin" : "qiao1", "pinyinAccent" : "qiāo", "definition" : "knock; blackmail" },
{ "simplified" : "适应", "traditional" : "適應", "pinyin" : "shi4ying4", "pinyinAccent" : "shìyìng", "definition" : "to suit; to fit; adapt" },
{ "simplified" : "苦", "traditional" : "苦", "pinyin" : "ku3", "pinyinAccent" : "kǔ", "definition" : "bitter; miserable" },
{ "simplified" : "辛苦", "traditional" : "辛苦", "pinyin" : "xin1ku3", "pinyinAccent" : "xīnkǔ", "definition" : "hard; exhausting; toilsome; laborious" },
{ "simplified" : "然而", "traditional" : "然而", "pinyin" : "ran2'er2", "pinyinAccent" : "rán'ér", "definition" : "however; yet; but" },
{ "simplified" : "耐心", "traditional" : "耐心", "pinyin" : "nai4xin1", "pinyinAccent" : "nàixīn", "definition" : "to be patient" },
{ "simplified" : "将来", "traditional" : "將來", "pinyin" : "jiang1lai2", "pinyinAccent" : "jiānglái", "definition" : "the future" },
{ "simplified" : "沙发", "traditional" : "沙發", "pinyin" : "sha1fa1", "pinyinAccent" : "shāfā", "definition" : "sofa" },
{ "simplified" : "最好", "traditional" : "最好", "pinyin" : "zui4hao3", "pinyinAccent" : "zuìhǎo", "definition" : "the best; had better ...; it would be best" },
{ "simplified" : "禁止", "traditional" : "禁止", "pinyin" : "jin4zhi3", "pinyinAccent" : "jìnzhǐ", "definition" : "to ban; prohibit" },
{ "simplified" : "经济", "traditional" : "經濟", "pinyin" : "jing1ji4", "pinyinAccent" : "jīngjì", "definition" : "economy; economic" },
{ "simplified" : "座位", "traditional" : "座位", "pinyin" : "zuo4wei4", "pinyinAccent" : "zuòwèi", "definition" : "seat; place" },
{ "simplified" : "购物", "traditional" : "購物", "pinyin" : "gou4wu4", "pinyinAccent" : "gòuwù", "definition" : "go shopping; buy goods" },
{ "simplified" : "抽烟", "traditional" : "抽煙", "pinyin" : "chou1yan1", "pinyinAccent" : "chōuyān", "definition" : "to smoke (a cigarette, pipe, etc.)" },
{ "simplified" : "航班", "traditional" : "航班", "pinyin" : "hang2ban1", "pinyinAccent" : "hángbān", "definition" : "scheduled flight; flight number" },
{ "simplified" : "礼貌", "traditional" : "禮貌", "pinyin" : "li3mao4", "pinyinAccent" : "lǐmào", "definition" : "courtesy; politeness; manners" },
{ "simplified" : "提前", "traditional" : "提前", "pinyin" : "ti2qian2", "pinyinAccent" : "tíqián", "definition" : "shift to an earlier date; bring forward; to advance" },
{ "simplified" : "判断", "traditional" : "判斷", "pinyin" : "pan4duan4", "pinyinAccent" : "pànduàn", "definition" : "to judge; judgment; to decide" },
{ "simplified" : "胳膊", "traditional" : "胳膊", "pinyin" : "ge1bo5", "pinyinAccent" : "gēbo", "definition" : "arm" },
{ "simplified" : "整理", "traditional" : "整理", "pinyin" : "zheng3li3", "pinyinAccent" : "zhěnglǐ", "definition" : "put in order; arrange; straighten up; to tidy; to pack (luggage)" },
{ "simplified" : "森林", "traditional" : "森林", "pinyin" : "sen1lin2", "pinyinAccent" : "sēnlín", "definition" : "forest" },
{ "simplified" : "同情", "traditional" : "同情", "pinyin" : "tong2qing2", "pinyinAccent" : "tóngqíng", "definition" : "compassion; sympathy" },
{ "simplified" : "网站", "traditional" : "網站", "pinyin" : "wang3zhan4", "pinyinAccent" : "wǎngzhàn", "definition" : "website" },
{ "simplified" : "商量", "traditional" : "商量", "pinyin" : "shang1liang5", "pinyinAccent" : "shāngliang", "definition" : "consult; talk over; discuss" },
{ "simplified" : "眼镜", "traditional" : "眼鏡", "pinyin" : "yan3jing4", "pinyinAccent" : "yǎnjìng", "definition" : "glasses; spectacles" },
{ "simplified" : "镜子", "traditional" : "鏡子", "pinyin" : "jing4zi5", "pinyinAccent" : "jìngzi", "definition" : "mirror" },
{ "simplified" : "广播", "traditional" : "廣播", "pinyin" : "guang3bo1", "pinyinAccent" : "guǎngbō", "definition" : "broadcast; on the air" },
{ "simplified" : "专门", "traditional" : "專門", "pinyin" : "zhuan1men2", "pinyinAccent" : "zhuānmén", "definition" : "specialized" },
{ "simplified" : "弹钢琴", "traditional" : "彈鋼琴", "pinyin" : "tan2 gang1qin2", "pinyinAccent" : "tán gāngqín", "definition" : "play the piano" },
{ "simplified" : "尝", "traditional" : "嘗", "pinyin" : "chang2", "pinyinAccent" : "cháng", "definition" : "to taste; flavor; (past tense marker)" },
{ "simplified" : "流行", "traditional" : "流行", "pinyin" : "liu2xing2", "pinyinAccent" : "liúxíng", "definition" : "spread; prevalent; be popular" },
{ "simplified" : "材料", "traditional" : "材料", "pinyin" : "cai2liao4", "pinyinAccent" : "cáiliào", "definition" : "material" },
{ "simplified" : "对话", "traditional" : "對話", "pinyin" : "dui4hua4", "pinyinAccent" : "duìhuà", "definition" : "dialogue; conversation" },
{ "simplified" : "详细", "traditional" : "詳細", "pinyin" : "xiang2xi4", "pinyinAccent" : "xiángxì", "definition" : "detailed; in detail; minute" },
{ "simplified" : "随着", "traditional" : "隨著", "pinyin" : "sui2zhe5", "pinyinAccent" : "suízhe", "definition" : "along with; in the wake of" },
{ "simplified" : "降落", "traditional" : "降落", "pinyin" : "jiang4luo4", "pinyinAccent" : "jiàngluò", "definition" : "descend; to land; put down" },
{ "simplified" : "功夫", "traditional" : "功夫", "pinyin" : "gong1fu5", "pinyinAccent" : "gōngfu", "definition" : "kung fu; skill; art; labor" },
{ "simplified" : "严格", "traditional" : "嚴格", "pinyin" : "yan2ge2", "pinyinAccent" : "yángé", "definition" : "strict; stringent; tight" },
{ "simplified" : "日记", "traditional" : "日記", "pinyin" : "ri4ji4", "pinyinAccent" : "rìjì", "definition" : "diary" },
{ "simplified" : "偶尔", "traditional" : "偶爾", "pinyin" : "ou3'er3", "pinyinAccent" : "ǒu'ěr", "definition" : "occasionally; once in a while; sometimes" },
{ "simplified" : "实际", "traditional" : "實際", "pinyin" : "shi2ji4", "pinyinAccent" : "shíjì", "definition" : "actual; reality; practice" },
{ "simplified" : "友好", "traditional" : "友好", "pinyin" : "you3hao3", "pinyinAccent" : "yǒuhǎo", "definition" : "friendly (relations); close friends" },
{ "simplified" : "相反", "traditional" : "相反", "pinyin" : "xiang1fan3", "pinyinAccent" : "xiāngfǎn", "definition" : "opposite; contrary" },
{ "simplified" : "大夫", "traditional" : "大夫", "pinyin" : "dai4fu5", "pinyinAccent" : "dàifu", "definition" : "doctor; physician" },
{ "simplified" : "友谊", "traditional" : "友誼", "pinyin" : "you3yi4", "pinyinAccent" : "yǒuyì", "definition" : "friendship; companionship" },
{ "simplified" : "准确", "traditional" : "准確", "pinyin" : "zhun3que4", "pinyinAccent" : "zhǔnquè", "definition" : "accurate; precise" },
{ "simplified" : "平时", "traditional" : "平時", "pinyin" : "ping2shi2", "pinyinAccent" : "píngshí", "definition" : "ordinarily; in normal times; in peacetime" },
{ "simplified" : "对面", "traditional" : "對面", "pinyin" : "dui4mian4", "pinyinAccent" : "duìmiàn", "definition" : "opposite; across from; the other side" },
{ "simplified" : "脾气", "traditional" : "脾氣", "pinyin" : "pi2qi5", "pinyinAccent" : "píqi", "definition" : "temperament; disposition; temper" },
{ "simplified" : "价格", "traditional" : "價格", "pinyin" : "jia4ge2", "pinyinAccent" : "jiàgé", "definition" : "price" },
{ "simplified" : "性格", "traditional" : "性格", "pinyin" : "xing4ge2", "pinyinAccent" : "xìnggé", "definition" : "nature; personality; temperament" },
{ "simplified" : "鼓励", "traditional" : "鼓勵", "pinyin" : "gu3li4", "pinyinAccent" : "gǔlì", "definition" : "encourage; inspire" },
{ "simplified" : "及时", "traditional" : "及時", "pinyin" : "ji2shi2", "pinyinAccent" : "jíshí", "definition" : "timely; in time; promptly; without delay" },
{ "simplified" : "迷路", "traditional" : "迷路", "pinyin" : "mi2lu4", "pinyinAccent" : "mílù", "definition" : "to get lost" },
{ "simplified" : "棵", "traditional" : "棵", "pinyin" : "ke1", "pinyinAccent" : "kē", "definition" : "(mw for plants)" },
{ "simplified" : "理想", "traditional" : "理想", "pinyin" : "li3xiang3", "pinyinAccent" : "lǐxiǎng", "definition" : "ideal" },
{ "simplified" : "工资", "traditional" : "工資", "pinyin" : "gong1zi1", "pinyinAccent" : "gōngzī", "definition" : "wages; pay; earnings; salary" },
{ "simplified" : "散步", "traditional" : "散步", "pinyin" : "san4 bu4", "pinyinAccent" : "sàn bù", "definition" : "to go for a walk" },
{ "simplified" : "只好", "traditional" : "隻好", "pinyin" : "zhi3hao3", "pinyinAccent" : "zhǐhǎo", "definition" : "have to; be forced to" },
{ "simplified" : "感动", "traditional" : "感動", "pinyin" : "gan3dong4", "pinyinAccent" : "gǎndòng", "definition" : "be moved; to touch emotionally" },
{ "simplified" : "知识", "traditional" : "知識", "pinyin" : "zhi1shi5", "pinyinAccent" : "zhīshi", "definition" : "knowledge; intellectual" },
{ "simplified" : "难受", "traditional" : "難受", "pinyin" : "nan2shou4", "pinyinAccent" : "nánshòu", "definition" : "feel unwell; to suffer pain" },
{ "simplified" : "奖金", "traditional" : "獎金", "pinyin" : "jiang3jin1", "pinyinAccent" : "jiǎngjīn", "definition" : "bonus" },
{ "simplified" : "幽默", "traditional" : "幽默", "pinyin" : "you1mo4", "pinyinAccent" : "yōumò", "definition" : "humorous" },
{ "simplified" : "孙子", "traditional" : "孫子", "pinyin" : "sun1zi5", "pinyinAccent" : "sūnzi", "definition" : "grandson; son's son" },
{ "simplified" : "汗", "traditional" : "汗", "pinyin" : "han4, han2", "pinyinAccent" : "hàn, hán", "definition" : "sweat; perspiration; Khan" },
{ "simplified" : "收入", "traditional" : "收入", "pinyin" : "shou1ru4", "pinyinAccent" : "shōurù", "definition" : "take in; income; revenue" },
{ "simplified" : "酸", "traditional" : "酸", "pinyin" : "suan1", "pinyinAccent" : "suān", "definition" : "sour; sore; ache" },
{ "simplified" : "公里", "traditional" : "公裡", "pinyin" : "gong1li3", "pinyinAccent" : "gōnglǐ", "definition" : "kilometer" },
{ "simplified" : "害羞", "traditional" : "害羞", "pinyin" : "hai4 xiu1", "pinyinAccent" : "hài xiū", "definition" : "blush; shy" },
{ "simplified" : "基础", "traditional" : "基礎", "pinyin" : "ji1chu3", "pinyinAccent" : "jīchǔ", "definition" : "base; foundation" },
{ "simplified" : "准时", "traditional" : "准時", "pinyin" : "zhun3shi2", "pinyinAccent" : "zhǔnshí", "definition" : "punctually; on time" },
{ "simplified" : "积极", "traditional" : "積極", "pinyin" : "ji1ji2", "pinyinAccent" : "jījí", "definition" : "active; positive; energetic" },
{ "simplified" : "富", "traditional" : "富", "pinyin" : "fu4", "pinyinAccent" : "fù", "definition" : "wealthy" },
{ "simplified" : "力气", "traditional" : "力氣", "pinyin" : "li4qi5", "pinyinAccent" : "lìqi", "definition" : "physical strength; effort" },
{ "simplified" : "入口", "traditional" : "入口", "pinyin" : "ru4kou3", "pinyinAccent" : "rùkǒu", "definition" : "entrance" },
{ "simplified" : "袜子", "traditional" : "襪子", "pinyin" : "wa4zi5", "pinyinAccent" : "wàzi", "definition" : "socks; stockings" },
{ "simplified" : "烦恼", "traditional" : "煩惱", "pinyin" : "fan2nao3", "pinyinAccent" : "fánnǎo", "definition" : "worried; vexed" },
{ "simplified" : "举办", "traditional" : "舉辦", "pinyin" : "ju3ban4", "pinyinAccent" : "jǔbàn", "definition" : "to conduct; to hold" },
{ "simplified" : "修理", "traditional" : "修理", "pinyin" : "xiu1li3", "pinyinAccent" : "xiūlǐ", "definition" : "to repair; perform maintenance; to overhaul" },
{ "simplified" : "减少", "traditional" : "減少", "pinyin" : "jian3shao3", "pinyinAccent" : "jiǎnshǎo", "definition" : "reduce; to decrease" },
{ "simplified" : "亲戚", "traditional" : "親戚", "pinyin" : "qin1qi5", "pinyinAccent" : "qīnqi", "definition" : "a relative (i.e. family relation)" },
{ "simplified" : "参观", "traditional" : "參觀", "pinyin" : "can1guan1", "pinyinAccent" : "cānguān", "definition" : "to visit (a place, such as a tourist spot); inspect" },
{ "simplified" : "丰富", "traditional" : "豐富", "pinyin" : "feng1fu4", "pinyinAccent" : "fēngfù", "definition" : "rich; enrich; abundant; plentiful" },
{ "simplified" : "果汁", "traditional" : "果汁", "pinyin" : "guo3zhi1", "pinyinAccent" : "guǒzhī", "definition" : "fruit juice" },
{ "simplified" : "毛巾", "traditional" : "毛巾", "pinyin" : "mao2jin1", "pinyinAccent" : "máojīn", "definition" : "towel; washcloth" },
{ "simplified" : "作者", "traditional" : "作者", "pinyin" : "zuo4zhe3", "pinyinAccent" : "zuòzhě", "definition" : "author; writer" },
{ "simplified" : "海洋", "traditional" : "海洋", "pinyin" : "hai3yang2", "pinyinAccent" : "hǎiyáng", "definition" : "ocean" },
{ "simplified" : "批评", "traditional" : "批評", "pinyin" : "pi1ping2", "pinyinAccent" : "pīpíng", "definition" : "criticize" },
{ "simplified" : "排队", "traditional" : "排隊", "pinyin" : "pai2 dui4", "pinyinAccent" : "pái duì", "definition" : "queue; stand in line" },
{ "simplified" : "例如", "traditional" : "例如", "pinyin" : "li4ru2", "pinyinAccent" : "lìrú", "definition" : "for example; for instance" },
{ "simplified" : "植物", "traditional" : "植物", "pinyin" : "zhi2wu4", "pinyinAccent" : "zhíwù", "definition" : "plant; botanical; vegetation" },
{ "simplified" : "穷", "traditional" : "窮", "pinyin" : "qiong2", "pinyinAccent" : "qióng", "definition" : "poor; exhausted" },
{ "simplified" : "家具", "traditional" : "家具", "pinyin" : "jia1ju4", "pinyinAccent" : "jiājù", "definition" : "furniture" },
{ "simplified" : "盐", "traditional" : "鹽", "pinyin" : "yan2", "pinyinAccent" : "yán", "definition" : "salt" },
{ "simplified" : "温度", "traditional" : "溫度", "pinyin" : "wen1du4", "pinyinAccent" : "wēndù", "definition" : "temperature" },
{ "simplified" : "数量", "traditional" : "數量", "pinyin" : "shu4liang4", "pinyinAccent" : "shùliàng", "definition" : "amount; quantity; number" },
{ "simplified" : "逛", "traditional" : "逛", "pinyin" : "guang4", "pinyinAccent" : "guàng", "definition" : "to stroll; to visit; go window shopping" },
{ "simplified" : "厚", "traditional" : "厚", "pinyin" : "hou4", "pinyinAccent" : "hòu", "definition" : "thick (for flat things); generous" },
{ "simplified" : "亚洲", "traditional" : "亞洲", "pinyin" : "Ya4zhou1", "pinyinAccent" : "Yàzhōu", "definition" : "Asia" },
{ "simplified" : "来不及", "traditional" : "來不及", "pinyin" : "lai2 bu5 ji2", "pinyinAccent" : "lái bu jí", "definition" : "there's not enough time (to do something); it's too late" },
{ "simplified" : "师傅", "traditional" : "師傅", "pinyin" : "shi1fu5", "pinyinAccent" : "shīfu", "definition" : "master; qualified worker; teacher" },
{ "simplified" : "污染", "traditional" : "污染", "pinyin" : "wu1ran3", "pinyinAccent" : "wūrǎn", "definition" : "pollution; contamination" },
{ "simplified" : "来得及", "traditional" : "來得及", "pinyin" : "lai2 de5 ji2", "pinyinAccent" : "lái de jí", "definition" : "there's still time" },
{ "simplified" : "减肥", "traditional" : "減肥", "pinyin" : "jian3fei2", "pinyinAccent" : "jiǎnféi", "definition" : "go on a diet; lose weight" },
{ "simplified" : "客厅", "traditional" : "客廳", "pinyin" : "ke4ting1", "pinyinAccent" : "kètīng", "definition" : "living room; parlor" },
{ "simplified" : "缺少", "traditional" : "缺少", "pinyin" : "que1shao3", "pinyinAccent" : "quēshǎo", "definition" : "to lack; be short of; be deficient in" },
{ "simplified" : "老虎", "traditional" : "老虎", "pinyin" : "lao3hu3", "pinyinAccent" : "lǎohǔ", "definition" : "tiger" },
{ "simplified" : "降低", "traditional" : "降低", "pinyin" : "jiang4di1", "pinyinAccent" : "jiàngdī", "definition" : "reduce; to lower; to drop" },
{ "simplified" : "云", "traditional" : "雲", "pinyin" : "yun2", "pinyinAccent" : "yún", "definition" : "cloud; Yunnan province | say; speak" },
{ "simplified" : "质量", "traditional" : "質量", "pinyin" : "zhi4liang4", "pinyinAccent" : "zhìliàng", "definition" : "quality; mass (physics)" },
{ "simplified" : "学期", "traditional" : "學期", "pinyin" : "xue2qi1", "pinyinAccent" : "xuéqī", "definition" : "semester; school term" },
{ "simplified" : "卫生间", "traditional" : "衛生間", "pinyin" : "wei4sheng1jian1", "pinyinAccent" : "wèishēngjiān", "definition" : "restroom; bathroom; water closet (WC)" },
{ "simplified" : "网球", "traditional" : "網球", "pinyin" : "wang3qiu2", "pinyinAccent" : "wǎngqiú", "definition" : "tennis; tennis ball" },
{ "simplified" : "其次", "traditional" : "其次", "pinyin" : "qi2ci4", "pinyinAccent" : "qícì", "definition" : "next; secondly" },
{ "simplified" : "打招呼", "traditional" : "打招呼", "pinyin" : "da3zhao1hu5", "pinyinAccent" : "dǎzhāohu", "definition" : "notify; greet; inform" },
{ "simplified" : "表格", "traditional" : "表格", "pinyin" : "biao3ge2", "pinyinAccent" : "biǎogé", "definition" : "form (document)" },
{ "simplified" : "阅读", "traditional" : "閱讀", "pinyin" : "yue4du2", "pinyinAccent" : "yuèdú", "definition" : "read; reading" },
{ "simplified" : "信封", "traditional" : "信封", "pinyin" : "xin4feng1", "pinyinAccent" : "xìnfēng", "definition" : "envelope" },
{ "simplified" : "顺序", "traditional" : "順序", "pinyin" : "shun4xu4", "pinyinAccent" : "shùnxù", "definition" : "sequence; order" },
{ "simplified" : "放暑假", "traditional" : "放暑假", "pinyin" : "fang4 shu3jia4", "pinyinAccent" : "fàng shǔjià", "definition" : "have summer vacation" },
{ "simplified" : "乘坐", "traditional" : "乘坐", "pinyin" : "cheng2zuo4", "pinyinAccent" : "chéngzuò", "definition" : "ride; get into (a vehicle)" },
{ "simplified" : "重视", "traditional" : "重視", "pinyin" : "zhong4shi4", "pinyinAccent" : "zhòngshì", "definition" : "to value; take seriously" },
{ "simplified" : "推迟", "traditional" : "推遲", "pinyin" : "tui1chi2", "pinyinAccent" : "tuīchí", "definition" : "postpone; defer" },
{ "simplified" : "缺点", "traditional" : "缺點", "pinyin" : "que1dian3", "pinyinAccent" : "quēdiǎn", "definition" : "weak point; defect; fault; shortcoming" },
{ "simplified" : "加油站", "traditional" : "加油站", "pinyin" : "jia1you2zhan4", "pinyinAccent" : "jiāyóuzhàn", "definition" : "gas station" },
{ "simplified" : "首都", "traditional" : "首都", "pinyin" : "shou3du1", "pinyinAccent" : "shǒudū", "definition" : "capital (city)" },
{ "simplified" : "羡慕", "traditional" : "羨慕", "pinyin" : "xian4mu4", "pinyinAccent" : "xiànmù", "definition" : "to envy; admire" },
{ "simplified" : "零钱", "traditional" : "零錢", "pinyin" : "ling2qian2", "pinyinAccent" : "língqián", "definition" : "small change (of money)" },
{ "simplified" : "暖和", "traditional" : "暖和", "pinyin" : "nuan3huo5", "pinyinAccent" : "nuǎnhuo", "definition" : "warm; nice and warm" },
{ "simplified" : "懒", "traditional" : "懶", "pinyin" : "lan3", "pinyinAccent" : "lǎn", "definition" : "lazy" },
{ "simplified" : "出差", "traditional" : "出差", "pinyin" : "chu1 chai1", "pinyinAccent" : "chū chāi", "definition" : "go on a business trip" },
{ "simplified" : "民族", "traditional" : "民族", "pinyin" : "min2zu2", "pinyinAccent" : "mínzú", "definition" : "nationality; ethnic group" },
{ "simplified" : "传真", "traditional" : "傳真", "pinyin" : "chuan2zhen1", "pinyinAccent" : "chuánzhēn", "definition" : "fax; facsimile" },
{ "simplified" : "优点", "traditional" : "優點", "pinyin" : "you1dian3", "pinyinAccent" : "yōudiǎn", "definition" : "merit; good point; a strength; a benefit" },
{ "simplified" : "垃圾桶", "traditional" : "垃圾桶", "pinyin" : "la1ji1tong3", "pinyinAccent" : "lājītǒng", "definition" : "garbage can" },
{ "simplified" : "加班", "traditional" : "加班", "pinyin" : "jia1 ban1", "pinyinAccent" : "jiā bān", "definition" : "work overtime" },
{ "simplified" : "房东", "traditional" : "房東", "pinyin" : "fang2dong1", "pinyinAccent" : "fángdōng", "definition" : "landlord" },
{ "simplified" : "按时", "traditional" : "按時", "pinyin" : "an4shi2", "pinyinAccent" : "ànshí", "definition" : "on time; on schedule" },
{ "simplified" : "葡萄", "traditional" : "葡萄", "pinyin" : "pu2tao5", "pinyinAccent" : "pútao", "definition" : "grape" },
{ "simplified" : "往往", "traditional" : "往往", "pinyin" : "wang3wang3", "pinyinAccent" : "wǎngwǎng", "definition" : "often; frequently; more often than not" },
{ "simplified" : "高速公路", "traditional" : "高速公路", "pinyin" : "gao1su4 gong1lu4", "pinyinAccent" : "gāosù gōnglù", "definition" : "highway" },
{ "simplified" : "得意", "traditional" : "得意", "pinyin" : "de2yi4", "pinyinAccent" : "déyì", "definition" : "proud of oneself; complacent" },
{ "simplified" : "特点", "traditional" : "特點", "pinyin" : "te4dian3", "pinyinAccent" : "tèdiǎn", "definition" : "a characteristic; trait; feature" },
{ "simplified" : "合格", "traditional" : "合格", "pinyin" : "he2ge2", "pinyinAccent" : "hégé", "definition" : "qualified; up to standard" },
{ "simplified" : "性别", "traditional" : "性別", "pinyin" : "xing4bie2", "pinyinAccent" : "xìngbié", "definition" : "gender; sex; sexual distinction" },
{ "simplified" : "报名", "traditional" : "報名", "pinyin" : "bao4 ming2", "pinyinAccent" : "bào míng", "definition" : "sign up; apply" },
{ "simplified" : "互联网", "traditional" : "互聯網", "pinyin" : "Hu4lian2wang3", "pinyinAccent" : "Hùliánwǎng", "definition" : "Internet" },
{ "simplified" : "景色", "traditional" : "景色", "pinyin" : "jing3se4", "pinyinAccent" : "jǐngsè", "definition" : "scenery; landscape; scene; view" },
{ "simplified" : "大使馆", "traditional" : "大使館", "pinyin" : "da4shi3guan3", "pinyinAccent" : "dàshǐguǎn", "definition" : "embassy" },
{ "simplified" : "总结", "traditional" : "總結", "pinyin" : "zong3jie2", "pinyinAccent" : "zǒngjié", "definition" : "summarize; conclude" },
{ "simplified" : "热闹", "traditional" : "熱鬧", "pinyin" : "re4nao5", "pinyinAccent" : "rènao", "definition" : "bustling; lively; busy" },
{ "simplified" : "郊区", "traditional" : "郊區", "pinyin" : "jiao1qu1", "pinyinAccent" : "jiāoqū", "definition" : "suburbs; outskirts" },
{ "simplified" : "咳嗽", "traditional" : "咳嗽", "pinyin" : "ke2sou5", "pinyinAccent" : "késou", "definition" : "to cough" },
{ "simplified" : "签证", "traditional" : "簽証", "pinyin" : "qian1zheng4", "pinyinAccent" : "qiānzhèng", "definition" : "visa" },
{ "simplified" : "咸", "traditional" : "咸", "pinyin" : "xian2", "pinyinAccent" : "xián", "definition" : "salty; salted; all" },
{ "simplified" : "打印", "traditional" : "打印", "pinyin" : "da3yin4", "pinyinAccent" : "dǎyìn", "definition" : "to print" },
{ "simplified" : "活泼", "traditional" : "活潑", "pinyin" : "huo2po5", "pinyinAccent" : "huópo", "definition" : "lively; vivacious" },
{ "simplified" : "邮局", "traditional" : "郵局", "pinyin" : "you2ju2", "pinyinAccent" : "yóujú", "definition" : "post office" },
{ "simplified" : "牙膏", "traditional" : "牙膏", "pinyin" : "ya2gao1", "pinyinAccent" : "yágāo", "definition" : "toothpaste" },
{ "simplified" : "气候", "traditional" : "氣候", "pinyin" : "qi4hou4", "pinyinAccent" : "qìhòu", "definition" : "climate; atmosphere; weather" },
{ "simplified" : "勺子", "traditional" : "勺子", "pinyin" : "shao2zi5", "pinyinAccent" : "sháozi", "definition" : "spoon; scoop; ladle" },
{ "simplified" : "付款", "traditional" : "付款", "pinyin" : "fu4 kuan3", "pinyinAccent" : "fù kuǎn", "definition" : "to pay" },
{ "simplified" : "理发", "traditional" : "理發", "pinyin" : "li3fa4", "pinyinAccent" : "lǐfà", "definition" : "a barber, hairdressing; haircut" },
{ "simplified" : "复印", "traditional" : "復印", "pinyin" : "fu4yin4", "pinyinAccent" : "fùyìn", "definition" : "photocopy; duplicate" },
{ "simplified" : "词语", "traditional" : "詞語", "pinyin" : "ci2yu3", "pinyinAccent" : "cíyǔ", "definition" : "words and expressions; terms" },
{ "simplified" : "表扬", "traditional" : "表揚", "pinyin" : "biao3yang2", "pinyinAccent" : "biǎoyáng", "definition" : "to praise; commend" },
{ "simplified" : "打针", "traditional" : "打針", "pinyin" : "da3zhen1", "pinyinAccent" : "dǎzhēn", "definition" : "inject; get a shot" },
{ "simplified" : "普遍", "traditional" : "普遍", "pinyin" : "pu3bian4", "pinyinAccent" : "pǔbiàn", "definition" : "common; universal; general; widespread" },
{ "simplified" : "堵车", "traditional" : "堵車", "pinyin" : "du3che1", "pinyinAccent" : "dǔchē", "definition" : "traffic jam" },
{ "simplified" : "叶子", "traditional" : "葉子", "pinyin" : "ye4zi5", "pinyinAccent" : "yèzi", "definition" : "leaves" },
{ "simplified" : "打折", "traditional" : "打折", "pinyin" : "da3zhe2", "pinyinAccent" : "dǎzhé", "definition" : "sell at a discount" },
{ "simplified" : "排列", "traditional" : "排列", "pinyin" : "pai2lie4", "pinyinAccent" : "páiliè", "definition" : "arrange; align; permutation" },
{ "simplified" : "凉快", "traditional" : "涼快", "pinyin" : "liang2kuai5", "pinyinAccent" : "liángkuai", "definition" : "nice and cool; pleasantly cool" },
{ "simplified" : "塑料袋", "traditional" : "塑料袋", "pinyin" : "su4liao4dai4", "pinyinAccent" : "sùliàodài", "definition" : "plastic bag" },
{ "simplified" : "导游", "traditional" : "導游", "pinyin" : "dao3you2", "pinyinAccent" : "dǎoyóu", "definition" : "tour guide" },
{ "simplified" : "小吃", "traditional" : "小吃", "pinyin" : "xiao3chi1", "pinyinAccent" : "xiǎochī", "definition" : "snack; refreshments" },
{ "simplified" : "西红柿", "traditional" : "西紅柿", "pinyin" : "xi1hong2shi4", "pinyinAccent" : "xīhóngshì", "definition" : "tomato" },
{ "simplified" : "招聘", "traditional" : "招聘", "pinyin" : "zhao1pin4", "pinyinAccent" : "zhāopìn", "definition" : "recruitment; take job applications for a job" },
{ "simplified" : "节约", "traditional" : "節約", "pinyin" : "jie2yue1", "pinyinAccent" : "jiéyuē", "definition" : "frugal; to save" },
{ "simplified" : "硕士", "traditional" : "碩士", "pinyin" : "shuo4shi4", "pinyinAccent" : "shuòshì", "definition" : "Master's degree (M.A.)" },
{ "simplified" : "乒乓球", "traditional" : "乒乓球", "pinyin" : "ping1pang1qiu2", "pinyinAccent" : "pīngpāngqiú", "definition" : "ping pong; table tennis" },
{ "simplified" : "积累", "traditional" : "積累", "pinyin" : "ji1lei3", "pinyinAccent" : "jīlěi", "definition" : "accumulate; accumulation" },
{ "simplified" : "橡皮", "traditional" : "橡皮", "pinyin" : "xiang4pi2", "pinyinAccent" : "xiàngpí", "definition" : "rubber; an eraser" },
{ "simplified" : "应聘", "traditional" : "應聘", "pinyin" : "ying4pin4", "pinyinAccent" : "yìngpìn", "definition" : "accept a job offer; to apply for a job" },
{ "simplified" : "矿泉水", "traditional" : "礦泉水", "pinyin" : "kuang4quan2shui3", "pinyinAccent" : "kuàngquánshuǐ", "definition" : "mineral water" },
{ "simplified" : "长城", "traditional" : "長城", "pinyin" : "chang2cheng2", "pinyinAccent" : "chángchéng", "definition" : "the Great Wall" },
{ "simplified" : "语法", "traditional" : "語法", "pinyin" : "yu3fa3", "pinyinAccent" : "yǔfǎ", "definition" : "grammar" },
{ "simplified" : "礼拜天", "traditional" : "禮拜天", "pinyin" : "li3bai4tian1", "pinyinAccent" : "lǐbàitiān", "definition" : "Sunday" },
{ "simplified" : "饺子", "traditional" : "餃子", "pinyin" : "jiao3zi5", "pinyinAccent" : "jiǎozi", "definition" : "dumpling; potsticker" },
{ "simplified" : "国籍", "traditional" : "國籍", "pinyin" : "guo2ji2", "pinyinAccent" : "guójí", "definition" : "nationality" },
{ "simplified" : "售货员", "traditional" : "售貨員", "pinyin" : "shou4huo4yuan2", "pinyinAccent" : "shòuhuòyuán", "definition" : "salesclerk; shop assistant" },
{ "simplified" : "翻译", "traditional" : "翻譯", "pinyin" : "fan1yi4", "pinyinAccent" : "fānyì", "definition" : "translate; translation; interpret" },
{ "simplified" : "流利", "traditional" : "流利", "pinyin" : "liu2li4", "pinyinAccent" : "liúlì", "definition" : "fluent" },
{ "simplified" : "粗心", "traditional" : "粗心", "pinyin" : "cu1xin1", "pinyinAccent" : "cūxīn", "definition" : "careless; inadvertent; negligent" },
{ "simplified" : "养成", "traditional" : "養成", "pinyin" : "yang3cheng2", "pinyinAccent" : "yǎngchéng", "definition" : "cultivate; acquire; to form" },
{ "simplified" : "马虎", "traditional" : "馬虎", "pinyin" : "ma3hu5", "pinyinAccent" : "mǎhu", "definition" : "careless; sloppy; casual" },
{ "simplified" : "百分之", "traditional" : "百分之", "pinyin" : "bai3fen1zhi1", "pinyinAccent" : "bǎifēnzhī", "definition" : "percent" },
{ "simplified" : "普通话", "traditional" : "普通話", "pinyin" : "pu3tong1hua4", "pinyinAccent" : "pǔtōnghuà", "definition" : "Mandarin (common language)" },
{ "simplified" : "登机牌", "traditional" : "登機牌", "pinyin" : "deng1ji1pai2", "pinyinAccent" : "dēngjīpái", "definition" : "boarding pass" },
{ "simplified" : "占线", "traditional" : "佔線", "pinyin" : "zhan4xian4", "pinyinAccent" : "zhànxiàn", "definition" : "the (phone) line is busy" },
{ "simplified" : "包子", "traditional" : "包子", "pinyin" : "bao1zi5", "pinyinAccent" : "bāozi", "definition" : "steamed stuffed bun" },
{ "simplified" : "羽毛球", "traditional" : "羽毛球", "pinyin" : "yu3mao2qiu2", "pinyinAccent" : "yǔmáoqiú", "definition" : "badminton" },
{ "simplified" : "烤鸭", "traditional" : "烤鴨", "pinyin" : "kao3ya1", "pinyinAccent" : "kǎoyā", "definition" : "roast duck" },
{ "simplified" : "寒假", "traditional" : "寒假", "pinyin" : "han2jia4", "pinyinAccent" : "hánjià", "definition" : "winter vacation" },
{ "simplified" : "长江", "traditional" : "長江", "pinyin" : "Chang2jiang1", "pinyinAccent" : "Chángjiāng", "definition" : "the Yangtze River; the Changjiang River" },
{ "simplified" : "预习", "traditional" : "預習", "pinyin" : "yu4xi2", "pinyinAccent" : "yùxí", "definition" : "(of students) prepare a lesson before class; preview" },
{ "simplified" : "填空", "traditional" : "填空", "pinyin" : "tian2kong4", "pinyinAccent" : "tiánkòng", "definition" : "fill in the blanks; fill a vacancy" },
{ "simplified" : "京剧", "traditional" : "京劇", "pinyin" : "jing1ju4", "pinyinAccent" : "jīngjù", "definition" : "Beijing Opera" }
]
